openapi: 3.1.0
info:
  title: datapipeline
paths:
  /:
    POST:
      summary: 'Validate Pipeline Definition '
      description: >-
        <p>Validates the specified pipeline definition to ensure that it is well
        formed and can be run without 
      tags:
        - Definitions
        - Pipelines
        - Validate
