openapi: 3.1.0
info:
  title: devicefarm
paths:
  /:
    POST:
      summary: 'Update VPCE Configuration   '
      description: >-
        <p>Updates information about an Amazon Virtual Private Cloud (VPC)
        endpoint configur
      tags:
        - Configurations
        - VPCE
