openapi: 3.1.0
info:
  title: devops-guru
paths:
  /channels:
    POST:
      summary: 'List Notification Channels '
      description: >-
        <p> Returns a list of notification channels configured for DevOps Guru.
        Each notification channel is used to notify you when DevOps Guru
        generates an insight that contains information about how to improve your
        operations. The one supported notification channel is Amazon Simple
        Notification Service (Amazon SNS). </p>
      tags:
        - Channels
        - Notifications
  /insights/{Id}:
    GET:
      summary: 'Describe Insight '
      description: <p> Returns details about an insight that you specify using its ID. </p>
      tags:
        - Describe
        - Insight
        - Insights
  /accounts/health:
    GET:
      summary: 'Describe Account Health '
      description: >-
        <p> Returns the number of open reactive insights, the number of open
        proactive insights, and the number of metrics analyzed in your Amazon
        Web Services account. Use these numbers to gauge the health of
        operations in your Amazon Web Services account. </p>
      tags:
        - Accounts
        - Describe
        - Health
  /accounts/overview:
    POST:
      summary: Create Accounts Overview
      description: >-
        <p> For the time range passed in, returns the number of open reactive
        insight that were created, the number of open proactive insights that
        were created, and the Mean Time to Recover (MTTR) for all closed
        reactive insights. </p>
      tags:
        - Accounts
        - Overview
  /anomalies/{Id}:
    GET:
      summary: 'Describe Anomaly '
      description: <p> Returns details about an anomaly that you specify using its ID. </p>
      tags:
        - Anomalies
        - Anomaly
        - Describe
  /event-sources:
    PUT:
      summary: 'Update Event Sources Config '
      description: >-
        <p>Enables or disables integration with a service that can be integrated
        with DevOps Guru. The one service that can be integrated with DevOps
        Guru is Amazon CodeGuru Profiler, which can produce proactive
        recommendations which can be stored and viewed in DevOps Guru.</p>
      tags:
        - Configurations
        - Events
        - Sources
  /feedback:
    PUT:
      summary: 'Put Feedback '
      description: <p> Collects customer feedback about the specified insight. </p>
      tags:
        - Feedback
  /organization/health:
    POST:
      summary: 'Describe Organization Health '
      description: >-
        <p>Returns active insights, predictive insights, and resource hours
        analyzed in last hour.</p>
      tags:
        - Describe
        - Health
        - Organizations
  /organization/overview:
    POST:
      summary: 'Describe Organization Overview '
      description: >-
        <p>Returns an overview of your organization's history based on the
        specified time range. The overview includes the total reactive and
        proactive insights.</p>
      tags:
        - Describe
        - Organizations
        - Overview
  /organization/health/resource-collection:
    POST:
      summary: 'Describe Organization Resource Collection Health '
      description: >-
        <p>Provides an overview of your system's health. If additional member
        accounts are part of your organization, you can filter those accounts
        using the <code>AccountIds</code> field.</p>
      tags:
        - Collections
        - Describe
        - Health
        - Organizations
        - Resources
  /accounts/health/resource-collection/{ResourceCollectionType}:
    GET:
      summary: 'Describe Resource Collection Health '
      description: >-
        <p> Returns the number of open proactive insights, open reactive
        insights, and the Mean Time to Recover (MTTR) for all closed insights in
        resource collections in your account. You specify the type of Amazon Web
        Services resources collection. The two types of Amazon Web Services
        resource collections supported are Amazon Web Services CloudFormation
        stacks and Amazon Web Services resources that contain the same Amazon
        Web Services tag. DevOps Guru can be configured to analyze the Amazon
        Web Services resources that are defined in the stacks or that are tagged
        using the same tag <i>key</i>. You can specify up to 500 Amazon Web
        Services CloudFormation stacks. </p>
      tags:
        - Accounts
        - Collections
        - Describe
        - Health
        - Resources
        - Types
  /service-integrations:
    PUT:
      summary: 'Update Service Integration '
      description: >-
        <p> Enables or disables integration with a service that can be
        integrated with DevOps Guru. The one service that can be integrated with
        DevOps Guru is Amazon Web Services Systems Manager, which can be used to
        create an OpsItem for each generated insight. </p>
      tags:
        - Integrations
        - Services
  /cost-estimation:
    PUT:
      summary: 'Start Cost Estimation '
      description: >-
        <p>Starts the creation of an estimate of the monthly cost to analyze
        your Amazon Web Services resources.</p>
      tags:
        - Cost
        - Estimation
  /resource-collections/{ResourceCollectionType}:
    GET:
      summary: 'Get Resource Collection '
      description: >-
        <p> Returns lists Amazon Web Services resources that are of the
        specified resource collection type. The two types of Amazon Web Services
        resource collections supported are Amazon Web Services CloudFormation
        stacks and Amazon Web Services resources that contain the same Amazon
        Web Services tag. DevOps Guru can be configured to analyze the Amazon
        Web Services resources that are defined in the stacks or that are tagged
        using the same tag <i>key</i>. You can specify up to 500 Amazon Web
        Services CloudFormation stacks. </p>
      tags:
        - Collections
        - Resources
        - Types
  /anomalies/insight/{InsightId}:
    POST:
      summary: 'List Anomalies For Insight '
      description: >-
        <p> Returns a list of the anomalies that belong to an insight that you
        specify using its ID. </p>
      tags:
        - Anomalies
        - Insights
  /list-log-anomalies:
    POST:
      summary: 'List Anomalous Log Groups '
      description: <p> Returns the list of log groups that contain log anomalies. </p>
      tags:
        - Anomalies
        - Anomalous
        - Groups
        - Logs
  /events:
    POST:
      summary: 'List Events '
      description: >-
        <p> Returns a list of the events emitted by the resources that are
        evaluated by DevOps Guru. You can use filters to specify which events
        are returned. </p>
      tags:
        - Events
  /insights:
    POST:
      summary: 'List Insights '
      description: >-
        <p> Returns a list of insights in your Amazon Web Services account. You
        can specify which insights are returned by their start time and status
        (<code>ONGOING</code>, <code>CLOSED</code>, or <code>ANY</code>). </p>
      tags:
        - Insights
  /monitoredResources:
    POST:
      summary: 'List Monitored Resources '
      description: >-
        <p> Returns the list of all log groups that are being monitored and
        tagged by DevOps Guru. </p>
      tags:
        - Monitored
        - Resources
  /organization/insights:
    POST:
      summary: 'List Organization Insights '
      description: <p>Returns a list of insights associated with the account or OU Id.</p>
      tags:
        - Insights
        - Organizations
  /recommendations:
    POST:
      summary: 'List Recommendations '
      description: >-
        <p> Returns a list of a specified insight's recommendations. Each
        recommendation includes a list of related metrics and a list of related
        events. </p>
      tags:
        - Recommendations
  /channels/{Id}:
    DELETE:
      summary: 'Remove Notification Channel '
      description: >-
        <p> Removes a notification channel from DevOps Guru. A notification
        channel is used to notify you when DevOps Guru generates an insight that
        contains information about how to improve your operations. </p>
      tags:
        - Channels
        - Notifications
        - Removes
  /insights/search:
    POST:
      summary: 'Search Insights '
      description: >-
        <p> Returns a list of insights in your Amazon Web Services account. You
        can specify which insights are returned by their start time, one or more
        statuses (<code>ONGOING</code> or <code>CLOSED</code>), one or more
        severities (<code>LOW</code>, <code>MEDIUM</code>, and
        <code>HIGH</code>), and type (<code>REACTIVE</code> or
        <code>PROACTIVE</code>). </p> <p> Use the <code>Filters</code> parameter
        to specify status and severity search parameters. Use the
        <code>Type</code> parameter to specify <code>REACTIVE</code> or
        <code>PROACTIVE</code> in your search. </p>
      tags:
        - Insights
        - Search
  /organization/insights/search:
    POST:
      summary: 'Search Organization Insights '
      description: >-
        <p> Returns a list of insights in your organization. You can specify
        which insights are returned by their start time, one or more statuses
        (<code>ONGOING</code>, <code>CLOSED</code>, and <code>CLOSED</code>),
        one or more severities (<code>LOW</code>, <code>MEDIUM</code>, and
        <code>HIGH</code>), and type (<code>REACTIVE</code> or
        <code>PROACTIVE</code>). </p> <p> Use the <code>Filters</code> parameter
        to specify status and severity search parameters. Use the
        <code>Type</code> parameter to specify <code>REACTIVE</code> or
        <code>PROACTIVE</code> in your search. </p>
      tags:
        - Insights
        - Organizations
        - Search
  /resource-collections:
    PUT:
      summary: 'Update Resource Collection '
      description: >-
        <p> Updates the collection of resources that DevOps Guru analyzes. The
        two types of Amazon Web Services resource collections supported are
        Amazon Web Services CloudFormation stacks and Amazon Web Services
        resources that contain the same Amazon Web Services tag. DevOps Guru can
        be configured to analyze the Amazon Web Services resources that are
        defined in the stacks or that are tagged using the same tag <i>key</i>.
        You can specify up to 500 Amazon Web Services CloudFormation stacks.
        This method also creates the IAM role required for you to use DevOps 
      tags:
        - Collections
        - Resources
