openapi: 3.1.0
info:
  title: dlm
paths:
  /policies:
    GET:
      summary: 'Get Lifecycle Policies '
      description: >-
        <p>Gets summary information about all or the specified data lifecycle
        policies.</p> <p>To get complete information about a policy, use <a
        href="https://docs.aws.amazon.com/dlm/latest/APIReference/API_GetLifecyclePolicy.html">GetLifecyclePolicy</a>.</p>
      tags:
        - Lifecycle
        - Policies
  /policies/{policyId}:
    PATCH:
      summary: 'Update Lifecycle Policy '
      description: >-
        <p>Updates the specified lifecycle policy.</p> <p>For more information
        about updating a policy, see <a
        href="https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/view-modify-delete.html#modify">Modify
        lifecycle policies</a>.</p>
      tags:
        - Lifecycle
        - Policies
  /tags/{resourceArn}:
    DELETE:
      summary: 'Untag Resource '
      description: <p>Removes the specified tags from the specified res
      tags:
        - ARN
        - Resources
        - Tags
        - Untag
