openapi: 3.1.0
info:
  title: docdb-elastic
paths:
  /cluster:
    POST:
      summary: 'Create Cluster '
      description: >-
        <p>Creates a new Elastic DocumentDB cluster and returns its Cluster
        structure.</p>
      tags:
        - Cluster
  /cluster-snapshot:
    POST:
      summary: 'Create Cluster Snapshot '
      description: <p>Creates a snapshot of a cluster.</p>
      tags:
        - Cluster
        - Snapshots
  /cluster/{clusterArn}:
    PUT:
      summary: 'Update Cluster '
      description: >-
        <p>Modifies a Elastic DocumentDB cluster. This includes updating
        admin-username/password, upgrading API version setting up a backup
        window and maintenance window</p>
      tags:
        - ARN
        - Cluster
  /cluster-snapshot/{snapshotArn}:
    GET:
      summary: 'Get Cluster Snapshot '
      description: <p>Returns information about a specific Elastic DocumentDB snapshot</p>
      tags:
        - ARN
        - Cluster
        - Snapshots
  /cluster-snapshots:
    GET:
      summary: 'List Cluster Snapshots '
      description: >-
        <p>Returns information about Elastic DocumentDB snapshots for a
        specified cluster.</p>
      tags:
        - Cluster
        - Snapshots
  /clusters:
    GET:
      summary: 'List Clusters '
      description: >-
        <p>Returns information about provisioned Elastic DocumentDB
        clusters.</p>
      tags:
        - Clusters
  /tags/{resourceArn}:
    DELETE:
      summary: 'Untag Resource '
      description: <p>Removes metadata tags to a Elastic DocumentDB resource</p>
      tags:
        - ARN
        - Resources
        - Tags
        - Untag
  /cluster-snapshot/{snapshotArn}/restore:
    POST:
      summary: 'Restore Cluster From Snapshot '
      description: <p>Restores a Elastic DocumentDB cluster from a sna
      tags:
        - ARN
        - Cluster
        - Restore
        - Snapshots
