openapi: 3.1.0
info:
  title: drs
paths:
  /AssociateSourceNetworkStack:
    POST:
      summary: 'Associate Source Network Stack '
      description: >-
        <p>Associate a Source Network to an existing CloudFormation Stack and
        modify launch templates to use this network. Can be used for reverting
        to previously deployed CloudFormation stacks.</p>
      tags:
        - Associate
        - Networks
        - Sources
        - Stack
  /CreateExtendedSourceServer:
    POST:
      summary: 'Create Extended Source Server '
      description: >-
        <p>Create an extended source server in the target Account based on the
        source server in staging account.</p>
      tags:
        - Extended
        - Server
        - Sources
  /CreateLaunchConfigurationTemplate:
    POST:
      summary: 'Create Launch Configuration Template '
      description: <p>Creates a new Launch Configuration Template.</p>
      tags:
        - Configurations
        - Launch
        - Templates
  /CreateReplicationConfigurationTemplate:
    POST:
      summary: 'Create Replication Configuration Template '
      description: <p>Creates a new ReplicationConfigurationTemplate.</p>
      tags:
        - Configurations
        - Replication
        - Templates
  /CreateSourceNetwork:
    POST:
      summary: 'Create Source Network '
      description: <p>Create a new Source Network resource for a provided VPC ID.</p>
      tags:
        - Networks
        - Sources
  /DeleteJob:
    POST:
      summary: 'Delete Job '
      description: <p>Deletes a single Job by ID.</p>
      tags:
        - Jobs
  /DeleteLaunchAction:
    POST:
      summary: 'Delete Launch Action '
      description: <p>Deletes a resource launch action.</p>
      tags:
        - Actions
        - Launch
  /DeleteLaunchConfigurationTemplate:
    POST:
      summary: 'Delete Launch Configuration Template '
      description: <p>Deletes a single Launch Configuration Template by ID.</p>
      tags:
        - Configurations
        - Launch
        - Templates
  /DeleteRecoveryInstance:
    POST:
      summary: 'Delete Recovery Instance '
      description: >-
        <p>Deletes a single Recovery Instance by ID. This deletes the Recovery
        Instance resource from Elastic Disaster Recovery. The Recovery Instance
        must be disconnected first in order to delete it.</p>
      tags:
        - Instances
        - Recovery
  /DeleteReplicationConfigurationTemplate:
    POST:
      summary: 'Delete Replication Configuration Template '
      description: <p>Deletes a single Replication Configuration Template by ID</p>
      tags:
        - Configurations
        - Replication
        - Templates
  /DeleteSourceNetwork:
    POST:
      summary: 'Delete Source Network '
      description: <p>Delete Source Network resource.</p>
      tags:
        - Networks
        - Sources
  /DeleteSourceServer:
    POST:
      summary: 'Delete Source Server '
      description: >-
        <p>Deletes a single Source Server by ID. The Source Server must be
        disconnected first.</p>
      tags:
        - Server
        - Sources
  /DescribeJobLogItems:
    POST:
      summary: 'Describe Job Log Items '
      description: <p>Retrieves a detailed Job log with pagination.</p>
      tags:
        - Describe
        - Items
        - Jobs
        - Logs
  /DescribeJobs:
    POST:
      summary: 'Describe Jobs '
      description: >-
        <p>Returns a list of Jobs. Use the JobsID and fromDate and toDate
        filters to limit which jobs are returned. The response is sorted by
        creationDataTime - latest date first. Jobs are created by the
        StartRecovery, TerminateRecoveryInstances and StartFailbackLaunch APIs.
        Jobs are also created by DiagnosticLaunch and
        TerminateDiagnosticInstances, which are APIs available only to *Support*
        and only used in response to relevant support tickets.</p>
      tags:
        - Describe
        - Jobs
  /DescribeLaunchConfigurationTemplates:
    POST:
      summary: 'Describe Launch Configuration Templates '
      description: >-
        <p>Lists all Launch Configuration Templates, filtered by Launch
        Configuration Template IDs</p>
      tags:
        - Configurations
        - Describe
        - Launch
        - Templates
  /DescribeRecoveryInstances:
    POST:
      summary: 'Describe Recovery Instances '
      description: >-
        <p>Lists all Recovery Instances or multiple Recovery Instances by
        ID.</p>
      tags:
        - Describe
        - Instances
        - Recovery
  /DescribeRecoverySnapshots:
    POST:
      summary: 'Describe Recovery Snapshots '
      description: <p>Lists all Recovery Snapshots for a single Source Server.</p>
      tags:
        - Describe
        - Recovery
        - Snapshots
  /DescribeReplicationConfigurationTemplates:
    POST:
      summary: 'Describe Replication Configuration Templates '
      description: >-
        <p>Lists all ReplicationConfigurationTemplates, filtered by Source
        Server IDs.</p>
      tags:
        - Configurations
        - Describe
        - Replication
        - Templates
  /DescribeSourceNetworks:
    POST:
      summary: 'Describe Source Networks '
      description: >-
        <p>Lists all Source Networks or multiple Source Networks filtered by
        ID.</p>
      tags:
        - Describe
        - Networks
        - Sources
  /DescribeSourceServers:
    POST:
      summary: 'Describe Source Servers '
      description: >-
        <p>Lists all Source Servers or multiple Source Servers filtered by
        ID.</p>
      tags:
        - Describe
        - Servers
        - Sources
  /DisconnectRecoveryInstance:
    POST:
      summary: 'Disconnect Recovery Instance '
      description: >-
        <p>Disconnect a Recovery Instance from Elastic Disaster Recovery. Data
        replication is stopped immediately. All AWS resources created by Elastic
        Disaster Recovery for enabling the replication of the Recovery Instance
        will be terminated / deleted within 90 minutes. If the agent on the
        Recovery Instance has not been prevented from communicating with the
        Elastic Disaster Recovery service, then it will receive a command to
        uninstall itself (within approximately 10 minutes). The following
        properties of the Recovery Instance will be changed immediately:
        dataReplicationInfo.dataReplicationState will be set to DISCONNECTED;
        The totalStorageBytes property for each of
        dataReplicationInfo.replicatedDisks will be set to zero;
        dataReplicationInfo.lagDuration and dataReplicationInfo.lagDuration will
        be nullified.</p>
      tags:
        - Disconnect
        - Instances
        - Recovery
  /DisconnectSourceServer:
    POST:
      summary: 'Disconnect Source Server '
      description: >-
        <p>Disconnects a specific Source Server from Elastic Disaster Recovery.
        Data replication is stopped immediately. All AWS resources created by
        Elastic Disaster Recovery for enabling the replication of the Source
        Server will be terminated / deleted within 90 minutes. You cannot
        disconnect a Source Server if it has a Recovery Instance. If the agent
        on the Source Server has not been prevented from communicating with the
        Elastic Disaster Recovery service, then it will receive a command to
        uninstall itself (within approximately 10 minutes). The following
        properties of the SourceServer will be changed immediately:
        dataReplicationInfo.dataReplicationState will be set to DISCONNECTED;
        The totalStorageBytes property for each of
        dataReplicationInfo.replicatedDisks will be set to zero;
        dataReplicationInfo.lagDuration and dataReplicationInfo.lagDuration will
        be nullified.</p>
      tags:
        - Disconnect
        - Server
        - Sources
  /ExportSourceNetworkCfnTemplate:
    POST:
      summary: 'Export Source Network Cfn Template '
      description: >-
        <p>Export the Source Network CloudFormation template to an S3
        bucket.</p>
      tags:
        - Exports
        - Networks
        - Sources
        - Templates
  /GetFailbackReplicationConfiguration:
    POST:
      summary: 'Get Failback Replication Configuration '
      description: >-
        <p>Lists all Failback ReplicationConfigurations, filtered by Recovery
        Instance ID.</p>
      tags:
        - Configurations
        - Failback
        - Replication
  /GetLaunchConfiguration:
    POST:
      summary: 'Get Launch Configuration '
      description: <p>Gets a LaunchConfiguration, filtered by Source Server IDs.</p>
      tags:
        - Configurations
        - Launch
  /GetReplicationConfiguration:
    POST:
      summary: 'Get Replication Configuration '
      description: <p>Gets a ReplicationConfiguration, filtered by Source Server ID.</p>
      tags:
        - Configurations
        - Replication
  /InitializeService:
    POST:
      summary: 'Initialize Service '
      description: <p>Initialize Elastic Disaster Recovery.</p>
      tags:
        - Initialize
        - Services
  /ListExtensibleSourceServers:
    POST:
      summary: 'List Extensible Source Servers '
      description: >-
        <p>Returns a list of source servers on a staging account that are
        extensible, which means that: a. The source server is not already
        extended into this Account. b. The source server on the Account we’re
        reading from is not an extension of another source server. </p>
      tags:
        - Extensible
        - Servers
        - Sources
  /ListLaunchActions:
    POST:
      summary: 'List Launch Actions '
      description: <p>Lists resource launch actions.</p>
      tags:
        - Actions
        - Launch
  /ListStagingAccounts:
    GET:
      summary: 'List Staging Accounts '
      description: >-
        <p>Returns an array of staging accounts for existing extended source
        servers.</p>
      tags:
        - Accounts
        - Staging
  /tags/{resourceArn}:
    DELETE:
      summary: 'Untag Resource '
      description: >-
        <p>Deletes the specified set of tags from the specified set of Elastic
        Disaster Recovery resources.</p>
      tags:
        - ARN
        - Resources
        - Tags
        - Untag
  /PutLaunchAction:
    POST:
      summary: 'Put Launch Action '
      description: <p>Puts a resource launch action.</p>
      tags:
        - Actions
        - Launch
  /RetryDataReplication:
    POST:
      summary: 'Retry Data Replication '
      description: >-
        <p>WARNING: RetryDataReplication is deprecated. Causes the data
        replication initiation sequence to begin immediately upon next Handshake
        for the specified Source Server ID, regardless of when the previous
        initiation started. This command will work only if the Source Server is
        stalled or is in a DISCONNECTED or STOPPED state. </p>
      tags:
        - Data
        - Replication
        - Retry
  /ReverseReplication:
    POST:
      summary: 'Reverse Replication '
      description: >-
        <p>Start replication to origin / target region - applies only to
        protected instances that originated in EC2. For recovery instances on
        target region - starts replication back to origin region. For failback
        instances on origin region - starts replication to target region to
        re-protect them. </p>
      tags:
        - Replication
        - Reverse
  /StartFailbackLaunch:
    POST:
      summary: 'Start Failback Launch '
      description: >-
        <p>Initiates a Job for launching the machine that is being failed back
        to from the specified Recovery Instance. This will run conversion on the
        failback client and will reboot your machine, thus completing the
        failback process.</p>
      tags:
        - Failback
        - Launch
  /StartRecovery:
    POST:
      summary: 'Start Recovery '
      description: >-
        <p>Launches Recovery Instances for the specified Source Servers. For
        each Source Server you may choose a point in time snapshot to launch
        from, or use an on demand snapshot.</p>
      tags:
        - Recovery
  /StartReplication:
    POST:
      summary: 'Start Replication '
      description: >-
        <p>Starts replication for a stopped Source Server. This action would
        make the Source Server protected again and restart billing for it.</p>
      tags:
        - Replication
  /StartSourceNetworkRecovery:
    POST:
      summary: 'Start Source Network Recovery '
      description: >-
        <p>Deploy VPC for the specified Source Network and modify launch
        templates to use this network. The VPC will be deployed using a
        dedicated CloudFormation stack.</p>
      tags:
        - Networks
        - Recovery
        - Sources
  /StartSourceNetworkReplication:
    POST:
      summary: 'Start Source Network Replication '
      description: >-
        <p>Starts replication for a Source Network. This action would make the
        Source Network protected.</p>
      tags:
        - Networks
        - Replication
        - Sources
  /StopFailback:
    POST:
      summary: 'Stop Failback '
      description: >-
        <p>Stops the failback process for a specified Recovery Instance. This
        changes the Failback State of the Recovery Instance back to
        FAILBACK_NOT_STARTED.</p>
      tags:
        - Failback
        - Stop
  /StopReplication:
    POST:
      summary: 'Stop Replication '
      description: >-
        <p>Stops replication for a Source Server. This action would make the
        Source Server unprotected, delete its existing snapshots and stop
        billing for it.</p>
      tags:
        - Replication
        - Stop
  /StopSourceNetworkReplication:
    POST:
      summary: 'Stop Source Network Replication '
      description: >-
        <p>Stops replication for a Source Network. This action would make the
        Source Network unprotected.</p>
      tags:
        - Networks
        - Replication
        - Sources
        - Stop
  /TerminateRecoveryInstances:
    POST:
      summary: 'Terminate Recovery Instances '
      description: >-
        <p>Initiates a Job for terminating the EC2 resources associated with the
        specified Recovery Instances, and then will delete the Recovery
        Instances from the Elastic Disaster Recovery service.</p>
      tags:
        - Instances
        - Recovery
        - Terminate
  /UpdateFailbackReplicationConfiguration:
    POST:
      summary: 'Update Failback Replication Configuration '
      description: >-
        <p>Allows you to update the failback replication configuration of a
        Recovery Instance by ID.</p>
      tags:
        - Configurations
        - Failback
        - Replication
  /UpdateLaunchConfiguration:
    POST:
      summary: 'Update Launch Configuration '
      description: <p>Updates a LaunchConfiguration by Source Server ID.</p>
      tags:
        - Configurations
        - Launch
  /UpdateLaunchConfigurationTemplate:
    POST:
      summary: 'Update Launch Configuration Template '
      description: <p>Updates an existing Launch Configuration Template by ID.</p>
      tags:
        - Configurations
        - Launch
        - Templates
  /UpdateReplicationConfiguration:
    POST:
      summary: 'Update Replication Configuration '
      description: >-
        <p>Allows you to update a ReplicationConfiguration by Source Server
        ID.</p>
      tags:
        - Configurations
        - Replication
  /UpdateReplicationConfigurationTemplate:
    POST:
      summary: 'Update Replication Configuration Template '
      description: <p>Updates a ReplicationConfigurationTemplate
      tags:
        - Configurations
        - Replication
        - Templates
