openapi: 3.1.0
info:
  title: ebs
paths:
  /snapshots/completion/{snapshotId}:
    POST:
      summary: 'Complete Snapshot '
      description: >-
        <p>Seals and completes the snapshot after all of the required blocks of
        data have been written to it. Completing the snapshot changes the status
        to <code>completed</code>. You cannot write new blocks to a snapshot
        after it has been completed.</p> <note> <p>You should always retry
        requests that receive server (<code>5xx</code>) error responses, and
        <code>ThrottlingException</code> and
        <code>RequestThrottledException</code> client error responses. For more
        information see <a
        href="https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/error-retries.html">Error
        retries</a> in the <i>Amazon Elastic Compute Cloud User Guide</i>.</p>
        </note>
      tags:
        - Complete
        - Completions
        - Snapshots
  /snapshots/{snapshotId}/blocks/{blockIndex}:
    PUT:
      summary: 'Put Snapshot Block '
      description: >-
        <p>Writes a block of data to a snapshot. If the specified block contains
        data, the existing data is overwritten. The target snapshot must be in
        the <code>pending</code> state.</p> <p>Data written to a snapshot must
        be aligned with 512-KiB sectors.</p> <note> <p>You should always retry
        requests that receive server (<code>5xx</code>) error responses, and
        <code>ThrottlingException</code> and
        <code>RequestThrottledException</code> client error responses. For more
        information see <a
        href="https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/error-retries.html">Error
        retries</a> in the <i>Amazon Elastic Compute Cloud User Guide</i>.</p>
        </note>
      tags:
        - Blocks
        - Index
        - Snapshots
  /snapshots/{secondSnapshotId}/changedblocks:
    GET:
      summary: 'List Changed Blocks '
      description: >-
        <p>Returns information about the blocks that are different between two
        Amazon Elastic Block Store snapshots of the same volume/snapshot
        lineage.</p> <note> <p>You should always retry requests that receive
        server (<code>5xx</code>) error responses, and
        <code>ThrottlingException</code> and
        <code>RequestThrottledException</code> client error responses. For more
        information see <a
        href="https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/error-retries.html">Error
        retries</a> in the <i>Amazon Elastic Compute Cloud User Guide</i>.</p>
        </note>
      tags:
        - Blocks
        - Changed
        - Changed Blocks
        - Second
        - Snapshots
  /snapshots/{snapshotId}/blocks:
    GET:
      summary: 'List Snapshot Blocks '
      description: >-
        <p>Returns information about the blocks in an Amazon Elastic Block Store
        snapshot.</p> <note> <p>You should always retry requests that receive
        server (<code>5xx</code>) error responses, and
        <code>ThrottlingException</code> and
        <code>RequestThrottledException</code> client error responses. For more
        information see <a
        href="https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/error-retries.html">Error
        retries</a> in the <i>Amazon Elastic Compute Cloud User Guide</i>.</p>
        </note>
      tags:
        - Blocks
        - Snapshots
  /snapshots:
    POST:
      summary: 'Start Snapshot '
      description: >-
        <p>Creates a new Amazon EBS snapshot. The new snapshot enters the
        <code>pending</code> state after the request completes. </p> <p>After
        creating the snapshot, use <a
        href="https://docs.aws.amazon.com/ebs/latest/APIReference/API_PutSnapshotBlock.html">
        PutSnapshotBlock</a> to write blocks of data to the snapshot.</p> <note>
        <p>You should always retry requests that receive server
        (<code>5xx</code>) error responses, and <code>ThrottlingException</code>
        and <code>RequestThrottledException</code> client error responses. For
        more information see <a
        href="https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/error-retries.html">Error
        retries</a> in the <i>Amazon Elastic Compute Cloud User Guide</i>.</
      tags:
        - Snapshots
        - Snapshots
