openapi: 3.1.0
info:
  title: ecr
paths:
  /:
    POST:
      summary: 'Validate Pull Through Cache Rule '
      description: >-
        <p>Validates an existing pull through cache rule for an upstream
        registry that requires authentication. This will retrieve the contents
        of the Amazon Web Services Secrets Manager secret, verify the syntax,
        and then validate that authentication to the upstream registry is succe
      tags:
        - Cache
        - Pull
        - Rules
        - Validate
