openapi: 3.1.0
info:
  title: elastictranscoder
paths:
  /2012-09-25/jobs/{Id}:
    GET:
      summary: 'Read Job '
      description: <p>The ReadJob operation returns detailed information about a job.</p>
      tags:
        - Jobs
        - Read
  /2012-09-25/jobs:
    POST:
      summary: 'Create Job '
      description: >-
        <p>When you create a job, Elastic Transcoder returns JSON data that
        includes the values that you specified plus information about the job
        that is created.</p> <p>If you have specified more than one output for
        your jobs (for example, one output for the Kindle Fire and another
        output for the Apple iPhone 4s), you currently must use the Elastic
        Transcoder API to list the jobs (as opposed to the AWS Console).</p>
      tags:
        - Jobs
  /2012-09-25/pipelines:
    GET:
      summary: 'List Pipelines '
      description: >-
        <p>The ListPipelines operation gets a list of the pipelines associated
        with the current AWS account.</p>
      tags:
        - Pipelines
  /2012-09-25/presets:
    GET:
      summary: 'List Presets '
      description: >-
        <p>The ListPresets operation gets a list of the default presets included
        with Elastic Transcoder and the presets that you've added in an AWS
        region.</p>
      tags:
        - Presets
  /2012-09-25/pipelines/{Id}:
    PUT:
      summary: 'Update Pipeline '
      description: >-
        <p> Use the <code>UpdatePipeline</code> operation to update settings for
        a pipeline.</p> <important> <p>When you change pipeline settings, your
        changes take effect immediately. Jobs that you have already submitted
        and that Elastic Transcoder has not started to process are affected in
        addition to jobs that you submit after you change settings. </p>
        </important>
      tags:
        - Pipelines
  /2012-09-25/presets/{Id}:
    GET:
      summary: 'Read Preset '
      description: >-
        <p>The ReadPreset operation gets detailed information about a
        preset.</p>
      tags:
        - Presets
        - Read
  /2012-09-25/jobsByPipeline/{PipelineId}:
    GET:
      summary: 'List Jobs By Pipeline '
      description: >-
        <p>The ListJobsByPipeline operation gets a list of the jobs currently in
        a pipeline.</p> <p>Elastic Transcoder returns all of the jobs currently
        in the specified pipeline. The response body contains one element for
        each job that satisfies the search criteria.</p>
      tags:
        - Jobs
        - Pipelines
  /2012-09-25/jobsByStatus/{Status}:
    GET:
      summary: 'List Jobs By Status '
      description: >-
        <p>The ListJobsByStatus operation gets a list of jobs that have a
        specified status. The response body contains one element for each job
        that satisfies the search criteria.</p>
      tags:
        - Jobs
        - Status
  /2012-09-25/roleTests:
    POST:
      summary: 'Test Role '
      description: >-
        <p>The TestRole operation tests the IAM role used to create the
        pipeline.</p> <p>The <code>TestRole</code> action lets you determine
        whether the IAM role you are using has sufficient permissions to let
        Elastic Transcoder perform tasks associated with the transcoding
        process. The action attempts to assume the specified IAM role, checks
        read access to the input and output buckets, and tries to send a test
        notification to Amazon SNS topics that you specify.</p>
      tags:
        - Roles
        - Tests
  /2012-09-25/pipelines/{Id}/notifications:
    POST:
      summary: 'Update Pipeline Notifications '
      description: >-
        <p>With the UpdatePipelineNotifications operation, you can update Amazon
        Simple Notification Service (Amazon SNS) notifications for a
        pipeline.</p> <p>When you update notifications for a pipeline, Elastic
        Transcoder returns the values that you specified in the request.</p>
      tags:
        - Notifications
        - Pipelines
  /2012-09-25/pipelines/{Id}/status:
    POST:
      summary: 'Update Pipeline Status '
      description: >-
        <p>The UpdatePipelineStatus operation pauses or reactivates a pipeline,
        so that the pipeline stops or restarts the processing of jobs.</p>
        <p>Changing the pipeline status is useful if you want to cancel one or
        more jobs. You can't cancel jobs after Elastic Transcoder has started
        processing them; if you pause the pipeline to which you submitted the
        jobs, you have more time to get the job IDs for the jobs that you want
        to cancel, and to send a <a>CancelJob</a> req
      tags:
        - Pipelines
        - Status
