openapi: 3.1.0
info:
  title: elasticache
paths:
  /:
    POST:
      summary: 'Test Migration  '
      description: <p> Async API to test connection between source and target replication g
      tags:
        - Migrations
        - Tests
