openapi: 3.1.0
info:
  title: elasticmapreduce
paths:
  /:
    POST:
      summary: 'Update Studio Session Mapping '
      description: >-
        <p>Updates the session policy attached to the user or group for the
        specified Amazon EMR S
      tags:
        - Mapping
        - Sessions
        - Studios
