openapi: 3.1.0
info:
  title: elasticbeanstalk
paths:
  /:
    POST:
      summary: 'Validate Configuration Settings '
      description: >-
        <p>Takes a set of configuration settings and either a configuration
        template or environment, and determines whether those values are
        valid.</p> <p>This action returns a list of messages indicating any
        errors or warnings associated with the selection of option v
      tags:
        - Configurations
        - Settings
        - Validate
