openapi: 3.1.0
info:
  title: emr-containers
paths:
  /virtualclusters/{virtualClusterId}/jobruns/{jobRunId}:
    GET:
      summary: 'Describe Job Run '
      description: >-
        <p>Displays detailed information about a job run. A job run is a unit of
        work, such as a Spark jar, PySpark script, or SparkSQL query, that you
        submit to Amazon EMR on EKS.</p>
      tags:
        - Clusters
        - Describe
        - Job RUns
        - Jobs
        - Runs
        - Virtual
        - Virtual Clusters
  /jobtemplates:
    GET:
      summary: 'List Job Templates '
      description: >-
        <p>Lists job templates based on a set of parameters. Job template stores
        values of StartJobRun API request in a template and can be used to start
        a job run. Job template allows two use cases: avoid repeating recurring
        StartJobRun API request values, enforcing certain values in StartJobRun
        API request.</p>
      tags:
        - Job Templates
        - Jobs
        - Templates
  /virtualclusters/{virtualClusterId}/endpoints:
    GET:
      summary: 'List Managed Endpoints '
      description: >-
        <p>Lists managed endpoints based on a set of parameters. A managed
        endpoint is a gateway that connects Amazon EMR Studio to Amazon EMR on
        EKS so that Amazon EMR Studio can communicate with your virtual
        cluster.</p>
      tags:
        - Clusters
        - Endpoints
        - Managed
        - Virtual
        - Virtual Clusters
  /virtualclusters:
    GET:
      summary: 'List Virtual Clusters '
      description: >-
        <p>Lists information about the specified virtual cluster. Virtual
        cluster is a managed entity on Amazon EMR on EKS. You can create,
        describe, list and delete virtual clusters. They do not consume any
        additional resource in your system. A single virtual cluster maps to a
        single Kubernetes namespace. Given this relationship, you can model
        virtual clusters the same way you model Kubernetes namespaces to meet
        your requirements.</p>
      tags:
        - Clusters
        - Virtual
        - Virtual Clusters
  /jobtemplates/{templateId}:
    GET:
      summary: 'Describe Job Template '
      description: >-
        <p>Displays detailed information about a specified job template. Job
        template stores values of StartJobRun API request in a template and can
        be used to start a job run. Job template allows two use cases: avoid
        repeating recurring StartJobRun API request values, enforcing certain
        values in StartJobRun API request.</p>
      tags:
        - Describe
        - Job Templates
        - Jobs
        - Templates
  /virtualclusters/{virtualClusterId}/endpoints/{endpointId}:
    GET:
      summary: 'Describe Managed Endpoint '
      description: >-
        <p>Displays detailed information about a managed endpoint. A managed
        endpoint is a gateway that connects Amazon EMR Studio to Amazon EMR on
        EKS so that Amazon EMR Studio can communicate with your virtual
        cluster.</p>
      tags:
        - Clusters
        - Describe
        - Endpoints
        - Managed
        - Virtual
        - Virtual Clusters
  /virtualclusters/{virtualClusterId}:
    GET:
      summary: 'Describe Virtual Cluster '
      description: >-
        <p>Displays detailed information about a specified virtual cluster.
        Virtual cluster is a managed entity on Amazon EMR on EKS. You can
        create, describe, list and delete virtual clusters. They do not consume
        any additional resource in your system. A single virtual cluster maps to
        a single Kubernetes namespace. Given this relationship, you can model
        virtual clusters the same way you model Kubernetes namespaces to meet
        your requirements.</p>
      tags:
        - Clusters
        - Describe
        - Virtual
        - Virtual Clusters
  /virtualclusters/{virtualClusterId}/endpoints/{endpointId}/credentials:
    POST:
      summary: 'Get Managed Endpoint Session Credentials '
      description: <p>Generate a session token to connect to a managed endpoint. </p>
      tags:
        - Clusters
        - Credentials
        - Endpoints
        - Managed
        - Sessions
        - Virtual
        - Virtual Clusters
  /virtualclusters/{virtualClusterId}/jobruns:
    POST:
      summary: 'Start Job Run '
      description: >-
        <p>Starts a job run. A job run is a unit of work, such as a Spark jar,
        PySpark script, or SparkSQL query, that you submit to Amazon EMR on
        EKS.</p>
      tags:
        - Clusters
        - Job RUns
        - Jobs
        - Runs
        - Virtual
        - Virtual Clusters
  /tags/{resourceArn}:
    DELETE:
      summary: 'Untag Resource '
      description: <p>Removes tags from reso
      tags:
        - ARN
        - Resources
        - Tags
        - Untag
