openapi: 3.1.0
info:
  title: emr-serverless
paths:
  /applications/{applicationId}/jobruns/{jobRunId}:
    GET:
      summary: 'Get Job Run '
      description: <p>Displays detailed information about a job run.</p>
      tags:
        - Applications
        - Job RUns
        - Jobs
        - Runs
  /applications:
    GET:
      summary: 'List Applications '
      description: <p>Lists applications based on a set of parameters.</p>
      tags:
        - Applications
  /applications/{applicationId}:
    PATCH:
      summary: 'Update Application '
      description: >-
        <p>Updates a specified application. An application has to be in a
        stopped or created state in order to be updated.</p>
      tags:
        - Applications
  /applications/{applicationId}/jobruns/{jobRunId}/dashboard:
    GET:
      summary: 'Get Dashboard For Job Run '
      description: >-
        <p>Creates and returns a URL that you can use to access the application
        UIs for a job run.</p> <p>For jobs in a running state, the application
        UI is a live user interface such as the Spark or Tez web UI. For
        completed jobs, the application UI is a persistent application user
        interface such as the Spark History Server or persistent Tez UI.</p>
        <note> <p>The URL is valid for one hour after you generate it. To access
        the application UI after that hour elapses, you must invoke the API
        again to generate a new URL.</p> </note>
      tags:
        - Applications
        - Dashboard
        - Job RUns
        - Jobs
        - Runs
  /applications/{applicationId}/jobruns:
    POST:
      summary: 'Start Job Run  '
      description: <p>Starts a job run.</p>
      tags:
        - Applications
        - Job RUns
        - Jobs
        - Runs
  /tags/{resourceArn}:
    DELETE:
      summary: 'Untag Resource '
      description: <p>Removes tags from resources.</p>
      tags:
        - ARN
        - Resources
        - Tags
        - Untag
  /applications/{applicationId}/start:
    POST:
      summary: 'Start Application '
      description: >-
        <p>Starts a specified application and initializes initial capacity if
        configured.</p>
      tags:
        - Applications
  /applications/{applicationId}/stop:
    POST:
      summary: 'Stop Application '
      description: >-
        <p>Stops a specified application and releases initial capacity if
        configured. All scheduled and running jobs must be completed or
        cancelled before stopping an applic
      tags:
        - Applications
        - Stop
