openapi: 3.1.0
info:
  title: entitlement.marketplace
paths:
  /:
    POST:
      summary: 'Get Entitlements '
      description: >-
        <p>GetEntitlements retrieves entitlement values for a given product. The
        results can be filtered based on customer identifier or product dimen
      tags:
        - Entitlements
