openapi: 3.1.0
info:
  title: finspace-data
paths:
  /permission-group/{permissionGroupId}/users/{userId}:
    DELETE:
      summary: 'Disassociate User From Permission Group '
      description: <p>Removes a user from a permission group.</p>
      tags:
        - Disassociate
        - Groups
        - Permission
        - Users
  /datasets/{datasetId}/changesetsv2:
    GET:
      summary: 'List Changesets '
      description: <p>Lists the FinSpace Changesets for a Dataset.</p>
      tags:
        - Change Sets
        - Datasets
  /datasets/{datasetId}/dataviewsv2:
    GET:
      summary: 'List Data Views '
      description: <p>Lists all available Dataviews for a Dataset.</p>
      tags:
        - Data
        - Data Views
        - Datasets
        - Views
  /datasetsv2:
    GET:
      summary: 'List Datasets '
      description: <p>Lists all of the active Datasets that a user has access to.</p>
      tags:
        - Datasets
  /permission-group:
    GET:
      summary: 'List Permission Groups '
      description: <p>Lists all available permission groups in FinSpace.</p>
      tags:
        - Groups
        - Permission
  /user:
    GET:
      summary: 'List Users '
      description: <p>Lists all available users in FinSpace.</p>
      tags:
        - Users
  /datasetsv2/{datasetId}:
    PUT:
      summary: 'Update Dataset '
      description: <p>Updates a FinSpace Dataset.</p>
      tags:
        - Datasets
  /permission-group/{permissionGroupId}:
    PUT:
      summary: 'Update Permission Group '
      description: >-
        <p>Modifies the details of a permission group. You cannot modify a
        <code>permissionGroupID</code>.</p>
      tags:
        - Groups
        - Permission
  /user/{userId}/disable:
    POST:
      summary: 'Disable User '
      description: >-
        <p>Denies access to the FinSpace web application and API for the
        specified user.</p>
      tags:
        - Disable
        - Users
  /user/{userId}/enable:
    POST:
      summary: 'Enable User '
      description: >-
        <p> Allows the specified user to access the FinSpace web application and
        API.</p>
      tags:
        - Enable
        - Users
  /datasets/{datasetId}/changesetsv2/{changesetId}:
    PUT:
      summary: 'Update Changeset '
      description: <p>Updates a FinSpace Changeset.</p>
      tags:
        - Change Sets
        - Datasets
  /datasets/{datasetId}/dataviewsv2/{dataviewId}:
    GET:
      summary: 'Get Data View '
      description: <p>Gets information about a Dataview.</p>
      tags:
        - Data
        - Data Views
        - Datasets
        - View
  /datasets/{datasetId}/dataviewsv2/{dataviewId}/external-access-details:
    POST:
      summary: 'Get External Data View Access Details '
      description: >-
        <p>Returns the credentials to access the external Dataview from an S3
        location. To call this API:</p> <ul> <li> <p>You must retrieve the
        programmatic credentials.</p> </li> <li> <p>You must be a member of a
        FinSpace user group, where the dataset that you want to access has
        <code>Read Dataset Data</code> permissions.</p> </li> </ul>
      tags:
        - Access
        - Data
        - Data Views
        - Datasets
        - Details
        - External
        - View
  /credentials/programmatic:
    GET:
      summary: 'Get Programmatic Access Credentials '
      description: >-
        <p>Request programmatic credentials to use with FinSpace SDK. For more
        information, see <a
        href="https://docs.aws.amazon.com/finspace/latest/data-api/fs-using-the-finspace-api.html#accessing-credentials">Step
        2. Access credentials programmatically using IAM access key id and
        secret access key</a>.</p>
      tags:
        - Access
        - Credentials
        - Programmatic
  /user/{userId}:
    PUT:
      summary: 'Update User '
      description: >-
        <p>Modifies the details of the specified user. You cannot update the
        <code>userId</code> for a user.</p>
      tags:
        - Users
  /workingLocationV1:
    POST:
      summary: 'Get Working Location '
      description: >-
        <p>A temporary Amazon S3 location, where you can copy your files from a
        source location to stage or use as a scratch space in FinSpace
        notebook.</p>
      tags:
        - Locations
        - Working
  /user/{userId}/permission-groups:
    GET:
      summary: 'List Permission Groups By User '
      description: >-
        <p>Lists all the permission groups that are associated with a specific
        user.</p>
      tags:
        - Groups
        - Permission
        - Users
  /permission-group/{permissionGroupId}/users:
    GET:
      summary: 'List Users By Permission Group '
      description: <p>Lists details of all the users in a specific permission group.</p>
      tags:
        - Groups
        - Permission
        - Users
  /user/{userId}/password:
    POST:
      summary: 'Reset User Password '
      description: >-
        <p>Resets the password for a specified user ID and generates a temporary
        one. Only a superuser can reset password for other users. Resetting the
        password immediately invalidates the previous password associated with
        the
      tags:
        - Password
        - Reset
        - Users
