openapi: 3.1.0
info:
  title: fis
paths:
  /experimentTemplates:
    GET:
      summary: 'List Experiment Templates  '
      description: <p>Lists your experiment templates.</p>
      tags:
        - Experiment
        - Templates
  /experimentTemplates/{id}/targetAccountConfigurations/{accountId}:
    PATCH:
      summary: 'Update Target Account Configuration  '
      description: >-
        <p>Updates the target account configuration for the specified experiment
        template.</p>
      tags:
        - Accounts
        - Configurations
        - Experiment
        - Target
        - Templates
  /experimentTemplates/{id}:
    PATCH:
      summary: 'Update Experiment Template  '
      description: <p>Updates the specified experiment template.</p>
      tags:
        - Experiment
        - Templates
  /actions/{id}:
    GET:
      summary: 'Get Action  '
      description: <p>Gets information about the specified FIS action.</p>
      tags:
        - Actions
  /experiments/{id}:
    DELETE:
      summary: 'Stop Experiment  '
      description: <p>Stops the specified experiment.</p>
      tags:
        - Experiment
        - Experiments
        - Stop
  /experiments/{id}/targetAccountConfigurations/{accountId}:
    GET:
      summary: 'Get Experiment Target Account Configuration  '
      description: >-
        <p>Gets information about the specified target account configuration of
        the experiment.</p>
      tags:
        - Accounts
        - Configurations
        - Experiment
        - Experiments
        - Target
  /targetResourceTypes/{resourceType}:
    GET:
      summary: 'Get Target Resource Type  '
      description: <p>Gets information about the specified resource type.</p>
      tags:
        - Resources
        - Target
        - Types
  /actions:
    GET:
      summary: 'List Actions  '
      description: <p>Lists the available FIS actions.</p>
      tags:
        - Actions
  /experiments/{id}/resolvedTargets:
    GET:
      summary: 'List Experiment Resolved Targets  '
      description: >-
        <p>Lists the resolved targets information of the specified
        experiment.</p>
      tags:
        - Experiment
        - Experiments
        - Resolved
        - Targets
  /experiments/{id}/targetAccountConfigurations:
    GET:
      summary: 'List Experiment Target Account Configurations  '
      description: >-
        <p>Lists the target account configurations of the specified
        experiment.</p>
      tags:
        - Accounts
        - Configurations
        - Experiment
        - Experiments
        - Target
  /experiments:
    POST:
      summary: 'Start Experiment  '
      description: >-
        <p>Starts running an experiment from the specified experiment
        template.</p>
      tags:
        - Experiment
        - Experiments
  /tags/{resourceArn}:
    DELETE:
      summary: 'Untag Resource  '
      description: <p>Removes the specified tags from the specified resource.</p>
      tags:
        - ARN
        - Resources
        - Tags
        - Untag
  /experimentTemplates/{id}/targetAccountConfigurations:
    GET:
      summary: 'List Target Account Configurations  '
      description: >-
        <p>Lists the target account configurations of the specified experiment
        template.</p>
      tags:
        - Accounts
        - Configurations
        - Experiment
        - Target
        - Templates
  /targetResourceTypes:
    GET:
      summary: 'List Target Resource Types  '
      description: <p>Lists the target resource
      tags:
        - Resources
        - Target
        - Types
