openapi: 3.1.0
info:
  title: fms
paths:
  /:
    POST:
      summary: 'Untag Resource '
      description: <p>Removes one or more tags from an Amazon Web Services res
      tags:
        - Resources
        - Untag
