openapi: 3.1.0
info:
  title: fsx
paths:
  /:
    POST:
      summary: 'Update Volume '
      description: >-
        <p>Updates the configuration of an Amazon FSx for NetApp ONTAP or Amazon
        FSx for OpenZFS v
      tags:
        - Volumes
