openapi: 3.1.0
info:
  title: greengrass
paths:
  /greengrass/groups/{GroupId}/role:
    GET:
      summary: 'Get Associated Role '
      description: Retrieves the role associated with a particular group.
      tags:
        - Associated
        - Green Grass
        - Groups
        - Roles
  /greengrass/servicerole:
    GET:
      summary: 'Get Service Role For Account '
      description: Retrieves the service role that is attached to your account.
      tags:
        - Accounts
        - Green Grass
        - Roles
        - Service Roles
        - Services
  /greengrass/definition/connectors:
    GET:
      summary: 'List Connector Definitions '
      description: Retrieves a list of connector definitions.
      tags:
        - Connectors
        - Definitions
        - Green Grass
  /greengrass/definition/connectors/{ConnectorDefinitionId}/versions:
    GET:
      summary: 'List Connector Definition Versions '
      description: >-
        Lists the versions of a connector definition, which are containers for
        connectors. Connectors run on the Greengrass core and contain built-in
        integration with local infrastructure, device protocols, AWS, and other
        cloud services.
      tags:
        - Connectors
        - Definitions
        - Green Grass
        - Versions
  /greengrass/definition/cores:
    GET:
      summary: 'List Core Definitions '
      description: Retrieves a list of core definitions.
      tags:
        - Core
        - Cores
        - Definitions
        - Green Grass
  /greengrass/definition/cores/{CoreDefinitionId}/versions:
    GET:
      summary: 'List Core Definition Versions '
      description: Lists the versions of a core definition.
      tags:
        - Core
        - Cores
        - Definitions
        - Green Grass
        - Versions
  /greengrass/groups/{GroupId}/deployments:
    GET:
      summary: 'List Deployments '
      description: Returns a history of deployments for the group.
      tags:
        - Deployments
        - Green Grass
        - Groups
  /greengrass/definition/devices:
    GET:
      summary: 'List Device Definitions '
      description: Retrieves a list of device definitions.
      tags:
        - Definitions
        - Device
        - Devices
        - Green Grass
  /greengrass/definition/devices/{DeviceDefinitionId}/versions:
    GET:
      summary: 'List Device Definition Versions '
      description: Lists the versions of a device definition.
      tags:
        - Definitions
        - Device
        - Devices
        - Green Grass
        - Versions
  /greengrass/definition/functions:
    GET:
      summary: 'List Function Definitions '
      description: Retrieves a list of Lambda function definitions.
      tags:
        - Definitions
        - Functions
        - Green Grass
  /greengrass/definition/functions/{FunctionDefinitionId}/versions:
    GET:
      summary: 'List Function Definition Versions '
      description: Lists the versions of a Lambda function definition.
      tags:
        - Definitions
        - Functions
        - Green Grass
        - Versions
  /greengrass/groups:
    GET:
      summary: 'List Groups '
      description: Retrieves a list of groups.
      tags:
        - Green Grass
        - Groups
  /greengrass/groups/{GroupId}/certificateauthorities:
    GET:
      summary: 'List Group Certificate Authorities '
      description: Retrieves the current CAs for a group.
      tags:
        - Authorities
        - Certificate Authorities
        - Certificates
        - Green Grass
        - Groups
  /greengrass/groups/{GroupId}/versions:
    GET:
      summary: 'List Group Versions '
      description: Lists the versions of a group.
      tags:
        - Green Grass
        - Groups
        - Versions
  /greengrass/definition/loggers:
    GET:
      summary: 'List Logger Definitions '
      description: Retrieves a list of logger definitions.
      tags:
        - Definitions
        - Green Grass
        - Loggers
  /greengrass/definition/loggers/{LoggerDefinitionId}/versions:
    GET:
      summary: 'List Logger Definition Versions '
      description: Lists the versions of a logger definition.
      tags:
        - Definitions
        - Green Grass
        - Loggers
        - Versions
  /greengrass/definition/resources:
    GET:
      summary: 'List Resource Definitions '
      description: Retrieves a list of resource definitions.
      tags:
        - Definitions
        - Green Grass
        - Resources
  /greengrass/definition/resources/{ResourceDefinitionId}/versions:
    GET:
      summary: 'List Resource Definition Versions '
      description: Lists the versions of a resource definition.
      tags:
        - Definitions
        - Green Grass
        - Resources
        - Versions
  /greengrass/updates:
    POST:
      summary: 'Create Software Update Job '
      description: >-
        Creates a software update for a core or group of cores (specified as an
        IoT thing group.) Use this to update the OTA Agent as well as the
        Greengrass core software. It makes use of the IoT Jobs feature which
        provides additional commands to manage a Greengrass core software update
        job.
      tags:
        - Green Grass
        - Jobs
        - Software
  /greengrass/definition/subscriptions:
    GET:
      summary: 'List Subscription Definitions '
      description: Retrieves a list of subscription definitions.
      tags:
        - Definitions
        - Green Grass
        - Subscriptions
  /greengrass/definition/subscriptions/{SubscriptionDefinitionId}/versions:
    GET:
      summary: 'List Subscription Definition Versions '
      description: Lists the versions of a subscription definition.
      tags:
        - Definitions
        - Green Grass
        - Subscriptions
        - Versions
  /greengrass/definition/connectors/{ConnectorDefinitionId}:
    PUT:
      summary: 'Update Connector Definition '
      description: Updates a connector definition.
      tags:
        - Connectors
        - Definitions
        - Green Grass
  /greengrass/definition/cores/{CoreDefinitionId}:
    PUT:
      summary: 'Update Core Definition '
      description: Updates a core definition.
      tags:
        - Core
        - Cores
        - Definitions
        - Green Grass
  /greengrass/definition/devices/{DeviceDefinitionId}:
    PUT:
      summary: 'Update Device Definition '
      description: Updates a device definition.
      tags:
        - Definitions
        - Device
        - Devices
        - Green Grass
  /greengrass/definition/functions/{FunctionDefinitionId}:
    PUT:
      summary: 'Update Function Definition '
      description: Updates a Lambda function definition.
      tags:
        - Definitions
        - Functions
        - Green Grass
  /greengrass/groups/{GroupId}:
    PUT:
      summary: 'Update Group '
      description: Updates a group.
      tags:
        - Green Grass
        - Groups
  /greengrass/definition/loggers/{LoggerDefinitionId}:
    PUT:
      summary: 'Update Logger Definition '
      description: Updates a logger definition.
      tags:
        - Definitions
        - Green Grass
        - Loggers
  /greengrass/definition/resources/{ResourceDefinitionId}:
    PUT:
      summary: 'Update Resource Definition '
      description: Updates a resource definition.
      tags:
        - Definitions
        - Green Grass
        - Resources
  /greengrass/definition/subscriptions/{SubscriptionDefinitionId}:
    PUT:
      summary: 'Update Subscription Definition '
      description: Updates a subscription definition.
      tags:
        - Definitions
        - Green Grass
        - Subscriptions
  /greengrass/bulk/deployments/{BulkDeploymentId}/status:
    GET:
      summary: 'Get Bulk Deployment Status '
      description: Returns the status of a bulk deployment.
      tags:
        - Bulk
        - Deployments
        - Green Grass
        - Status
  /greengrass/things/{ThingName}/connectivityInfo:
    PUT:
      summary: 'Update Connectivity Info '
      description: >-
        Updates the connectivity information for the core. Any devices that
        belong to the group which has this core will receive this information in
        order to find the location of the core and connect to it.
      tags:
        - Connectivity
        - Green Grass
        - Info
        - Names
        - Things
  /greengrass/definition/connectors/{ConnectorDefinitionId}/versions/{ConnectorDefinitionVersionId}:
    GET:
      summary: 'Get Connector Definition Version '
      description: >-
        Retrieves information about a connector definition version, including
        the connectors that the version contains. Connectors are prebuilt
        modules that interact with local infrastructure, device protocols, AWS,
        and other cloud services.
      tags:
        - Connectors
        - Definitions
        - Green Grass
        - Versions
  /greengrass/definition/cores/{CoreDefinitionId}/versions/{CoreDefinitionVersionId}:
    GET:
      summary: 'Get Core Definition Version '
      description: Retrieves information about a core definition version.
      tags:
        - Core
        - Cores
        - Definitions
        - Green Grass
        - Versions
  /greengrass/groups/{GroupId}/deployments/{DeploymentId}/status:
    GET:
      summary: 'Get Deployment Status '
      description: Returns the status of a deployment.
      tags:
        - Deployments
        - Green Grass
        - Groups
        - Status
  /greengrass/definition/devices/{DeviceDefinitionId}/versions/{DeviceDefinitionVersionId}:
    GET:
      summary: 'Get Device Definition Version '
      description: Retrieves information about a device definition version.
      tags:
        - Definitions
        - Device
        - Devices
        - Green Grass
        - Versions
  /greengrass/definition/functions/{FunctionDefinitionId}/versions/{FunctionDefinitionVersionId}:
    GET:
      summary: 'Get Function Definition Version '
      description: >-
        Retrieves information about a Lambda function definition version,
        including which Lambda functions are included in the version and their
        configurations.
      tags:
        - Definitions
        - Functions
        - Green Grass
        - Versions
  /greengrass/groups/{GroupId}/certificateauthorities/{CertificateAuthorityId}:
    GET:
      summary: 'Get Group Certificate Authority '
      description: >-
        Retreives the CA associated with a group. Returns the public key of the
        CA.
      tags:
        - Authority
        - Certificate Authorities
        - Certificates
        - Green Grass
        - Groups
  /greengrass/groups/{GroupId}/certificateauthorities/configuration/expiry:
    PUT:
      summary: 'Update Group Certificate Configuration '
      description: Updates the Certificate expiry time for a group.
      tags:
        - Certificate Authorities
        - Certificates
        - Configurations
        - Expiry
        - Green Grass
        - Groups
  /greengrass/groups/{GroupId}/versions/{GroupVersionId}:
    GET:
      summary: 'Get Group Version '
      description: Retrieves information about a group version.
      tags:
        - Green Grass
        - Groups
        - Versions
  /greengrass/definition/loggers/{LoggerDefinitionId}/versions/{LoggerDefinitionVersionId}:
    GET:
      summary: 'Get Logger Definition Version '
      description: Retrieves information about a logger definition version.
      tags:
        - Definitions
        - Green Grass
        - Loggers
        - Versions
  /greengrass/definition/resources/{ResourceDefinitionId}/versions/{ResourceDefinitionVersionId}:
    GET:
      summary: 'Get Resource Definition Version '
      description: >-
        Retrieves information about a resource definition version, including
        which resources are included in the version.
      tags:
        - Definitions
        - Green Grass
        - Resources
        - Versions
  /greengrass/definition/subscriptions/{SubscriptionDefinitionId}/versions/{SubscriptionDefinitionVersionId}:
    GET:
      summary: 'Get Subscription Definition Version '
      description: Retrieves information about a subscription definition version.
      tags:
        - Definitions
        - Green Grass
        - Subscriptions
        - Versions
  /greengrass/things/{ThingName}/runtimeconfig:
    PUT:
      summary: 'Update Thing Runtime Configuration '
      description: Updates the runtime configuration of a thing.
      tags:
        - Configurations
        - Green Grass
        - Names
        - Runtime
        - Runtime Configurations
        - Things
  /greengrass/bulk/deployments/{BulkDeploymentId}/detailed-reports:
    GET:
      summary: 'List Bulk Deployment Detailed Reports '
      description: >-
        Gets a paginated list of the deployments that have been started in a
        bulk deployment operation, and their current deployment status.
      tags:
        - Bulk
        - Deployments
        - Detailed
        - Green Grass
        - Reports
  /greengrass/bulk/deployments:
    POST:
      summary: 'Start Bulk Deployment '
      description: >-
        Deploys multiple groups in one operation. This action starts the bulk
        deployment of a specified set of group versions. Each group version
        deployment will be triggered with an adaptive rate that has a fixed
        upper limit. We recommend that you include an ''X-Amzn-Client-Token''
        token in every ''StartBulkDeployment'' request. These requests are
        idempotent with respect to the token and the request parameters.
      tags:
        - Bulk
        - Deployments
        - Green Grass
  /tags/{resource-arn}:
    DELETE:
      summary: 'Untag Resource '
      description: Remove resource tags from a Greengrass Resource.
      tags:
        - ARN
        - Resources
        - Tags
        - Untag
  /greengrass/groups/{GroupId}/deployments/$reset:
    POST:
      summary: 'Reset Deployments '
      description: Resets a group's deployments.
      tags:
        - $Reset
        - Deployments
        - Green Grass
        - Groups
        - Reset
  /greengrass/bulk/deployments/{BulkDeploymentId}/$stop:
    PUT:
      summary: 'Stop Bulk Deployment '
      description: >-
        Stops the execution of a bulk deployment. This action returns a status
        of ''Stopping'' until the deployment is stopped. You cannot start a new
        bulk deployment while a previous deployment is in the ''Stopping''
        state. This action doesn't rollback completed deployments or cancel
        pending de
      tags:
        - $Stop
        - Bulk
        - Deployments
        - Green Grass
        - Stop
