openapi: 3.1.0
info:
  title: groundstation
paths:
  /contact/{contactId}:
    GET:
      summary: 'Describe Contact '
      description: <p>Describes an existing contact.</p>
      tags:
        - Contacts
        - Describe
  /config:
    GET:
      summary: 'List Configs '
      description: <p>Returns a list of <code>Config</code> objects.</p>
      tags:
        - Configurations
  /dataflowEndpointGroup:
    GET:
      summary: 'List Dataflow Endpoint Groups '
      description: <p>Returns a list of <code>DataflowEndpoint</code> groups.</p>
      tags:
        - Dataflow
        - Endpoints
        - Groups
  /ephemeris:
    POST:
      summary: 'Create Ephemeris '
      description: >-
        <p>Creates an Ephemeris with the specified
        <code>EphemerisData</code>.</p>
      tags: []
  /missionprofile:
    GET:
      summary: 'List Mission Profiles '
      description: <p>Returns a list of mission profiles.</p>
      tags:
        - Mission
        - Mission Profile
        - Profiles
  /config/{configType}/{configId}:
    PUT:
      summary: 'Update Config '
      description: >-
        <p>Updates the <code>Config</code> used when scheduling contacts.</p>
        <p>Updating a <code>Config</code> will not update the execution
        parameters for existing future contacts scheduled with this
        <code>Config</code>.</p>
      tags:
        - Configurations
        - Types
  /dataflowEndpointGroup/{dataflowEndpointGroupId}:
    GET:
      summary: 'Get Dataflow Endpoint Group '
      description: <p>Returns the dataflow endpoint group.</p>
      tags:
        - Dataflow
        - Endpoints
        - Groups
  /ephemeris/{ephemerisId}:
    PUT:
      summary: 'Update Ephemeris '
      description: <p>Updates an existing ephemeris</p>
      tags: []
  /missionprofile/{missionProfileId}:
    PUT:
      summary: 'Update Mission Profile '
      description: >-
        <p>Updates a mission profile.</p> <p>Updating a mission profile will not
        update the execution parameters for existing future contacts.</p>
      tags:
        - Mission
        - Mission Profile
        - Profiles
  /agent/{agentId}/configuration:
    GET:
      summary: 'Get Agent Configuration '
      description: >-
        <note> <p> For use by AWS Ground Station Agent and shouldn't be called
        directly.</p> </note> <p>Gets the latest configuration information for a
        registered agent.</p>
      tags:
        - Agent
        - Configurations
  /minute-usage:
    POST:
      summary: 'Get Minute Usage '
      description: <p>Returns the number of reserved minutes used by account.</p>
      tags:
        - Minute
        - Usage
  /satellite/{satelliteId}:
    GET:
      summary: 'Get Satellite '
      description: <p>Returns a satellite.</p>
      tags:
        - Satellites
  /contacts:
    POST:
      summary: 'List Contacts '
      description: >-
        <p>Returns a list of contacts.</p> <p>If <code>statusList</code>
        contains AVAILABLE, the request must include <code>groundStation</code>,
        <code>missionprofileArn</code>, and <code>satelliteArn</code>. </p>
      tags:
        - Contacts
  /ephemerides:
    POST:
      summary: 'List Ephemerides '
      description: <p>List existing ephemerides.</p>
      tags:
        - Ephemer
  /groundstation:
    GET:
      summary: 'List Ground Stations '
      description: <p>Returns a list of ground stations. </p>
      tags:
        - Ground
        - Groundstation
        - Stations
  /satellite:
    GET:
      summary: 'List Satellites '
      description: <p>Returns a list of satellites.</p>
      tags:
        - Satellites
  /tags/{resourceArn}:
    DELETE:
      summary: 'Untag Resource '
      description: <p>Deassigns a resource tag.</p>
      tags:
        - ARN
        - Resources
        - Tags
        - Untag
  /agent:
    POST:
      summary: 'Register Agent '
      description: >-
        <note> <p> For use by AWS Ground Station Agent and shouldn't be called
        directly.</p> </note> <p> Registers a new agent with AWS Ground Station.
        </p>
      tags:
        - Agent
        - Register
  /contact:
    POST:
      summary: 'Reserve Contact '
      description: <p>Reserves a contact using specified parameters.</p>
      tags:
        - Contacts
        - Reserve
  /agent/{agentId}:
    PUT:
      summary: 'Update Agent Status '
      description: >-
        <note> <p> For use by AWS Ground Station Agent and shouldn't be called
        directly.</p> </note> <p>Update the status of the 
      tags:
        - Agent
        - Status
