openapi: 3.1.0
info:
  title: internetmonitor
paths:
  /v20210603/Monitors:
    GET:
      summary: 'List Monitors '
      description: >-
        <p>Lists all of your monitors for Amazon CloudWatch Internet Monitor and
        their statuses, along with the Amazon Resource Name (ARN) and name of
        each monitor.</p>
      tags:
        - Monitors
        - V20210603
  /v20210603/Monitors/{MonitorName}:
    PATCH:
      summary: 'Update Monitor '
      description: >-
        <p>Updates a monitor. You can update a monitor to change the percentage
        of traffic to monitor or the maximum number of city-networks (locations
        and ASNs), to add or remove resources, or to change the status of the
        monitor. Note that you can't change the name of a monitor.</p> <p>The
        city-network maximum that you choose is the limit, but you only pay for
        the number of city-networks that are actually monitored. For more
        information, see <a
        href="https://docs.aws.amazon.com/AmazonCloudWatch/latest/monitoring/IMCityNetworksMaximum.html">Choosing
        a city-network maximum value</a> in the <i>Amazon CloudWatch User
        Guide</i>.</p>
      tags:
        - Monitors
        - Names
        - V20210603
  /v20210603/Monitors/{MonitorName}/HealthEvents/{EventId}:
    GET:
      summary: 'Get Health Event '
      description: >-
        <p>Gets information the Amazon CloudWatch Internet Monitor has created
        and stored about a health event for a specified monitor. This
        information includes the impacted locations, and all the information
        related to the event, by location.</p> <p>The information returned
        includes the impact on performance, availability, and round-trip time,
        information about the network providers (ASNs), the event type, and so
        on.</p> <p>Information rolled up at the global traffic level is also
        returned, including the impact type and total traffic impact.</p>
      tags:
        - Events
        - Health
        - Monitors
        - Names
        - V20210603
  /v20210603/Monitors/{MonitorName}/Queries/{QueryId}/Results:
    GET:
      summary: 'Get Query Results '
      description: >-
        <p>Return the data for a query with the Amazon CloudWatch Internet
        Monitor query interface. Specify the query that you want to return
        results for by providing a <code>QueryId</code> and a monitor name.</p>
        <p>For more information about using the query interface, including
        examples, see <a
        href="https://docs.aws.amazon.com/AmazonCloudWatch/latest/monitoring/CloudWatch-IM-view-cw-tools-cwim-query.html">Using
        the Amazon CloudWatch Internet Monitor query interface</a> in the Amazon
        CloudWatch Internet Monitor User Guide.</p>
      tags:
        - Monitors
        - Names
        - Queries
        - Results
        - V20210603
  /v20210603/Monitors/{MonitorName}/Queries/{QueryId}/Status:
    GET:
      summary: 'Get Query Status '
      description: >-
        <p>Returns the current status of a query for the Amazon CloudWatch
        Internet Monitor query interface, for a specified query ID and monitor.
        When you run a query, check the status to make sure that the query has
        <code>SUCCEEDED</code> before you review the results.</p> <ul> <li> <p>
        <code>QUEUED</code>: The query is scheduled to run.</p> </li> <li> <p>
        <code>RUNNING</code>: The query is in progress but not complete.</p>
        </li> <li> <p> <code>SUCCEEDED</code>: The query completed
        sucessfully.</p> </li> <li> <p> <code>FAILED</code>: The query failed
        due to an error.</p> </li> <li> <p> <code>CANCELED</code>: The query was
        canceled.</p> </li> </ul>
      tags:
        - Monitors
        - Names
        - Queries
        - Status
        - V20210603
  /v20210603/Monitors/{MonitorName}/HealthEvents:
    GET:
      summary: 'List Health Events '
      description: >-
        <p>Lists all health events for a monitor in Amazon CloudWatch Internet
        Monitor. Returns information for health events including the event start
        and end time and the status.</p> <note> <p>Health events that have start
        times during the time frame that is requested are not included in the
        list of health events.</p> </note>
      tags:
        - Events
        - Health
        - Monitors
        - Names
        - V20210603
  /tags/{ResourceArn}:
    DELETE:
      summary: 'Untag Resource '
      description: <p>Removes a tag from a resource.</p>
      tags:
        - ARN
        - Resources
        - Tags
        - Untag
  /v20210603/Monitors/{MonitorName}/Queries:
    POST:
      summary: 'Start Query '
      description: >-
        <p>Start a query to return data for a specific query type for the Amazon
        CloudWatch Internet Monitor query interface. Specify a time period for
        the data that you want returned by using <code>StartTime</code> and
        <code>EndTime</code>. You filter the query results to return by
        providing parameters that you specify with
        <code>FilterParameters</code>.</p> <p>For more information about using
        the query interface, including examples, see <a
        href="https://docs.aws.amazon.com/AmazonCloudWatch/latest/monitoring/CloudWatch-IM-view-cw-tools-cwim-query.html">Using
        the Amazon CloudWatch Internet Monitor query interface</a> in the Amazon
        CloudWatch Internet Monitor User Guide.</p>
      tags:
        - Monitors
        - Names
        - Queries
        - V20210603
  /v20210603/Monitors/{MonitorName}/Queries/{QueryId}:
    DELETE:
      summary: 'Stop Query '
      description: <p>Stop a query that is progress for a specific mo
      tags:
        - Monitors
        - Names
        - Queries
        - Stop
        - V20210603
