openapi: 3.1.0
info:
  title: iot1click-devices
paths:
  /claims/{claimCode}:
    PUT:
      summary: 'Claim Devices By Claim Code '
      description: >-
        <p>Adds device(s) to your account (i.e., claim one or more devices) if
        and only if you
         received a claim code with the device(s).</p>
      tags:
        - Claim
        - Claims
        - Code
        - Devices
  /devices/{deviceId}:
    GET:
      summary: 'Describe Device '
      description: >-
        <p>Given a device ID, returns a DescribeDeviceResponse object describing
        the
         details of the device.</p>
      tags:
        - Describe
        - Device
        - Devices
  /devices/{deviceId}/finalize-claim:
    PUT:
      summary: 'Finalize Device Claim '
      description: >-
        <p>Given a device ID, finalizes the claim request for the associated
        device.</p><note>
         <p>Claiming a device consists of initiating a claim, then publishing a device event,
         and finalizing the claim. For a device of type button, a device event can
         be published by simply clicking the device.</p>
         </note>
      tags:
        - Claim
        - Device
        - Devices
        - Finalize
  /devices/{deviceId}/methods:
    POST:
      summary: 'Invoke Device Method '
      description: >-
        <p>Given a device ID, issues a request to invoke a named device method
        (with possible
         parameters). See the "Example POST" code snippet below.</p>
      tags:
        - Device
        - Devices
        - Invoke
        - Methods
  /devices/{deviceId}/initiate-claim:
    PUT:
      summary: 'Initiate Device Claim '
      description: >-
        <p>Given a device ID, initiates a claim request for the associated
        device.</p><note>
         <p>Claiming a device consists of initiating a claim, then publishing a device event,
         and finalizing the claim. For a device of type button, a device event can
         be published by simply clicking the device.</p>
         </note>
      tags:
        - Claim
        - Device
        - Devices
        - Initiate
  /devices/{deviceId}/events:
    GET:
      summary: 'List Device Events '
      description: >-
        <p>Using a device ID, returns a DeviceEventsResponse object containing
        an
         array of events for the device.</p>
      tags:
        - Device
        - Devices
        - Events
  /devices:
    GET:
      summary: 'List Devices '
      description: >-
        <p>Lists the 1-Click compatible devices associated with your AWS
        account.</p>
      tags:
        - Devices
  /tags/{resource-arn}:
    DELETE:
      summary: 'Untag Resource '
      description: >-
        <p>Using tag keys, deletes the tags (key/value pairs) associated with
        the specified
         resource ARN.</p>
      tags:
        - ARN
        - Resources
        - Tags
        - Untag
  /devices/{deviceId}/unclaim:
    PUT:
      summary: 'Unclaim Device '
      description: <p>Disassociates a device from your AWS account using its device ID.</p>
      tags:
        - Device
        - Devices
        - Unclaim
  /devices/{deviceId}/state:
    PUT:
      summary: 'Update Device State '
      description: |-
        <p>Using a Boolean value (true or false), this operation
         enables or disables the device given a devi
      tags:
        - Device
        - Devices
        - States
