openapi: 3.1.0
info:
  title: iotdeviceadvisor
paths:
  /suiteDefinitions:
    GET:
      summary: 'List Suite Definitions '
      description: >-
        <p>Lists the Device Advisor test suites you have created.</p>
        <p>Requires permission to access the <a
        href="https://docs.aws.amazon.com/service-authorization/latest/reference/list_awsiot.html#awsiot-actions-as-permissions">ListSuiteDefinitions</a>
        action.</p>
      tags:
        - Definitions
        - Suites
  /suiteDefinitions/{suiteDefinitionId}:
    PATCH:
      summary: 'Update Suite Definition '
      description: >-
        <p>Updates a Device Advisor test suite.</p> <p>Requires permission to
        access the <a
        href="https://docs.aws.amazon.com/service-authorization/latest/reference/list_awsiot.html#awsiot-actions-as-permissions">UpdateSuiteDefinition</a>
        action.</p>
      tags:
        - Definitions
        - Suites
  /endpoint:
    GET:
      summary: 'Get Endpoint '
      description: <p>Gets information about an Device Advisor endpoint.</p>
      tags:
        - Endpoints
  /suiteDefinitions/{suiteDefinitionId}/suiteRuns/{suiteRunId}:
    GET:
      summary: 'Get Suite Run '
      description: >-
        <p>Gets information about a Device Advisor test suite run.</p>
        <p>Requires permission to access the <a
        href="https://docs.aws.amazon.com/service-authorization/latest/reference/list_awsiot.html#awsiot-actions-as-permissions">GetSuiteRun</a>
        action.</p>
      tags:
        - Definitions
        - Runs
        - Suites
  /suiteDefinitions/{suiteDefinitionId}/suiteRuns/{suiteRunId}/report:
    GET:
      summary: 'Get Suite Run Report '
      description: >-
        <p>Gets a report download link for a successful Device Advisor
        qualifying test suite run.</p> <p>Requires permission to access the <a
        href="https://docs.aws.amazon.com/service-authorization/latest/reference/list_awsiot.html#awsiot-actions-as-permissions">GetSuiteRunReport</a>
        action.</p>
      tags:
        - Definitions
        - Reports
        - Runs
        - Suites
  /suiteRuns:
    GET:
      summary: 'List Suite Runs '
      description: >-
        <p>Lists runs of the specified Device Advisor test suite. You can list
        all runs of the test suite, or the runs of a specific version of the
        test suite.</p> <p>Requires permission to access the <a
        href="https://docs.aws.amazon.com/service-authorization/latest/reference/list_awsiot.html#awsiot-actions-as-permissions">ListSuiteRuns</a>
        action.</p>
      tags:
        - Runs
        - Suites
  /tags/{resourceArn}:
    DELETE:
      summary: 'Untag Resource '
      description: >-
        <p>Removes tags from an IoT Device Advisor resource.</p> <p>Requires
        permission to access the <a
        href="https://docs.aws.amazon.com/service-authorization/latest/reference/list_awsiot.html#awsiot-actions-as-permissions">UntagResource</a>
        action.</p>
      tags:
        - ARN
        - Resources
        - Tags
        - Untag
  /suiteDefinitions/{suiteDefinitionId}/suiteRuns:
    POST:
      summary: 'Start Suite Run '
      description: >-
        <p>Starts a Device Advisor test suite run.</p> <p>Requires permission to
        access the <a
        href="https://docs.aws.amazon.com/service-authorization/latest/reference/list_awsiot.html#awsiot-actions-as-permissions">StartSuiteRun</a>
        action.</p>
      tags:
        - Definitions
        - Runs
        - Suites
  /suiteDefinitions/{suiteDefinitionId}/suiteRuns/{suiteRunId}/stop:
    POST:
      summary: 'Stop Suite Run '
      description: >-
        <p>Stops a Device Advisor test suite run that is currently running.</p>
        <p>Requires permission to access the <a
        href="https://docs.aws.amazon.com/service-authorization/latest/reference/list_awsiot.html#awsiot-actions-as-permissions">StopSuiteRun</a>
        a
      tags:
        - Definitions
        - Runs
        - Stop
        - Suites
