openapi: 3.1.0
info:
  title: iotevents
paths:
  /alarm-models:
    GET:
      summary: 'List Alarm Models '
      description: >-
        <p>Lists the alarm models that you created. The operation returns only
        the metadata associated with each alarm model.</p>
      tags:
        - Alarm
        - Models
  /detector-models:
    GET:
      summary: 'List Detector Models '
      description: >-
        <p>Lists the detector models you have created. Only the metadata
        associated with each detector model is returned.</p>
      tags:
        - Detectors
        - Models
  /inputs:
    GET:
      summary: 'List Inputs '
      description: <p>Lists the inputs you have created.</p>
      tags:
        - Inputs
  /alarm-models/{alarmModelName}:
    POST:
      summary: 'Update Alarm Model '
      description: >-
        <p>Updates an alarm model. Any alarms that were created based on the
        previous version are deleted and then created again as new data
        arrives.</p>
      tags:
        - Alarm
        - Models
        - Names
  /detector-models/{detectorModelName}:
    POST:
      summary: 'Update Detector Model '
      description: >-
        <p>Updates a detector model. Detectors (instances) spawned by the
        previous version are deleted and then re-created as new inputs
        arrive.</p>
      tags:
        - Detectors
        - Models
        - Names
  /inputs/{inputName}:
    PUT:
      summary: 'Update Input '
      description: <p>Updates an input.</p>
      tags:
        - Inputs
        - Names
  /analysis/detector-models/{analysisId}:
    GET:
      summary: 'Describe Detector Model Analysis '
      description: >-
        <p>Retrieves runtime information about a detector model analysis.</p>
        <note> <p>After AWS IoT Events starts analyzing your detector model, you
        have up to 24 hours to retrieve the analysis results.</p> </note>
      tags:
        - Analysis
        - Describe
        - Detectors
        - Models
  /logging:
    PUT:
      summary: 'Put Logging Options '
      description: >-
        <p>Sets or updates the AWS IoT Events logging options.</p> <p>If you
        update the value of any <code>loggingOptions</code> field, it takes up
        to one minute for the change to take effect. If you change the policy
        attached to the role you specified in the <code>roleArn</code> field
        (for example, to correct an invalid policy), it takes up to five minutes
        for that change to take effect.</p>
      tags:
        - Logging
        - Options
  /analysis/detector-models/{analysisId}/results:
    GET:
      summary: 'Get Detector Model Analysis Results '
      description: >-
        <p>Retrieves one or more analysis results of the detector model.</p>
        <note> <p>After AWS IoT Events starts analyzing your detector model, you
        have up to 24 hours to retrieve the analysis results.</p> </note>
      tags:
        - Analysis
        - Detectors
        - Models
        - Results
  /alarm-models/{alarmModelName}/versions:
    GET:
      summary: 'List Alarm Model Versions '
      description: >-
        <p>Lists all the versions of an alarm model. The operation returns only
        the metadata associated with each alarm model version.</p>
      tags:
        - Alarm
        - Models
        - Names
        - Versions
  /detector-models/{detectorModelName}/versions:
    GET:
      summary: 'List Detector Model Versions '
      description: >-
        <p>Lists all the versions of a detector model. Only the metadata
        associated with each detector model version is returned.</p>
      tags:
        - Detectors
        - Models
        - Names
        - Versions
  /input-routings:
    POST:
      summary: 'List Input Routings '
      description: <p> Lists one or more input routings. </p>
      tags:
        - Inputs
        - Routings
  /tags:
    DELETE:
      summary: 'Untag Resource '
      description: <p>Removes the given tags (metadata) from the resource.</p>
      tags:
        - Resources
        - Tags
        - Untag
  /analysis/detector-models/:
    POST:
      summary: 'Start Detector Model Analysis '
      description: >-
        <p>Performs an analysis of your detector model. For more information,
        see <a
        href="https://docs.aws.amazon.com/iotevents/latest/developerguide/iotevents-analyze-api.html">Troubleshooting
        a detector model</a> in the <i>AWS IoT Events Developer Guid
      tags:
        - Analysis
        - Detectors
        - Models
