openapi: 3.1.0
info:
  title: iotfleethub
paths:
  /applications:
    GET:
      summary: 'List Applications '
      description: >-
        <p>Gets a list of Fleet Hub for AWS IoT Device Management web
        applications for the current account.</p> <note> <p>Fleet Hub for AWS
        IoT Device Management is in public preview and is subject to change.</p>
        </note>
      tags:
        - Applications
  /applications/{applicationId}:
    PATCH:
      summary: 'Update Application '
      description: >-
        <p>Updates information about a Fleet Hub for a AWS IoT Device Management
        web application.</p> <note> <p>Fleet Hub for AWS IoT Device Management
        is in public preview and is subject to change.</p> </note>
      tags:
        - Applications
  /tags/{resourceArn}:
    DELETE:
      summary: 'Untag Resource '
      description: >-
        <p>Removes the specified tags (metadata) from the resource.</p> <note>
        <p>Fleet Hub for AWS IoT Device Management is in public preview and is
        subject to change.</
      tags:
        - ARN
        - Resources
        - Tags
        - Untag
