openapi: 3.1.0
info:
  title: ivs
paths:
  /BatchGetChannel:
    POST:
      summary: 'Batch Get Channel '
      description: <p>Performs <a>GetChannel</a> on multiple ARNs simultaneously.</p>
      tags:
        - Batches
        - Channels
  /BatchGetStreamKey:
    POST:
      summary: 'Batch Get Stream Key '
      description: <p>Performs <a>GetStreamKey</a> on multiple ARNs simultaneously.</p>
      tags:
        - Batches
        - Keys
        - Stream
  /BatchStartViewerSessionRevocation:
    POST:
      summary: 'Batch Start Viewer Session Revocation '
      description: >-
        <p>Performs <a>StartViewerSessionRevocation</a> on multiple channel ARN
        and viewer ID pairs simultaneously.</p>
      tags:
        - Batches
        - Revocations
        - Sessions
        - Viewers
  /CreateChannel:
    POST:
      summary: 'Create Channel '
      description: >-
        <p>Creates a new channel and an associated stream key to start
        streaming.</p>
      tags:
        - Channels
  /CreatePlaybackRestrictionPolicy:
    POST:
      summary: 'Create Playback Restriction Policy '
      description: >-
        <p>Creates a new playback restriction policy, for constraining playback
        by countries and/or origins.</p>
      tags:
        - Playback
        - Policies
        - Restrictions
  /CreateRecordingConfiguration:
    POST:
      summary: 'Create Recording Configuration '
      description: >-
        <p>Creates a new recording configuration, used to enable recording to
        Amazon S3.</p> <p> <b>Known issue:</b> In the us-east-1 region, if you
        use the Amazon Web Services CLI to create a recording configuration, it
        returns success even if the S3 bucket is in a different region. In this
        case, the <code>state</code> of the recording configuration is
        <code>CREATE_FAILED</code> (instead of <code>ACTIVE</code>). (In other
        regions, the CLI correctly returns failure if the bucket is in a
        different region.)</p> <p> <b>Workaround:</b> Ensure that your S3 bucket
        is in the same region as the recording configuration. If you create a
        recording configuration in a different region as your S3 bucket, delete
        that recording configuration and create a new one with an S3 bucket from
        the correct region.</p>
      tags:
        - Configurations
        - Recording
  /CreateStreamKey:
    POST:
      summary: 'Create Stream Key '
      description: >-
        <p>Creates a stream key, used to initiate a stream, for the specified
        channel ARN.</p> <p>Note that <a>CreateChannel</a> creates a stream key.
        If you subsequently use CreateStreamKey on the same channel, it will
        fail because a stream key already exists and there is a limit of 1
        stream key per channel. To reset the stream key on a channel, use
        <a>DeleteStreamKey</a> and then CreateStreamKey.</p>
      tags:
        - Keys
        - Stream
  /DeleteChannel:
    POST:
      summary: 'Delete Channel '
      description: >-
        <p>Deletes the specified channel and its associated stream keys.</p>
        <p>If you try to delete a live channel, you will get an error (409
        ConflictException). To delete a channel that is live, call
        <a>StopStream</a>, wait for the Amazon EventBridge "Stream End" event
        (to verify that the stream's state is no longer Live), then call
        DeleteChannel. (See <a
        href="https://docs.aws.amazon.com/ivs/latest/userguide/eventbridge.html">
        Using EventBridge with Amazon IVS</a>.) </p>
      tags:
        - Channels
  /DeletePlaybackKeyPair:
    POST:
      summary: 'Delete Playback Key Pair '
      description: >-
        <p>Deletes a specified authorization key pair. This invalidates future
        viewer tokens generated using the key pair’s <code>privateKey</code>.
        For more information, see <a
        href="https://docs.aws.amazon.com/ivs/latest/userguide/private-channels.html">Setting
        Up Private Channels</a> in the <i>Amazon IVS User Guide</i>.</p>
      tags:
        - Keys
        - Pairs
        - Playback
  /DeletePlaybackRestrictionPolicy:
    POST:
      summary: 'Delete Playback Restriction Policy '
      description: <p>Deletes the specified playback restriction policy.</p>
      tags:
        - Playback
        - Policies
        - Restrictions
  /DeleteRecordingConfiguration:
    POST:
      summary: 'Delete Recording Configuration '
      description: >-
        <p>Deletes the recording configuration for the specified ARN.</p> <p>If
        you try to delete a recording configuration that is associated with a
        channel, you will get an error (409 ConflictException). To avoid this,
        for all channels that reference the recording configuration, first use
        <a>UpdateChannel</a> to set the <code>recordingConfigurationArn</code>
        field to an empty string, then use DeleteRecordingConfiguration.</p>
      tags:
        - Configurations
        - Recording
  /DeleteStreamKey:
    POST:
      summary: 'Delete Stream Key '
      description: >-
        <p>Deletes the stream key for the specified ARN, so it can no longer be
        used to stream.</p>
      tags:
        - Keys
        - Stream
  /GetChannel:
    POST:
      summary: 'Get Channel '
      description: >-
        <p>Gets the channel configuration for the specified channel ARN. See
        also <a>BatchGetChannel</a>.</p>
      tags:
        - Channels
  /GetPlaybackKeyPair:
    POST:
      summary: 'Get Playback Key Pair '
      description: >-
        <p>Gets a specified playback authorization key pair and returns the
        <code>arn</code> and <code>fingerprint</code>. The
        <code>privateKey</code> held by the caller can be used to generate
        viewer authorization tokens, to grant viewers access to private
        channels. For more information, see <a
        href="https://docs.aws.amazon.com/ivs/latest/userguide/private-channels.html">Setting
        Up Private Channels</a> in the <i>Amazon IVS User Guide</i>.</p>
      tags:
        - Keys
        - Pairs
        - Playback
  /GetPlaybackRestrictionPolicy:
    POST:
      summary: 'Get Playback Restriction Policy '
      description: <p>Gets the specified playback restriction policy.</p>
      tags:
        - Playback
        - Policies
        - Restrictions
  /GetRecordingConfiguration:
    POST:
      summary: 'Get Recording Configuration '
      description: <p>Gets the recording configuration for the specified ARN.</p>
      tags:
        - Configurations
        - Recording
  /GetStream:
    POST:
      summary: 'Get Stream '
      description: >-
        <p>Gets information about the active (live) stream on a specified
        channel.</p>
      tags:
        - Stream
  /GetStreamKey:
    POST:
      summary: 'Get Stream Key '
      description: <p>Gets stream-key information for a specified ARN.</p>
      tags:
        - Keys
        - Stream
  /GetStreamSession:
    POST:
      summary: 'Get Stream Session '
      description: <p>Gets metadata on a specified stream.</p>
      tags:
        - Sessions
        - Stream
  /ImportPlaybackKeyPair:
    POST:
      summary: 'Import Playback Key Pair '
      description: >-
        <p>Imports the public portion of a new key pair and returns its
        <code>arn</code> and <code>fingerprint</code>. The
        <code>privateKey</code> can then be used to generate viewer
        authorization tokens, to grant viewers access to private channels. For
        more information, see <a
        href="https://docs.aws.amazon.com/ivs/latest/userguide/private-channels.html">Setting
        Up Private Channels</a> in the <i>Amazon IVS User Guide</i>.</p>
      tags:
        - Import
        - Keys
        - Pairs
        - Playback
  /ListChannels:
    POST:
      summary: 'List Channels '
      description: >-
        <p>Gets summary information about all channels in your account, in the
        Amazon Web Services region where the API request is processed. This list
        can be filtered to match a specified name or recording-configuration
        ARN. Filters are mutually exclusive and cannot be used together. If you
        try to use both filters, you will get an error (409
        ConflictException).</p>
      tags:
        - Channels
  /ListPlaybackKeyPairs:
    POST:
      summary: 'List Playback Key Pairs '
      description: >-
        <p>Gets summary information about playback key pairs. For more
        information, see <a
        href="https://docs.aws.amazon.com/ivs/latest/userguide/private-channels.html">Setting
        Up Private Channels</a> in the <i>Amazon IVS User Guide</i>.</p>
      tags:
        - Keys
        - Pairs
        - Playback
  /ListPlaybackRestrictionPolicies:
    POST:
      summary: 'List Playback Restriction Policies '
      description: <p>Gets summary information about playback restriction policies.</p>
      tags:
        - Playback
        - Policies
        - Restrictions
  /ListRecordingConfigurations:
    POST:
      summary: 'List Recording Configurations '
      description: >-
        <p>Gets summary information about all recording configurations in your
        account, in the Amazon Web Services region where the API request is
        processed.</p>
      tags:
        - Configurations
        - Recording
  /ListStreamKeys:
    POST:
      summary: 'List Stream Keys '
      description: >-
        <p>Gets summary information about stream keys for the specified
        channel.</p>
      tags:
        - Keys
        - Stream
  /ListStreamSessions:
    POST:
      summary: 'List Stream Sessions '
      description: >-
        <p>Gets a summary of current and previous streams for a specified
        channel in your account, in the AWS region where the API request is
        processed.</p>
      tags:
        - Sessions
        - Stream
  /ListStreams:
    POST:
      summary: 'List Streams '
      description: >-
        <p>Gets summary information about live streams in your account, in the
        Amazon Web Services region where the API request is processed.</p>
      tags:
        - Streams
  /tags/{resourceArn}:
    DELETE:
      summary: 'Untag Resource '
      description: <p>Removes tags from the resource with the specified ARN.</p>
      tags:
        - ARN
        - Resources
        - Tags
        - Untag
  /PutMetadata:
    POST:
      summary: 'Put Metadata '
      description: >-
        <p>Inserts metadata into the active stream of the specified channel. At
        most 5 requests per second per channel are allowed, each with a maximum
        1 KB payload. (If 5 TPS is not sufficient for your needs, we recommend
        batching your data into a single PutMetadata call.) At most 155 requests
        per second per account are allowed. Also see <a
        href="https://docs.aws.amazon.com/ivs/latest/userguide/metadata.html">Embedding
        Metadata within a Video Stream</a> in the <i>Amazon IVS User
        Guide</i>.</p>
      tags:
        - Metadata
  /StartViewerSessionRevocation:
    POST:
      summary: 'Start Viewer Session Revocation '
      description: >-
        <p>Starts the process of revoking the viewer session associated with a
        specified channel ARN and viewer ID. Optionally, you can provide a
        version to revoke viewer sessions less than and including that version.
        For instructions on associating a viewer ID with a viewer session, see
        <a
        href="https://docs.aws.amazon.com/ivs/latest/userguide/private-channels.html">Setting
        Up Private Channels</a>.</p>
      tags:
        - Revocations
        - Sessions
        - Viewers
  /StopStream:
    POST:
      summary: 'Stop Stream '
      description: >-
        <p>Disconnects the incoming RTMPS stream for the specified channel. Can
        be used in conjunction with <a>DeleteStreamKey</a> to prevent further
        streaming to a channel.</p> <note> <p>Many streaming client-software
        libraries automatically reconnect a dropped RTMPS session, so to stop
        the stream permanently, you may want to first revoke the
        <code>streamKey</code> attached to the channel.</p> </note>
      tags:
        - Stop
        - Stream
  /UpdateChannel:
    POST:
      summary: 'Update Channel '
      description: >-
        <p>Updates a channel's configuration. Live channels cannot be updated.
        You must stop the ongoing stream, update the channel, and restart the
        stream for the changes to take effect.</p>
      tags:
        - Channels
  /UpdatePlaybackRestrictionPolicy:
    POST:
      summary: 'Update Playback Restriction Policy '
      description: <p>Updates a specified playback restriction p
      tags:
        - Playback
        - Policies
        - Restrictions
