openapi: 3.1.0
info:
  title: ivschat
paths:
  /CreateChatToken:
    POST:
      summary: 'Create Chat Token '
      description: >-
        <p>Creates an encrypted token that is used by a chat participant to
        establish an individual WebSocket chat connection to a room. When the
        token is used to connect to chat, the connection is valid for the
        session duration specified in the request. The token becomes invalid at
        the token-expiration timestamp included in the response.</p> <p>Use the
        <code>capabilities</code> field to permit an end user to send messages
        or moderate a room.</p> <p>The <code>attributes</code> field securely
        attaches structured data to the chat session; the data is included
        within each message sent by the end user and received by other
        participants in the room. Common use cases for attributes include
        passing end-user profile data like an icon, display name, colors,
        badges, and other display features.</p> <p>Encryption keys are owned by
        Amazon IVS Chat and never used directly by your application.</p>
      tags:
        - Chat
        - Tokens
  /CreateLoggingConfiguration:
    POST:
      summary: 'Create Logging Configuration '
      description: >-
        <p>Creates a logging configuration that allows clients to store and
        record sent messages.</p>
      tags:
        - Configurations
        - Logging
  /CreateRoom:
    POST:
      summary: 'Create Room '
      description: <p>Creates a room that allows clients to connect and pass messages.</p>
      tags:
        - Rooms
  /DeleteLoggingConfiguration:
    POST:
      summary: 'Delete Logging Configuration '
      description: <p>Deletes the specified logging configuration.</p>
      tags:
        - Configurations
        - Logging
  /DeleteMessage:
    POST:
      summary: 'Delete Message '
      description: >-
        <p>Sends an event to a specific room which directs clients to delete a
        specific message; that is, unrender it from view and delete it from the
        client’s chat history. This event’s <code>EventName</code> is
        <code>aws:DELETE_MESSAGE</code>. This replicates the <a
        href="https://docs.aws.amazon.com/ivs/latest/chatmsgapireference/actions-deletemessage-publish.html">
        DeleteMessage</a> WebSocket operation in the Amazon IVS Chat Messaging
        API.</p>
      tags:
        - Messages
  /DeleteRoom:
    POST:
      summary: 'Delete Room '
      description: <p>Deletes the specified room.</p>
      tags:
        - Rooms
  /DisconnectUser:
    POST:
      summary: 'Disconnect User '
      description: >-
        <p>Disconnects all connections using a specified user ID from a room.
        This replicates the <a
        href="https://docs.aws.amazon.com/ivs/latest/chatmsgapireference/actions-disconnectuser-publish.html">
        DisconnectUser</a> WebSocket operation in the Amazon IVS Chat Messaging
        API.</p>
      tags:
        - Disconnect
        - Users
  /GetLoggingConfiguration:
    POST:
      summary: 'Get Logging Configuration '
      description: <p>Gets the specified logging configuration.</p>
      tags:
        - Configurations
        - Logging
  /GetRoom:
    POST:
      summary: 'Get Room '
      description: <p>Gets the specified room.</p>
      tags:
        - Rooms
  /ListLoggingConfigurations:
    POST:
      summary: 'List Logging Configurations '
      description: >-
        <p>Gets summary information about all your logging configurations in the
        AWS region where the API request is processed.</p>
      tags:
        - Configurations
        - Logging
  /ListRooms:
    POST:
      summary: 'List Rooms '
      description: >-
        <p>Gets summary information about all your rooms in the AWS region where
        the API request is processed. Results are sorted in descending order of
        <code>updateTime</code>.</p>
      tags:
        - Rooms
  /tags/{resourceArn}:
    DELETE:
      summary: 'Untag Resource '
      description: <p>Removes tags from the resource with the specified ARN.</p>
      tags:
        - ARN
        - Resources
        - Tags
        - Untag
  /SendEvent:
    POST:
      summary: 'Send Event '
      description: >-
        <p>Sends an event to a room. Use this within your application’s business
        logic to send events to clients of a room; e.g., to notify clients to
        change the way the chat UI is rendered.</p>
      tags:
        - Events
        - Send
  /UpdateLoggingConfiguration:
    POST:
      summary: 'Update Logging Configuration '
      description: <p>Updates a specified logging configuration.</p>
      tags:
        - Configurations
        - Logging
  /UpdateRoom:
    POST:
      summary: 'Update Room '
      description: <p>Updates a room’s configur
      tags:
        - Rooms
