openapi: 3.1.0
info:
  title: kafka
paths:
  /v1/clusters/{clusterArn}/scram-secrets:
    GET:
      summary: 'List Scram Secrets '
      description: >-
        <p>Returns a list of the Scram Secrets associated with an Amazon MSK
        cluster.</p>
      tags:
        - ARN
        - Clusters
        - Secrets
  /v1/clusters:
    GET:
      summary: 'List Clusters '
      description: <p>Returns a list of all the MSK clusters in the current Region.</p>
      tags:
        - Clusters
  /api/v2/clusters:
    GET:
      summary: 'List Clusters V2 '
      description: <p>Returns a list of all the MSK clusters in the current Region.</p>
      tags:
        - Clusters
  /replication/v1/replicators:
    GET:
      summary: 'List Replicators '
      description: <p>Lists the replicators.</p>
      tags:
        - Replication
        - Replicators
  /v1/configurations:
    GET:
      summary: 'List Configurations '
      description: <p>Returns a list of all the MSK configurations in this Region.</p>
      tags:
        - Configurations
  /v1/vpc-connection:
    POST:
      summary: 'Create Vpc Connection '
      description: <p>Creates a new Amazon MSK VPC connection.</p>
      tags:
        - Connections
        - VPC
  /v1/clusters/{clusterArn}:
    GET:
      summary: 'Describe Cluster '
      description: >-
        <p>Returns a description of the MSK cluster whose Amazon Resource Name
        (ARN) is specified in the request.</p>
      tags:
        - ARN
        - Clusters
        - Describe
  /v1/clusters/{clusterArn}/policy:
    PUT:
      summary: 'Put Cluster Policy '
      description: >-
        <p>Creates or updates the specified MSK cluster policy. If updating the
        policy, the currentVersion field is required in the request payload.</p>
      tags:
        - ARN
        - Clusters
        - Policies
  /v1/configurations/{arn}:
    PUT:
      summary: 'Update Configuration '
      description: >-
        <p>Updates an existing MSK configuration. The configuration must be in
        the Active state.</p>
      tags:
        - ARN
        - Configurations
  /replication/v1/replicators/{replicatorArn}:
    GET:
      summary: 'Describe Replicator '
      description: >-
        <p>Returns a description of the Kafka Replicator whose Amazon Resource
        Name (ARN) is specified in the request.</p>
      tags:
        - ARN
        - Describe
        - Replication
        - Replicators
  /v1/vpc-connection/{arn}:
    GET:
      summary: 'Describe Vpc Connection '
      description: >-
        <p>Displays information about the specified Amazon MSK VPC
        connection.</p>
      tags:
        - ARN
        - Connections
        - Describe
        - VPC
  /api/v2/clusters/{clusterArn}:
    GET:
      summary: 'Describe Cluster V2 '
      description: >-
        <p>Returns a description of the MSK cluster of either the provisioned or
        the serverless type whose Amazon Resource Name (ARN) is specified in the
        request.</p>
      tags:
        - ARN
        - Clusters
        - Describe
  /v1/operations/{clusterOperationArn}:
    GET:
      summary: 'Describe Cluster Operation '
      description: >-
        <p>Returns a description of the cluster operation specified by the
        ARN.</p>
      tags:
        - ARN
        - Clusters
        - Describe
        - Operation
        - Operations
  /api/v2/operations/{clusterOperationArn}:
    GET:
      summary: 'Describe Cluster Operation V2 '
      description: >-
        <p>Returns a description of the cluster operation specified by the
        ARN.</p>
      tags:
        - ARN
        - Clusters
        - Describe
        - Operation
        - Operations
  /v1/configurations/{arn}/revisions/{revision}:
    GET:
      summary: 'Describe Configuration Revision '
      description: <p>Returns a description of this revision of the configuration.</p>
      tags:
        - ARN
        - Configurations
        - Describe
        - Revisions
  /v1/clusters/{clusterArn}/bootstrap-brokers:
    GET:
      summary: 'Get Bootstrap Brokers '
      description: <p>A list of brokers that a client application can use to bootstrap.</p>
      tags:
        - ARN
        - Bootstrap
        - Brokers
        - Clusters
  /v1/compatible-kafka-versions:
    GET:
      summary: 'Get Compatible Kafka Versions '
      description: >-
        <p>Gets the Apache Kafka versions to which you can update the MSK
        cluster.</p>
      tags:
        - Compatible
        - Kafka
        - Versions
  /v1/clusters/{clusterArn}/client-vpc-connections:
    GET:
      summary: 'List Client Vpc Connections '
      description: <p>Displays a list of client VPC connections.</p>
      tags:
        - ARN
        - Clients
        - Clusters
        - Connections
        - VPC
  /v1/clusters/{clusterArn}/operations:
    GET:
      summary: 'List Cluster Operations '
      description: >-
        <p>Returns a list of all the operations that have been performed on the
        specified MSK cluster.</p>
      tags:
        - ARN
        - Clusters
        - Operations
  /api/v2/clusters/{clusterArn}/operations:
    GET:
      summary: 'List Cluster Operations V2 '
      description: >-
        <p>Returns a list of all the operations that have been performed on the
        specified MSK cluster.</p>
      tags:
        - ARN
        - Clusters
        - Operations
  /v1/configurations/{arn}/revisions:
    GET:
      summary: 'List Configuration Revisions '
      description: <p>Returns a list of all the revisions of an MSK configuration.</p>
      tags:
        - ARN
        - Configurations
        - Revisions
  /v1/kafka-versions:
    GET:
      summary: 'List Kafka Versions '
      description: <p>Returns a list of Apache Kafka versions.</p>
      tags:
        - Kafka
        - Versions
  /v1/clusters/{clusterArn}/nodes:
    GET:
      summary: 'List Nodes '
      description: <p>Returns a list of the broker nodes in the cluster.</p>
      tags:
        - ARN
        - Clusters
        - Nodes
  /v1/tags/{resourceArn}:
    DELETE:
      summary: 'Untag Resource '
      description: >-
        <p>Removes the tags associated with the keys that are provided in the
        query.</p>
      tags:
        - ARN
        - Resources
        - Tags
        - Untag
  /v1/vpc-connections:
    GET:
      summary: 'List Vpc Connections '
      description: <p>Displays a list of Amazon MSK VPC connections.</p>
      tags:
        - Connections
        - VPC
  /v1/clusters/{clusterArn}/reboot-broker:
    PUT:
      summary: 'Reboot Broker '
      description: <p>Executes a reboot on a broker.</p>
      tags:
        - ARN
        - Brokers
        - Clusters
        - Reboot
  /v1/clusters/{clusterArn}/nodes/count:
    PUT:
      summary: 'Update Broker Count '
      description: >-
        <p>Updates the number of broker nodes in the cluster. You can use this
        operation to increase the number of brokers in an existing cluster. You
        can't decrease the number of brokers.</p>
      tags:
        - ARN
        - Brokers
        - Clusters
        - Count
        - Nodes
  /v1/clusters/{clusterArn}/nodes/type:
    PUT:
      summary: 'Update Broker Type '
      description: <p>Updates all the brokers in the cluster to the specified type.</p>
      tags:
        - ARN
        - Brokers
        - Clusters
        - Nodes
        - Types
  /v1/clusters/{clusterArn}/nodes/storage:
    PUT:
      summary: 'Update Broker Storage '
      description: <p>Updates the EBS storage associated with MSK brokers.</p>
      tags:
        - ARN
        - Brokers
        - Clusters
        - Nodes
        - Storage
  /v1/clusters/{clusterArn}/connectivity:
    PUT:
      summary: 'Update Connectivity '
      description: <p>Updates the connectivity configuration for the MSK cluster.</p>
      tags:
        - ARN
        - Clusters
        - Connectivity
  /v1/clusters/{clusterArn}/configuration:
    PUT:
      summary: 'Update Cluster Configuration '
      description: >-
        <p>Updates the cluster with the configuration that is specified in the
        request body.</p>
      tags:
        - ARN
        - Clusters
        - Configurations
  /v1/clusters/{clusterArn}/version:
    PUT:
      summary: 'Update Cluster Kafka Version '
      description: <p>Updates the Apache Kafka version for the cluster.</p>
      tags:
        - ARN
        - Clusters
        - Kafka
        - Versions
  /v1/clusters/{clusterArn}/monitoring:
    PUT:
      summary: 'Update Monitoring '
      description: >-
        <p>Updates the monitoring settings for the cluster. You can use this
        operation to specify which Apache Kafka metrics you want Amazon MSK to
        send to Amazon CloudWatch. You can also specify settings for open
        monitoring with Prometheus.</p>
      tags:
        - ARN
        - Clusters
        - Monitoring
  /replication/v1/replicators/{replicatorArn}/replication-info:
    PUT:
      summary: 'Update Replication Info '
      description: <p>Updates replication info of a replicator.</p>
      tags:
        - ARN
        - Info
        - Replication
        - Replicators
  /v1/clusters/{clusterArn}/security:
    PATCH:
      summary: 'Update Security '
      description: >-
        <p>You can use this operation to update the encrypting and
        authentication settings for an existing cluster.</p>
      tags:
        - ARN
        - Clusters
        - Security
  /v1/clusters/{clusterArn}/storage:
    PUT:
      summary: 'Update Storage '
      description: >-
        <p>Updates cluster broker volume size (or) sets cluster storage mode to
        T
      tags:
        - ARN
        - Clusters
        - Storage
