openapi: 3.1.0
info:
  title: launch-wizard
paths:
  /createDeployment:
    POST:
      summary: 'Create Deployment '
      description: >-
        <p>Creates a deployment for the given workload. Deployments created by
        this operation are not available in the Launch Wizard console to use the
        <code>Clone deployment</code> action on.</p>
      tags:
        - Deployments
  /deleteDeployment:
    POST:
      summary: 'Delete Deployment '
      description: <p>Deletes a deployment.</p>
      tags:
        - Deployments
  /getDeployment:
    POST:
      summary: 'Get Deployment '
      description: <p>Returns information about the deployment.</p>
      tags:
        - Deployments
  /getWorkload:
    POST:
      summary: 'Get Workload '
      description: <p>Returns information about a workload.</p>
      tags:
        - Workloads
  /listDeploymentEvents:
    POST:
      summary: 'List Deployment Events '
      description: <p>Lists the events of a deployment.</p>
      tags:
        - Deployments
        - Events
  /listDeployments:
    POST:
      summary: 'List Deployments '
      description: <p>Lists the deployments that have been created.</p>
      tags:
        - Deployments
  /listWorkloadDeploymentPatterns:
    POST:
      summary: 'List Workload Deployment Patterns '
      description: <p>Lists the workload deployment patterns.</p>
      tags:
        - Deployments
        - Patterns
        - Workloads
  /listWorkloads:
    POST:
      summary: 'List Workloads '
      description: <p>Lists the work
      tags:
        - Workloads
