openapi: 3.1.0
info:
  title: license-manager
paths:
  /:
    POST:
      summary: 'Update Service Settings '
      description: <p>Updates License Manager settings for the current R
      tags:
        - Services
        - Settings
