openapi: 3.1.0
info:
  title: logs
paths:
  /:
    POST:
      summary: 'Update Log Anomaly Detector '
      description: <p>Updates an existing log anomaly det
      tags:
        - Anomaly
        - Detectors
        - Logs
