openapi: 3.1.0
info:
  title: lookoutmetrics
paths:
  /ActivateAnomalyDetector:
    POST:
      summary: 'Activate Anomaly Detector '
      description: <p>Activates an anomaly detector.</p>
      tags:
        - Activate
        - Anomaly
        - Detectors
  /BackTestAnomalyDetector:
    POST:
      summary: 'Back Test Anomaly Detector '
      description: <p>Runs a backtest for anomaly detection for the specified resource.</p>
      tags:
        - Anomaly
        - Detectors
        - Tests
  /CreateAlert:
    POST:
      summary: 'Create Alert '
      description: <p>Creates an alert for an anomaly detector.</p>
      tags:
        - Alerts
  /CreateAnomalyDetector:
    POST:
      summary: 'Create Anomaly Detector '
      description: <p>Creates an anomaly detector.</p>
      tags:
        - Anomaly
        - Detectors
  /CreateMetricSet:
    POST:
      summary: 'Create Metric Set '
      description: <p>Creates a dataset.</p>
      tags:
        - Metrics
        - Sets
  /DeactivateAnomalyDetector:
    POST:
      summary: 'Deactivate Anomaly Detector '
      description: <p>Deactivates an anomaly detector.</p>
      tags:
        - Anomaly
        - Deactivate
        - Detectors
  /DeleteAlert:
    POST:
      summary: 'Delete Alert '
      description: <p>Deletes an alert.</p>
      tags:
        - Alerts
  /DeleteAnomalyDetector:
    POST:
      summary: 'Delete Anomaly Detector '
      description: >-
        <p>Deletes a detector. Deleting an anomaly detector will delete all of
        its corresponding resources including any configured datasets and
        alerts.</p>
      tags:
        - Anomaly
        - Detectors
  /DescribeAlert:
    POST:
      summary: 'Describe Alert '
      description: >-
        <p>Describes an alert.</p> <p>Amazon Lookout for Metrics API actions are
        eventually consistent. If you do a read operation on a resource
        immediately after creating or modifying it, use retries to allow time
        for the write operation to complete.</p>
      tags:
        - Alerts
        - Describe
  /DescribeAnomalyDetectionExecutions:
    POST:
      summary: 'Describe Anomaly Detection Executions '
      description: >-
        <p>Returns information about the status of the specified anomaly
        detection jobs.</p>
      tags:
        - Anomaly
        - Describe
        - Detections
        - Executions
  /DescribeAnomalyDetector:
    POST:
      summary: 'Describe Anomaly Detector '
      description: >-
        <p>Describes a detector.</p> <p>Amazon Lookout for Metrics API actions
        are eventually consistent. If you do a read operation on a resource
        immediately after creating or modifying it, use retries to allow time
        for the write operation to complete.</p>
      tags:
        - Anomaly
        - Describe
        - Detectors
  /DescribeMetricSet:
    POST:
      summary: 'Describe Metric Set '
      description: >-
        <p>Describes a dataset.</p> <p>Amazon Lookout for Metrics API actions
        are eventually consistent. If you do a read operation on a resource
        immediately after creating or modifying it, use retries to allow time
        for the write operation to complete.</p>
      tags:
        - Describe
        - Metrics
        - Sets
  /DetectMetricSetConfig:
    POST:
      summary: 'Detect Metric Set Config '
      description: <p>Detects an Amazon S3 dataset's file format, interval, and offset.</p>
      tags:
        - Configurations
        - Detect
        - Metrics
        - Sets
  /GetAnomalyGroup:
    POST:
      summary: 'Get Anomaly Group '
      description: <p>Returns details about a group of anomalous metrics.</p>
      tags:
        - Anomaly
        - Groups
  /GetDataQualityMetrics:
    POST:
      summary: 'Get Data Quality Metrics '
      description: <p>Returns details about the requested data quality metrics.</p>
      tags:
        - Data
        - Metrics
        - Quality
  /GetFeedback:
    POST:
      summary: 'Get Feedback '
      description: <p>Get feedback for an anomaly group.</p>
      tags:
        - Feedback
  /GetSampleData:
    POST:
      summary: 'Get Sample Data '
      description: >-
        <p>Returns a selection of sample records from an Amazon S3
        datasource.</p>
      tags:
        - Data
        - Samples
  /ListAlerts:
    POST:
      summary: 'List Alerts '
      description: >-
        <p>Lists the alerts attached to a detector.</p> <p>Amazon Lookout for
        Metrics API actions are eventually consistent. If you do a read
        operation on a resource immediately after creating or modifying it, use
        retries to allow time for the write operation to complete.</p>
      tags:
        - Alerts
  /ListAnomalyDetectors:
    POST:
      summary: 'List Anomaly Detectors '
      description: >-
        <p>Lists the detectors in the current AWS Region.</p> <p>Amazon Lookout
        for Metrics API actions are eventually consistent. If you do a read
        operation on a resource immediately after creating or modifying it, use
        retries to allow time for the write operation to complete.</p>
      tags:
        - Anomaly
        - Detectors
  /ListAnomalyGroupRelatedMetrics:
    POST:
      summary: 'List Anomaly Group Related Metrics '
      description: >-
        <p>Returns a list of measures that are potential causes or effects of an
        anomaly group.</p>
      tags:
        - Anomaly
        - Groups
        - Metrics
        - Related
  /ListAnomalyGroupSummaries:
    POST:
      summary: 'List Anomaly Group Summaries '
      description: <p>Returns a list of anomaly groups.</p>
      tags:
        - Anomaly
        - Groups
        - Summaries
  /ListAnomalyGroupTimeSeries:
    POST:
      summary: 'List Anomaly Group Time Series '
      description: >-
        <p>Gets a list of anomalous metrics for a measure in an anomaly
        group.</p>
      tags:
        - Anomaly
        - Groups
        - Series
        - Time
  /ListMetricSets:
    POST:
      summary: 'List Metric Sets '
      description: >-
        <p>Lists the datasets in the current AWS Region.</p> <p>Amazon Lookout
        for Metrics API actions are eventually consistent. If you do a read
        operation on a resource immediately after creating or modifying it, use
        retries to allow time for the write operation to complete.</p>
      tags:
        - Metrics
        - Sets
  /tags/{resourceArn}:
    DELETE:
      summary: 'Untag Resource '
      description: >-
        <p>Removes <a
        href="https://docs.aws.amazon.com/lookoutmetrics/latest/dev/detectors-tags.html">tags</a>
        from a detector, dataset, or alert.</p>
      tags:
        - ARN
        - Resources
        - Tags
        - Untag
  /PutFeedback:
    POST:
      summary: 'Put Feedback '
      description: <p>Add feedback for an anomalous metric.</p>
      tags:
        - Feedback
  /UpdateAlert:
    POST:
      summary: 'Update Alert '
      description: <p>Make changes to an existing alert.</p>
      tags:
        - Alerts
  /UpdateAnomalyDetector:
    POST:
      summary: 'Update Anomaly Detector '
      description: >-
        <p>Updates a detector. After activation, you can only change a
        detector's ingestion delay and description.</p>
      tags:
        - Anomaly
        - Detectors
  /UpdateMetricSet:
    POST:
      summary: 'Update Metric Set '
      description: <p>Updates a da
      tags:
        - Metrics
        - Sets
