openapi: 3.1.0
info:
  title: lookoutequipment
paths:
  /:
    POST:
      summary: 'Update Retraining Scheduler '
      description: <p>Updates a retraining sche
      tags:
        - Retraining
        - Scheduler
