openapi: 3.1.0
info:
  title: m2
paths:
  /applications/{applicationId}/batch-job-executions/{executionId}/cancel:
    POST:
      summary: 'Cancel Batch Job Execution '
      description: <p>Cancels the running of a specific batch job execution.</p>
      tags:
        - Applications
        - Batches
        - Cancel
        - Execution
        - Executions
        - Jobs
  /applications:
    GET:
      summary: 'List Applications '
      description: >-
        <p>Lists the applications associated with a specific Amazon Web Services
        account. You can provide the unique identifier of a specific runtime
        environment in a query parameter to see all applications associated with
        that environment.</p>
      tags:
        - Applications
  /applications/{applicationId}/dataset-import-task:
    POST:
      summary: 'Create Data Set Import Task '
      description: <p>Starts a data set import task for a specific application.</p>
      tags:
        - Applications
        - Data
        - Datasets
        - Import
        - Sets
        - Tasks
  /applications/{applicationId}/deployments:
    GET:
      summary: 'List Deployments '
      description: >-
        <p>Returns a list of all deployments of a specific application. A
        deployment is a combination of a specific application and a specific
        version of that application. Each deployment is mapped to a particular
        application version.</p>
      tags:
        - Applications
        - Deployments
  /environments:
    GET:
      summary: 'List Environments '
      description: <p>Lists the runtime environments.</p>
      tags:
        - Environments
  /applications/{applicationId}:
    PATCH:
      summary: 'Update Application '
      description: <p>Updates an application and creates a new version.</p>
      tags:
        - Applications
  /applications/{applicationId}/environment/{environmentId}:
    DELETE:
      summary: 'Delete Application From Environment '
      description: >-
        <p>Deletes a specific application from the specific runtime environment
        where it was previously deployed. You cannot delete a runtime
        environment using DeleteEnvironment if any application has ever been
        deployed to it. This API removes the association of the application with
        the runtime environment so you can delete the environment smoothly.</p>
      tags:
        - Applications
        - Environments
  /environments/{environmentId}:
    PATCH:
      summary: 'Update Environment '
      description: >-
        <p>Updates the configuration details for a specific runtime
        environment.</p>
      tags:
        - Environments
  /applications/{applicationId}/versions/{applicationVersion}:
    GET:
      summary: 'Get Application Version '
      description: >-
        <p>Returns details about a specific version of a specific
        application.</p>
      tags:
        - Applications
        - Versions
  /applications/{applicationId}/batch-job-executions/{executionId}:
    GET:
      summary: 'Get Batch Job Execution '
      description: >-
        <p>Gets the details of a specific batch job execution for a specific
        application.</p>
      tags:
        - Applications
        - Batches
        - Execution
        - Executions
        - Jobs
  /applications/{applicationId}/datasets/{dataSetName}:
    GET:
      summary: 'Get Data Set Details '
      description: <p>Gets the details of a specific data set.</p>
      tags:
        - Applications
        - Data
        - Datasets
        - Details
        - Names
        - Sets
  /applications/{applicationId}/dataset-import-tasks/{taskId}:
    GET:
      summary: 'Get Data Set Import Task '
      description: >-
        <p>Gets the status of a data set import task initiated with the
        <a>CreateDataSetImportTask</a> operation.</p>
      tags:
        - Applications
        - Data
        - Datasets
        - Import
        - Sets
        - Tasks
  /applications/{applicationId}/deployments/{deploymentId}:
    GET:
      summary: 'Get Deployment '
      description: >-
        <p>Gets details of a specific deployment with a given deployment
        identifier.</p>
      tags:
        - Applications
        - Deployments
  /signed-bi-url:
    GET:
      summary: 'Get Signed Bluinsights Url '
      description: >-
        <p>Gets a single sign-on URL that can be used to connect to AWS Blu
        Insights.</p>
      tags:
        - Signed
        - URL
  /applications/{applicationId}/versions:
    GET:
      summary: 'List Application Versions '
      description: >-
        <p>Returns a list of the application versions for a specific
        application.</p>
      tags:
        - Applications
        - Versions
  /applications/{applicationId}/batch-job-definitions:
    GET:
      summary: 'List Batch Job Definitions '
      description: >-
        <p>Lists all the available batch job definitions based on the batch job
        resources uploaded during the application creation. You can use the
        batch job definitions in the list to start a batch job.</p>
      tags:
        - Applications
        - Batches
        - Definitions
        - Jobs
  /applications/{applicationId}/batch-job-executions:
    GET:
      summary: 'List Batch Job Executions '
      description: >-
        <p>Lists historical, current, and scheduled batch job executions for a
        specific application.</p>
      tags:
        - Applications
        - Batches
        - Executions
        - Jobs
  /applications/{applicationId}/dataset-import-tasks:
    GET:
      summary: 'List Data Set Import History '
      description: <p>Lists the data set imports for the specified application.</p>
      tags:
        - Applications
        - Data
        - Datasets
        - History
        - Import
        - Sets
        - Tasks
  /applications/{applicationId}/datasets:
    GET:
      summary: 'List Data Sets '
      description: >-
        <p>Lists the data sets imported for a specific application. In Amazon
        Web Services Mainframe Modernization, data sets are associated with
        applications deployed on runtime environments. This is known as
        importing data sets. Currently, Amazon Web Services Mainframe
        Modernization can import data sets into catalogs using <a
        href="https://docs.aws.amazon.com/m2/latest/APIReference/API_CreateDataSetImportTask.html">CreateDataSetImportTask</a>.</p>
      tags:
        - Applications
        - Data
        - Datasets
        - Sets
  /engine-versions:
    GET:
      summary: 'List Engine Versions '
      description: <p>Lists the available engine versions.</p>
      tags:
        - Engines
        - Versions
  /tags/{resourceArn}:
    DELETE:
      summary: 'Untag Resource '
      description: <p>Removes one or more tags from the specified resource.</p>
      tags:
        - ARN
        - Resources
        - Tags
        - Untag
  /applications/{applicationId}/start:
    POST:
      summary: 'Start Application '
      description: <p>Starts an application that is currently stopped.</p>
      tags:
        - Applications
  /applications/{applicationId}/batch-job:
    POST:
      summary: 'Start Batch Job '
      description: >-
        <p>Starts a batch job and returns the unique identifier of this
        execution of the batch job. The associated application must be running
        in order to start the batch job.</p>
      tags:
        - Applications
        - Batches
        - Jobs
  /applications/{applicationId}/stop:
    POST:
      summary: 'Stop Application '
      description: <p>Stops a running applic
      tags:
        - Applications
        - Stop
