openapi: 3.1.0
info:
  title: macie2
paths:
  /invitations/accept:
    POST:
      summary: 'Accept Invitation '
      description: >-
        <p>Accepts an Amazon Macie membership invitation that was received from
        a specific account.</p>
      tags:
        - Accept
        - Invitation
        - Invitations
  /custom-data-identifiers/get:
    POST:
      summary: 'Batch Get Custom Data Identifiers '
      description: <p>Retrieves information about one or more custom data identifiers.</p>
      tags:
        - Batches
        - Custom
        - Data
        - Entifiers
  /allow-lists:
    GET:
      summary: 'List Allow Lists '
      description: >-
        <p>Retrieves a subset of information about all the allow lists for an
        account.</p>
      tags:
        - Allow
  /jobs:
    POST:
      summary: 'Create Classification Job '
      description: <p>Creates and defines the settings for a classification job.</p>
      tags:
        - Classifications
        - Jobs
  /custom-data-identifiers:
    POST:
      summary: 'Create Custom Data Identifier '
      description: >-
        <p>Creates and defines the criteria and other settings for a custom data
        identifier.</p>
      tags:
        - Custom
        - Data
        - Entifiers
  /findingsfilters:
    GET:
      summary: 'List Findings Filters '
      description: >-
        <p>Retrieves a subset of information about all the findings filters for
        an account.</p>
      tags:
        - Filters
        - Findings
        - Findings Filter
  /invitations:
    GET:
      summary: 'List Invitations '
      description: >-
        <p>Retrieves information about the Amazon Macie membership invitations
        that were received by an account.</p>
      tags:
        - Invitations
  /members:
    GET:
      summary: 'List Members '
      description: >-
        <p>Retrieves information about the accounts that are associated with an
        Amazon Macie administrator account.</p>
      tags:
        - Members
  /findings/sample:
    POST:
      summary: 'Create Sample Findings '
      description: <p>Creates sample findings.</p>
      tags:
        - Findings
        - Samples
  /invitations/decline:
    POST:
      summary: 'Decline Invitations '
      description: >-
        <p>Declines Amazon Macie membership invitations that were received from
        specific accounts.</p>
      tags:
        - Decline
        - Invitations
  /allow-lists/{id}:
    PUT:
      summary: 'Update Allow List '
      description: <p>Updates the settings for an allow list.</p>
      tags:
        - Allow
  /custom-data-identifiers/{id}:
    GET:
      summary: 'Get Custom Data Identifier '
      description: >-
        <p>Retrieves the criteria and other settings for a custom data
        identifier.</p>
      tags:
        - Custom
        - Data
        - Entifiers
  /findingsfilters/{id}:
    PATCH:
      summary: 'Update Findings Filter '
      description: <p>Updates the criteria and other settings for a findings filter.</p>
      tags:
        - Filter
        - Findings
        - Findings Filter
  /invitations/delete:
    POST:
      summary: 'Delete Invitations '
      description: >-
        <p>Deletes Amazon Macie membership invitations that were received from
        specific accounts.</p>
      tags:
        - Invitations
  /members/{id}:
    GET:
      summary: 'Get Member '
      description: >-
        <p>Retrieves information about an account that's associated with an
        Amazon Macie administrator account.</p>
      tags:
        - Members
  /datasources/s3:
    POST:
      summary: 'Describe Buckets '
      description: >-
        <p>Retrieves (queries) statistical data and other information about one
        or more S3 buckets that Amazon Macie monitors and analyzes for an
        account.</p>
      tags:
        - Buckets
        - Data Source
        - Describe
  /jobs/{jobId}:
    PATCH:
      summary: 'Update Classification Job '
      description: <p>Changes the status of a classification job.</p>
      tags:
        - Classifications
        - Jobs
  /admin/configuration:
    PATCH:
      summary: 'Update Organization Configuration '
      description: >-
        <p>Updates the Amazon Macie configuration settings for an organization
        in Organizations.</p>
      tags:
        - Administrative
        - Configurations
        - Organizations
  /macie:
    PATCH:
      summary: 'Update Macie Session '
      description: >-
        <p>Suspends or re-enables Amazon Macie, or updates the configuration
        settings for a Macie account.</p>
      tags:
        - Sessions
  /admin:
    GET:
      summary: 'List Organization Admin Accounts '
      description: >-
        <p>Retrieves information about the delegated Amazon Macie administrator
        account for an organization in Organizations.</p>
      tags:
        - Accounts
        - Administrative
        - Organizations
  /administrator/disassociate:
    POST:
      summary: 'Disassociate From Administrator Account '
      description: >-
        <p>Disassociates a member account from its Amazon Macie administrator
        account.</p>
      tags:
        - Accounts
        - Administrator
        - Disassociate
  /master/disassociate:
    POST:
      summary: 'Disassociate From Master Account '
      description: >-
        <p>(Deprecated) Disassociates a member account from its Amazon Macie
        administrator account. This operation has been replaced by the <link 
        linkend="DisassociateFromAdministratorAccount">DisassociateFromAdministratorAccount</link>
        operation.</p>
      tags:
        - Accounts
        - Disassociate
        - Master
  /members/disassociate/{id}:
    POST:
      summary: 'Disassociate Member '
      description: >-
        <p>Disassociates an Amazon Macie administrator account from a member
        account.</p>
      tags:
        - Disassociate
        - Members
  /administrator:
    GET:
      summary: 'Get Administrator Account '
      description: >-
        <p>Retrieves information about the Amazon Macie administrator account
        for an account.</p>
      tags:
        - Accounts
        - Administrator
  /automated-discovery/configuration:
    PUT:
      summary: 'Update Automated Discovery Configuration '
      description: >-
        <p>Enables or disables automated sensitive data discovery for an
        account.</p>
      tags:
        - Automated
        - Configurations
        - Discovery
  /datasources/s3/statistics:
    POST:
      summary: 'Get Bucket Statistics '
      description: >-
        <p>Retrieves (queries) aggregated statistical data about all the S3
        buckets that Amazon Macie monitors and analyzes for an account.</p>
      tags:
        - Bucket
        - Data Source
        - Statistics
  /classification-export-configuration:
    PUT:
      summary: 'Put Classification Export Configuration '
      description: >-
        <p>Creates or updates the configuration settings for storing data
        classification results.</p>
      tags:
        - Classifications
        - Configurations
        - Exports
  /classification-scopes/{id}:
    PATCH:
      summary: 'Update Classification Scope '
      description: <p>Updates the classification scope settings for an account.</p>
      tags:
        - Classifications
        - Scopes
  /findings/statistics:
    POST:
      summary: 'Get Finding Statistics '
      description: <p>Retrieves (queries) aggregated statistical data about findings.</p>
      tags:
        - Findings
        - Statistics
  /findings/describe:
    POST:
      summary: 'Get Findings '
      description: <p>Retrieves the details of one or more findings.</p>
      tags:
        - Describe
        - Findings
  /findings-publication-configuration:
    PUT:
      summary: 'Put Findings Publication Configuration '
      description: >-
        <p>Updates the configuration settings for publishing findings to
        Security Hub.</p>
      tags:
        - Configurations
        - Findings
        - Publication
  /invitations/count:
    GET:
      summary: 'Get Invitations Count '
      description: >-
        <p>Retrieves the count of Amazon Macie membership invitations that were
        received by an account.</p>
      tags:
        - Count
        - Invitations
  /master:
    GET:
      summary: 'Get Master Account '
      description: >-
        <p>(Deprecated) Retrieves information about the Amazon Macie
        administrator account for an account. This operation has been replaced
        by the <link 
        linkend="GetAdministratorAccount">GetAdministratorAccount</link>
        operation.</p>
      tags:
        - Accounts
        - Master
  /resource-profiles:
    PATCH:
      summary: 'Update Resource Profile '
      description: <p>Updates the sensitivity score for an S3 bucket.</p>
      tags:
        - Profiles
        - Resources
  /reveal-configuration:
    PUT:
      summary: 'Update Reveal Configuration '
      description: >-
        <p>Updates the status and configuration settings for retrieving
        occurrences of sensitive data reported by findings.</p>
      tags:
        - Configurations
        - Reveal
  /findings/{findingId}/reveal:
    GET:
      summary: 'Get Sensitive Data Occurrences '
      description: <p>Retrieves occurrences of sensitive data reported by a finding.</p>
      tags:
        - Data
        - Findings
        - Occurrences
        - Reveal
        - Sensitive
  /findings/{findingId}/reveal/availability:
    GET:
      summary: 'Get Sensitive Data Occurrences Availability '
      description: >-
        <p>Checks whether occurrences of sensitive data can be retrieved for a
        finding.</p>
      tags:
        - Availability
        - Data
        - Findings
        - Occurrences
        - Reveal
        - Sensitive
  /templates/sensitivity-inspections/{id}:
    PUT:
      summary: 'Update Sensitivity Inspection Template '
      description: ' <p>Updates the settings for the sensitivity inspection template for an account.</p>'
      tags:
        - Inspections
        - Sensitivity
        - Templates
  /usage/statistics:
    POST:
      summary: 'Get Usage Statistics '
      description: >-
        <p>Retrieves (queries) quotas and aggregated usage data for one or more
        accounts.</p>
      tags:
        - Statistics
        - Usage
  /usage:
    GET:
      summary: 'Get Usage Totals '
      description: <p>Retrieves (queries) aggregated usage data for an account.</p>
      tags:
        - Totals
        - Usage
  /jobs/list:
    POST:
      summary: 'List Classification Jobs '
      description: >-
        <p>Retrieves a subset of information about one or more classification
        jobs.</p>
      tags:
        - Classifications
        - Jobs
  /classification-scopes:
    GET:
      summary: 'List Classification Scopes '
      description: >-
        <p>Retrieves a subset of information about the classification scope for
        an account.</p>
      tags:
        - Classifications
        - Scopes
  /custom-data-identifiers/list:
    POST:
      summary: 'List Custom Data Identifiers '
      description: >-
        <p>Retrieves a subset of information about all the custom data
        identifiers for an account.</p>
      tags:
        - Custom
        - Data
        - Entifiers
  /findings:
    POST:
      summary: 'List Findings '
      description: <p>Retrieves a subset of information about one or more findings.</p>
      tags:
        - Findings
  /managed-data-identifiers/list:
    POST:
      summary: 'List Managed Data Identifiers '
      description: >-
        <p>Retrieves information about all the managed data identifiers that
        Amazon Macie currently provides.</p>
      tags:
        - Data
        - Entifiers
        - Managed
  /resource-profiles/artifacts:
    GET:
      summary: 'List Resource Profile Artifacts '
      description: >-
        <p>Retrieves information about objects that were selected from an S3
        bucket for automated sensitive data discovery.</p>
      tags:
        - Artifacts
        - Profiles
        - Resources
  /resource-profiles/detections:
    PATCH:
      summary: 'Update Resource Profile Detections '
      description: <p>Updates the sensitivity scoring settings for an S3 bucket.</p>
      tags:
        - Detections
        - Profiles
        - Resources
  /templates/sensitivity-inspections:
    GET:
      summary: 'List Sensitivity Inspection Templates '
      description: ' <p>Retrieves a subset of information about the sensitivity inspection template for an account.</p>'
      tags:
        - Inspections
        - Sensitivity
        - Templates
  /tags/{resourceArn}:
    DELETE:
      summary: 'Untag Resource '
      description: >-
        <p>Removes one or more tags (keys and values) from an Amazon Macie
        resource.</p>
      tags:
        - ARN
        - Resources
        - Tags
        - Untag
  /datasources/search-resources:
    POST:
      summary: 'Search Resources '
      description: >-
        <p>Retrieves (queries) statistical data and other information about
        Amazon Web Services resources that Amazon Macie monitors and
        analyzes.</p>
      tags:
        - Data Source
        - Resources
        - Search
  /custom-data-identifiers/test:
    POST:
      summary: 'Test Custom Data Identifier '
      description: <p>Tests a custom data identifier.</p>
      tags:
        - Custom
        - Data
        - Entifiers
        - Tests
  /macie/members/{id}:
    PATCH:
      summary: 'Update Member Session '
      description: >-
        <p>Enables an Amazon Macie administrator to suspend or re-enable Macie
        for a member ac
      tags:
        - Members
        - Sessions
