openapi: 3.1.0
info:
  title: managedblockchain-query
paths:
  /batch-get-token-balance:
    POST:
      summary: 'Batch Get Token Balance '
      description: >-
        <p>Gets the token balance for a batch of tokens by using the
        <code>BatchGetTokenBalance</code> action for every token in the
        request.</p> <note> <p>Only the native tokens BTC and ETH, and the
        ERC-20, ERC-721, and ERC 1155 token standards are supported.</p> </note>
      tags:
        - Balance
        - Batches
        - Tokens
  /get-asset-contract:
    POST:
      summary: 'Get Asset Contract '
      description: >-
        <p>Gets the information about a specific contract deployed on the
        blockchain.</p> <note> <ul> <li> <p>The Bitcoin blockchain networks do
        not support this operation.</p> </li> <li> <p>Metadata is currently only
        available for some <code>ERC-20</code> contracts. Metadata will be
        available for additional contracts in the future.</p> </li> </ul>
        </note>
      tags:
        - Assets
        - Contracts
  /get-token-balance:
    POST:
      summary: 'Get Token Balance '
      description: >-
        <p>Gets the balance of a specific token, including native tokens, for a
        given address (wallet or contract) on the blockchain.</p> <note> <p>Only
        the native tokens BTC and ETH, and the ERC-20, ERC-721, and ERC 1155
        token standards are supported.</p> </note>
      tags:
        - Balance
        - Tokens
  /get-transaction:
    POST:
      summary: 'Get Transaction '
      description: >-
        <p>Gets the details of a transaction.</p> <note> <p>This action will
        return transaction details for all transactions that are
        <i>confirmed</i> on the blockchain, even if they have not reached <a
        href="https://docs.aws.amazon.com/managed-blockchain/latest/ambq-dg/key-concepts.html#finality">finality</a>.
        </p> </note>
      tags:
        - Transactions
  /list-asset-contracts:
    POST:
      summary: 'List Asset Contracts '
      description: >-
        <p>Lists all the contracts for a given contract type deployed by an
        address (either a contract address or a wallet address).</p> <p>The
        Bitcoin blockchain networks do not support this operation.</p>
      tags:
        - Assets
        - Contracts
  /list-token-balances:
    POST:
      summary: 'List Token Balances '
      description: >-
        <p>This action returns the following for a given blockchain network:</p>
        <ul> <li> <p>Lists all token balances owned by an address (either a
        contract address or a wallet address).</p> </li> <li> <p>Lists all token
        balances for all tokens created by a contract.</p> </li> <li> <p>Lists
        all token balances for a given token.</p> </li> </ul> <note> <p>You must
        always specify the network property of the <code>tokenFilter</code> when
        using this operation.</p> </note>
      tags:
        - Balances
        - Tokens
  /list-transaction-events:
    POST:
      summary: 'List Transaction Events '
      description: >-
        <p>An array of <code>TransactionEvent</code> objects. Each object
        contains details about the transaction event.</p> <note> <p>This action
        will return transaction details for all transactions that are
        <i>confirmed</i> on the blockchain, even if they have not reached <a
        href="https://docs.aws.amazon.com/managed-blockchain/latest/ambq-dg/key-concepts.html#finality">finality</a>.
        </p> </note>
      tags:
        - Events
        - Transactions
  /list-transactions:
    POST:
      summary: 'List Transactions '
      description: >-
        <p>Lists all of the transactions on a given wallet address or to a
        specific con
      tags:
        - Transactions
