openapi: 3.1.0
info:
  title: marketplace-catalog
paths:
  /BatchDescribeEntities:
    POST:
      summary: 'Batch Describe Entities '
      description: >-
        <p>Returns metadata and content for multiple entities. This is the Batch
        version of the <code>DescribeEntity</code> API and uses the same IAM
        permission action as <code>DescribeEntity</code> API.</p>
      tags:
        - Batches
        - Describe
        - Entities
  /CancelChangeSet:
    PATCH:
      summary: 'Cancel Change Set '
      description: >-
        <p>Used to cancel an open change request. Must be sent before the status
        of the request changes to <code>APPLYING</code>, the final stage of
        completing your change request. You can describe a change during the
        60-day request history retention period for API calls.</p>
      tags:
        - Cancel
        - Change
        - Sets
  /DeleteResourcePolicy:
    DELETE:
      summary: 'Delete Resource Policy '
      description: >-
        <p>Deletes a resource-based policy on an entity that is identified by
        its resource ARN.</p>
      tags:
        - Policies
        - Resources
  /DescribeChangeSet:
    GET:
      summary: 'Describe Change Set '
      description: <p>Provides information about a given change set.</p>
      tags:
        - Change
        - Describe
        - Sets
  /DescribeEntity:
    GET:
      summary: 'Describe Entity '
      description: <p>Returns the metadata and content of the entity.</p>
      tags:
        - Describe
        - Entities
  /GetResourcePolicy:
    GET:
      summary: 'Get Resource Policy '
      description: >-
        <p>Gets a resource-based policy of an entity that is identified by its
        resource ARN.</p>
      tags:
        - Policies
        - Resources
  /ListChangeSets:
    POST:
      summary: 'List Change Sets '
      description: >-
        <p>Returns the list of change sets owned by the account being used to
        make the call. You can filter this list by providing any combination of
        <code>entityId</code>, <code>ChangeSetName</code>, and status. If you
        provide more than one filter, the API operation applies a logical AND
        between the filters.</p> <p>You can describe a change during the 60-day
        request history retention period for API calls.</p>
      tags:
        - Change
        - Sets
  /ListEntities:
    POST:
      summary: 'List Entities '
      description: <p>Provides the list of entities of a given type.</p>
      tags:
        - Entities
  /ListTagsForResource:
    POST:
      summary: 'List Tags For Resource '
      description: >-
        <p>Lists all tags that have been added to a resource (either an <a
        href="https://docs.aws.amazon.com/marketplace-catalog/latest/api-reference/welcome.html#catalog-api-entities">entity</a>
        or <a
        href="https://docs.aws.amazon.com/marketplace-catalog/latest/api-reference/welcome.html#working-with-change-sets">change
        set</a>).</p>
      tags:
        - Resources
        - Tags
  /PutResourcePolicy:
    POST:
      summary: 'Put Resource Policy '
      description: >-
        <p>Attaches a resource-based policy to an entity. Examples of an entity
        include: <code>AmiProduct</code> and <code>ContainerProduct</code>.</p>
      tags:
        - Policies
        - Resources
  /StartChangeSet:
    POST:
      summary: 'Start Change Set '
      description: >-
        <p>Allows you to request changes for your entities. Within a single
        <code>ChangeSet</code>, you can't start the same change type against the
        same entity multiple times. Additionally, when a <code>ChangeSet</code>
        is running, all the entities targeted by the different changes are
        locked until the change set has completed (either succeeded, cancelled,
        or failed). If you try to start a change set containing a change against
        an entity that is already locked, you will receive a
        <code>ResourceInUseException</code> error.</p> <p>For example, you can't
        start the <code>ChangeSet</code> described in the <a
        href="https://docs.aws.amazon.com/marketplace-catalog/latest/api-reference/API_StartChangeSet.html#API_StartChangeSet_Examples">example</a>
        later in this topic because it contains two changes to run the same
        change type (<code>AddRevisions</code>) against the same entity
        (<code>entity-id@1</code>).</p> <p>For more information about working
        with change sets, see <a
        href="https://docs.aws.amazon.com/marketplace-catalog/latest/api-reference/welcome.html#working-with-change-sets">
        Working with change sets</a>. For information about change types for
        single-AMI products, see <a
        href="https://docs.aws.amazon.com/marketplace-catalog/latest/api-reference/ami-products.html#working-with-single-AMI-products">Working
        with single-AMI products</a>. Also, for more information about change
        types available for container-based products, see <a
        href="https://docs.aws.amazon.com/marketplace-catalog/latest/api-reference/container-products.html#working-with-container-products">Working
        with container products</a>.</p>
      tags:
        - Change
        - Sets
  /TagResource:
    POST:
      summary: 'Tag Resource '
      description: >-
        <p>Tags a resource (either an <a
        href="https://docs.aws.amazon.com/marketplace-catalog/latest/api-reference/welcome.html#catalog-api-entities">entity</a>
        or <a
        href="https://docs.aws.amazon.com/marketplace-catalog/latest/api-reference/welcome.html#working-with-change-sets">change
        set</a>).</p>
      tags:
        - Resources
        - Tags
  /UntagResource:
    POST:
      summary: 'Untag Resource '
      description: >-
        <p>Removes a tag or list of tags from a resource (either an <a
        href="https://docs.aws.amazon.com/marketplace-catalog/latest/api-reference/welcome.html#catalog-api-entities">entity</a>
        or <a
        href="https://docs.aws.amazon.com/marketplace-catalog/latest/api-reference/welcome.html#working-with-change-sets">change
        set
      tags:
        - Resources
        - Untag
