openapi: 3.1.0
info:
  title: medical-imaging
paths:
  /datastore/{datastoreId}/imageSet/{sourceImageSetId}/copyImageSet:
    POST:
      summary: 'Copy Image Set '
      description: <p>Copy an image set.</p>
      tags:
        - Copy
        - Data Store
        - Images
        - Sets
        - Sources
  /datastore:
    GET:
      summary: 'List Datastores '
      description: <p>List data stores.</p>
      tags:
        - Data Store
  /datastore/{datastoreId}:
    GET:
      summary: 'Get Datastore '
      description: <p>Get data store properties.</p>
      tags:
        - Data Store
  /datastore/{datastoreId}/imageSet/{imageSetId}/deleteImageSet:
    POST:
      summary: 'Delete Image Set '
      description: <p>Delete an image set.</p>
      tags:
        - Data Store
        - Images
        - Sets
  /getDICOMImportJob/datastore/{datastoreId}/job/{jobId}:
    GET:
      summary: 'Get DICOMImport Job '
      description: >-
        <p>Get the import job properties to learn more about the job or job
        progress.</p>
      tags:
        - DICOMImport
        - Data Store
        - Dicomimport
        - Jobs
  /datastore/{datastoreId}/imageSet/{imageSetId}/getImageFrame:
    POST:
      summary: 'Get Image Frame '
      description: <p>Get an image frame (pixel data) for an image set.</p>
      tags:
        - Data Store
        - Frames
        - Images
        - Sets
  /datastore/{datastoreId}/imageSet/{imageSetId}/getImageSet:
    POST:
      summary: 'Get Image Set '
      description: <p>Get image set properties.</p>
      tags:
        - Data Store
        - Images
        - Sets
  /datastore/{datastoreId}/imageSet/{imageSetId}/getImageSetMetadata:
    POST:
      summary: 'Get Image Set Metadata '
      description: <p>Get metadata attributes for an image set.</p>
      tags:
        - Data Store
        - Images
        - Metadata
        - Sets
  /listDICOMImportJobs/datastore/{datastoreId}:
    GET:
      summary: 'List DICOMImport Jobs '
      description: <p>List import jobs created for a specific data store.</p>
      tags:
        - DICOMImport
        - Data Store
        - Dicomimport
        - Jobs
  /datastore/{datastoreId}/imageSet/{imageSetId}/listImageSetVersions:
    POST:
      summary: 'List Image Set Versions '
      description: <p>List image set versions.</p>
      tags:
        - Data Store
        - Images
        - Sets
        - Versions
  /tags/{resourceArn}:
    DELETE:
      summary: 'Untag Resource '
      description: <p>Removes tags from a medical imaging resource.</p>
      tags:
        - ARN
        - Resources
        - Tags
        - Untag
  /datastore/{datastoreId}/searchImageSets:
    POST:
      summary: 'Search Image Sets '
      description: >-
        <p>Search image sets based on defined input attributes.</p> <note> <p>
        <code>SearchImageSets</code> accepts a single search query parameter and
        returns a paginated response of all image sets that have the matching
        criteria. All range queries must be input as <code>(lowerBound,
        upperBound)</code>.</p> <p> <code>SearchImageSets</code> uses the
        <code>updatedAt</code> field for sorting in decreasing order from latest
        to oldest.</p> </note>
      tags:
        - Data Store
        - Images
        - Search
        - Sets
  /startDICOMImportJob/datastore/{datastoreId}:
    POST:
      summary: 'Start DICOMImport Job '
      description: >-
        <p>Start importing bulk data into an <code>ACTIVE</code> data store. The
        import job imports DICOM P10 files found in the S3 prefix specified by
        the <code>inputS3Uri</code> parameter. The import job stores processing
        results in the file specified by the <code>outputS3Uri</code>
        parameter.</p>
      tags:
        - DICOMImport
        - Data Store
        - Dicomimport
        - Jobs
  /datastore/{datastoreId}/imageSet/{imageSetId}/updateImageSetMetadata:
    POST:
      summary: 'Update Image Set Metadata '
      description: <p>Update image set metadata attri
      tags:
        - Data Store
        - Images
        - Metadata
        - Sets
