openapi: 3.1.0
info:
  title: mediaconvert
paths:
  /2017-08-29/certificates:
    POST:
      summary: 'Associate Certificate '
      description: >-
        Associates an AWS Certificate Manager (ACM) Amazon Resource Name (ARN)
        with AWS Elemental MediaConvert.
      tags:
        - Associate
        - Certificates
  /2017-08-29/jobs/{id}:
    GET:
      summary: 'Get Job '
      description: Retrieve the JSON for a specific transcoding job.
      tags:
        - Jobs
  /2017-08-29/jobs:
    GET:
      summary: 'List Jobs '
      description: >-
        Retrieve a JSON array of up to twenty of your most recently created
        jobs. This array includes in-process, completed, and errored jobs. This
        will return the jobs themselves, not just a list of the jobs. To
        retrieve the twenty next most recent jobs, use the nextToken string
        returned with the array.
      tags:
        - Jobs
  /2017-08-29/jobTemplates:
    GET:
      summary: 'List Job Templates '
      description: >-
        Retrieve a JSON array of up to twenty of your job templates. This will
        return the templates themselves, not just a list of them. To retrieve
        the next twenty templates, use the nextToken string returned with the
        array
      tags:
        - Jobs
        - Templates
  /2017-08-29/presets:
    GET:
      summary: 'List Presets '
      description: >-
        Retrieve a JSON array of up to twenty of your presets. This will return
        the presets themselves, not just a list of them. To retrieve the next
        twenty presets, use the nextToken string returned with the array.
      tags:
        - Presets
  /2017-08-29/queues:
    GET:
      summary: 'List Queues '
      description: >-
        Retrieve a JSON array of up to twenty of your queues. This will return
        the queues themselves, not just a list of them. To retrieve the next
        twenty queues, use the nextToken string returned with the array.
      tags:
        - Queues
  /2017-08-29/jobTemplates/{name}:
    PUT:
      summary: 'Update Job Template '
      description: Modify one of your existing job templates.
      tags:
        - Jobs
        - Names
        - Templates
  /2017-08-29/policy:
    PUT:
      summary: 'Put Policy '
      description: >-
        Create or change your policy. For more information about policies, see
        the user guide at
        http://docs.aws.amazon.com/mediaconvert/latest/ug/what-is.html
      tags:
        - Policies
  /2017-08-29/presets/{name}:
    PUT:
      summary: 'Update Preset '
      description: Modify one of your existing presets.
      tags:
        - Names
        - Presets
  /2017-08-29/queues/{name}:
    PUT:
      summary: 'Update Queue '
      description: Modify one of your existing queues.
      tags:
        - Names
        - Queues
  /2017-08-29/endpoints:
    POST:
      summary: 'Describe Endpoints '
      description: >-
        Send an request with an empty body to the regional API endpoint to get
        your account API endpoint.
      tags:
        - Describe
        - Endpoints
  /2017-08-29/certificates/{arn}:
    DELETE:
      summary: 'Disassociate Certificate '
      description: >-
        Removes an association between the Amazon Resource Name (ARN) of an AWS
        Certificate Manager (ACM) certificate and an AWS Elemental MediaConvert
        resource.
      tags:
        - ARN
        - Certificates
        - Disassociate
  /2017-08-29/tags/{arn}:
    PUT:
      summary: 'Untag Resource '
      description: >-
        Remove tags from a MediaConvert queue, preset, or job template. For
        information about tagging, see the User Guide at
        https://docs.aws.amazon.com/mediaconvert/latest/ug/tagging-resources.html
      tags:
        - ARN
        - Resources
        - Tags
        - Untag
  /2017-08-29/tags:
    POST:
      summary: 'Tag Resource '
      description: >-
        Add tags to a MediaConvert queue, preset, or job template. For
        information about tagging, see the User Guide at
        https://docs.aws.amazon.com/mediaconvert/latest/ug/tagging-reso
      tags:
        - Resources
        - Tags
