openapi: 3.1.0
info:
  title: mediaconnect
paths:
  /v1/bridges/{bridgeArn}/outputs:
    POST:
      summary: 'Add Bridge Outputs '
      description: Adds outputs to an existing bridge.
      tags:
        - ARN
        - Br
        - Bridges
        - Ge
        - Ges
        - Outputs
  /v1/bridges/{bridgeArn}/sources:
    POST:
      summary: 'Add Bridge Sources '
      description: Adds sources to an existing bridge.
      tags:
        - ARN
        - Br
        - Bridges
        - Ge
        - Ges
        - Sources
  /v1/flows/{flowArn}/mediaStreams:
    POST:
      summary: 'Add Flow Media Streams '
      description: >-
        Adds media streams to an existing flow. After you add a media stream to
        a flow, you can associate it with a source and/or an output that uses
        the ST 2110 JPEG XS or CDI protocol.
      tags:
        - ARN
        - Flows
        - Media
        - Streams
  /v1/flows/{flowArn}/outputs:
    POST:
      summary: 'Add Flow Outputs '
      description: >-
        Adds outputs to an existing flow. You can create up to 50 outputs per
        flow.
      tags:
        - ARN
        - Flows
        - Outputs
  /v1/flows/{flowArn}/source:
    POST:
      summary: 'Add Flow Sources '
      description: Adds Sources to flow
      tags:
        - ARN
        - Flows
        - Sources
  /v1/flows/{flowArn}/vpcInterfaces:
    POST:
      summary: 'Add Flow Vpc Interfaces '
      description: Adds VPC interfaces to flow
      tags:
        - ARN
        - Flows
        - Interfaces
        - VPC
  /v1/bridges:
    GET:
      summary: 'List Bridges '
      description: >-
        Displays a list of bridges that are associated with this account and an
        optionally specified Arn. This request returns a paginated result.
      tags:
        - Br
        - Bridges
        - Ges
  /v1/flows:
    GET:
      summary: 'List Flows '
      description: >-
        Displays a list of flows that are associated with this account. This
        request returns a paginated result.
      tags:
        - Flows
  /v1/gateways:
    GET:
      summary: 'List Gateways '
      description: >-
        Displays a list of gateways that are associated with this account. This
        request returns a paginated result.
      tags:
        - Gateways
  /v1/bridges/{bridgeArn}:
    PUT:
      summary: 'Update Bridge '
      description: Updates the bridge
      tags:
        - ARN
        - Br
        - Bridges
        - Ge
        - Ges
  /v1/flows/{flowArn}:
    PUT:
      summary: 'Update Flow '
      description: Updates flow
      tags:
        - ARN
        - Flows
  /v1/gateways/{gatewayArn}:
    GET:
      summary: 'Describe Gateway '
      description: >-
        Displays the details of a gateway. The response includes the gateway
        ARN, name, and CIDR blocks, as well as details about the networks.
      tags:
        - ARN
        - Describe
        - Gateways
  /v1/gateway-instances/{gatewayInstanceArn}:
    PUT:
      summary: 'Update Gateway Instance '
      description: Updates the configuration of an existing Gateway Instance.
      tags:
        - ARN
        - Gateways
        - Instances
  /v1/flows/{flowArn}/source-metadata:
    GET:
      summary: 'Describe Flow Source Metadata '
      description: >-
        Displays details of the flow's source stream. The response contains
        information about the contents of the stream and its programs.
      tags:
        - ARN
        - Describe
        - Flows
        - Metadata
        - Sources
  /v1/offerings/{offeringArn}:
    POST:
      summary: 'Purchase Offering '
      description: >-
        Submits a request to purchase an offering. If you already have an active
        reservation, you can't purchase another offering.
      tags:
        - ARN
        - Offerings
        - Purchase
  /v1/reservations/{reservationArn}:
    GET:
      summary: 'Describe Reservation '
      description: >-
        Displays the details of a reservation. The response includes the
        reservation name, state, start date and time, and the details of the
        offering that make up the rest of the reservation (such as price,
        duration, and outbound bandwidth).
      tags:
        - ARN
        - Describe
        - Reservations
  /v1/flows/{flowArn}/entitlements:
    POST:
      summary: 'Grant Flow Entitlements '
      description: Grants entitlements to an existing flow.
      tags:
        - ARN
        - Entitlements
        - Flows
        - Grants""
  /v1/entitlements:
    GET:
      summary: 'List Entitlements '
      description: >-
        Displays a list of all entitlements that have been granted to this
        account. This request returns 20 results per page.
      tags:
        - Entitlements
  /v1/gateway-instances:
    GET:
      summary: 'List Gateway Instances '
      description: >-
        Displays a list of instances associated with the AWS account. This
        request returns a paginated result. You can use the filterArn property
        to display only the instances associated with the selected Gateway
        Amazon Resource Name (ARN).
      tags:
        - Gateways
        - Instances
  /v1/offerings:
    GET:
      summary: 'List Offerings '
      description: >-
        Displays a list of all offerings that are available to this account in
        the current AWS Region. If you have an active reservation (which means
        you've purchased an offering that has already started and hasn't expired
        yet), your account isn't eligible for other offerings.
      tags:
        - Offerings
  /v1/reservations:
    GET:
      summary: 'List Reservations '
      description: >-
        Displays a list of all reservations that have been purchased by this
        account in the current AWS Region. This list includes all reservations
        in all states (such as active and expired).
      tags:
        - Reservations
  /tags/{resourceArn}:
    DELETE:
      summary: 'Untag Resource '
      description: Deletes specified tags from a resource.
      tags:
        - ARN
        - Resources
        - Tags
        - Untag
  /v1/bridges/{bridgeArn}/outputs/{outputName}:
    PUT:
      summary: 'Update Bridge Output '
      description: Updates an existing bridge output.
      tags:
        - ARN
        - Br
        - Bridges
        - Ge
        - Ges
        - Names
        - Output
        - Outputs
  /v1/bridges/{bridgeArn}/sources/{sourceName}:
    PUT:
      summary: 'Update Bridge Source '
      description: Updates an existing bridge source.
      tags:
        - ARN
        - Br
        - Bridges
        - Ge
        - Ges
        - Names
        - Sources
  /v1/flows/{flowArn}/mediaStreams/{mediaStreamName}:
    PUT:
      summary: 'Update Flow Media Stream '
      description: Updates an existing media stream.
      tags:
        - ARN
        - Flows
        - Media
        - Names
        - Stream
        - Streams
  /v1/flows/{flowArn}/outputs/{outputArn}:
    PUT:
      summary: 'Update Flow Output '
      description: Updates an existing flow output.
      tags:
        - ARN
        - Flows
        - Output
        - Outputs
  /v1/flows/{flowArn}/source/{sourceArn}:
    PUT:
      summary: 'Update Flow Source '
      description: Updates the source of a flow.
      tags:
        - ARN
        - Flows
        - Sources
  /v1/flows/{flowArn}/vpcInterfaces/{vpcInterfaceName}:
    DELETE:
      summary: 'Remove Flow Vpc Interface '
      description: >-
        Removes a VPC Interface from an existing flow. This request can be made
        only on a VPC interface that does not have a Source or Output associated
        with it. If the VPC interface is referenced by a Source or Output, you
        must first delete or update the Source or Output to no longer reference
        the VPC interface.
      tags:
        - ARN
        - Flows
        - Interfaces
        - Names
        - Removes
        - VPC
  /v1/flows/{flowArn}/entitlements/{entitlementArn}:
    PUT:
      summary: 'Update Flow Entitlement '
      description: >-
        You can change an entitlement's description, subscribers, and
        encryption. If you change the subscribers, the service will remove the
        outputs that are are used by the subscribers that are removed.
      tags:
        - ARN
        - Entitlements
        - Flows
  /v1/flows/start/{flowArn}:
    POST:
      summary: 'Start Flow '
      description: Starts a flow.
      tags:
        - ARN
        - Flows
  /v1/flows/stop/{flowArn}:
    POST:
      summary: 'Stop Flow '
      description: Stops a flow.
      tags:
        - ARN
        - Flows
        - Stop
  /v1/bridges/{bridgeArn}/state:
    PUT:
      summary: 'Update Bridge State '
      description: Updates the br
      tags:
        - ARN
        - Br
        - Bridges
        - Ge
        - Ges
        - States
