openapi: 3.1.0
info:
  title: medialive
paths:
  /prod/inputDevices/{inputDeviceId}/accept:
    POST:
      summary: 'Accept Input Device Transfer '
      description: >-
        Accept an incoming input device transfer. The ownership of the device
        will transfer to your AWS account.
      tags:
        - Accept
        - Device
        - Devices
        - Inputs
        - Transfers
  /prod/batch/delete:
    POST:
      summary: 'Batch Delete '
      description: Starts delete of resources.
      tags:
        - Batches
  /prod/batch/start:
    POST:
      summary: 'Batch Start '
      description: Starts existing resources
      tags:
        - Batches
  /prod/batch/stop:
    POST:
      summary: 'Batch Stop '
      description: Stops running resources
      tags:
        - Batches
        - Stop
  /prod/channels/{channelId}/schedule:
    GET:
      summary: 'Describe Schedule '
      description: Get a channel schedule
      tags:
        - Channels
        - Describe
        - Schedules
  /prod/inputDevices/{inputDeviceId}/cancel:
    POST:
      summary: 'Cancel Input Device Transfer '
      description: Cancel an input device transfer that you have requested.
      tags:
        - Cancel
        - Device
        - Devices
        - Inputs
        - Transfers
  /prod/claimDevice:
    POST:
      summary: 'Claim Device '
      description: >-
        Send a request to claim an AWS Elemental device that you have purchased
        from a third-party vendor. After the request succeeds, you will own the
        device.
      tags:
        - Claim
        - Device
  /prod/channels:
    GET:
      summary: 'List Channels '
      description: Produces list of channels that have been created
      tags:
        - Channels
  /prod/inputs:
    GET:
      summary: 'List Inputs '
      description: Produces list of inputs that have been created
      tags:
        - Inputs
  /prod/inputSecurityGroups:
    GET:
      summary: 'List Input Security Groups '
      description: Produces a list of Input Security Groups for an account
      tags:
        - Groups
        - Inputs
        - Security
  /prod/multiplexes:
    GET:
      summary: 'List Multiplexes '
      description: Retrieve a list of the existing multiplexes.
      tags:
        - Multiplexes
  /prod/multiplexes/{multiplexId}/programs:
    GET:
      summary: 'List Multiplex Programs '
      description: List the programs that currently exist for a specific multiplex.
      tags:
        - Multiplex
        - Multiplexes
        - Programs
  /prod/inputs/{inputId}/partners:
    POST:
      summary: 'Create Partner Input '
      description: Create a partner input
      tags:
        - Inputs
        - Partners
  /prod/tags/{resource-arn}:
    GET:
      summary: 'List Tags For Resource '
      description: Produces list of tags that have been created for a resource
      tags:
        - ARN
        - Resources
        - Tags
  /prod/channels/{channelId}:
    PUT:
      summary: 'Update Channel '
      description: Updates a channel.
      tags:
        - Channels
  /prod/inputs/{inputId}:
    PUT:
      summary: 'Update Input '
      description: Updates an input.
      tags:
        - Inputs
  /prod/inputSecurityGroups/{inputSecurityGroupId}:
    PUT:
      summary: 'Update Input Security Group '
      description: Update an Input Security Group's Whilelists.
      tags:
        - Groups
        - Inputs
        - Security
  /prod/multiplexes/{multiplexId}:
    PUT:
      summary: 'Update Multiplex '
      description: Updates a multiplex.
      tags:
        - Multiplex
        - Multiplexes
  /prod/multiplexes/{multiplexId}/programs/{programName}:
    PUT:
      summary: 'Update Multiplex Program '
      description: Update a program in a multiplex.
      tags:
        - Multiplex
        - Multiplexes
        - Names
        - Program
        - Programs
  /prod/reservations/{reservationId}:
    PUT:
      summary: 'Update Reservation '
      description: Update reservation.
      tags:
        - Reservations
  /prod/accountConfiguration:
    PUT:
      summary: 'Update Account Configuration '
      description: Update account configuration
      tags:
        - Accounts
        - Configurations
  /prod/inputDevices/{inputDeviceId}:
    PUT:
      summary: 'Update Input Device '
      description: Updates the parameters for the input device.
      tags:
        - Device
        - Devices
        - Inputs
  /prod/inputDevices/{inputDeviceId}/thumbnailData:
    GET:
      summary: 'Describe Input Device Thumbnail '
      description: Get the latest thumbnail data for the input device.
      tags:
        - Data
        - Describe
        - Device
        - Devices
        - Inputs
        - Thumbnails
  /prod/offerings/{offeringId}:
    GET:
      summary: 'Describe Offering '
      description: Get details for an offering.
      tags:
        - Describe
        - Offerings
  /prod/channels/{channelId}/thumbnails:
    GET:
      summary: 'Describe Thumbnails '
      description: Describe the latest thumbnails data.
      tags:
        - Channels
        - Describe
        - Thumbnails
  /prod/inputDeviceTransfers:
    GET:
      summary: 'List Input Device Transfers '
      description: >-
        List input devices that are currently being transferred. List input
        devices that you are transferring from your AWS account or input devices
        that another AWS account is transferring to you.
      tags:
        - Device
        - Inputs
        - Transfers
  /prod/inputDevices:
    GET:
      summary: 'List Input Devices '
      description: List input devices
      tags:
        - Devices
        - Inputs
  /prod/offerings:
    GET:
      summary: 'List Offerings '
      description: List offerings available for purchase.
      tags:
        - Offerings
  /prod/reservations:
    GET:
      summary: 'List Reservations '
      description: List purchased reservations.
      tags:
        - Reservations
  /prod/offerings/{offeringId}/purchase:
    POST:
      summary: 'Purchase Offering '
      description: Purchase an offering and create a reservation.
      tags:
        - Offerings
        - Purchase
  /prod/inputDevices/{inputDeviceId}/reboot:
    POST:
      summary: 'Reboot Input Device '
      description: >-
        Send a reboot command to the specified input device. The device will
        begin rebooting within a few seconds of sending the command. When the
        reboot is complete, the device’s connection status will change to
        connected.
      tags:
        - Device
        - Devices
        - Inputs
        - Reboot
  /prod/inputDevices/{inputDeviceId}/reject:
    POST:
      summary: 'Reject Input Device Transfer '
      description: Reject the transfer of the specified input device to your AWS account.
      tags:
        - Device
        - Devices
        - Inputs
        - Reject
        - Transfers
  /prod/channels/{channelId}/start:
    POST:
      summary: 'Start Channel '
      description: Starts an existing channel
      tags:
        - Channels
  /prod/inputDevices/{inputDeviceId}/start:
    POST:
      summary: 'Start Input Device '
      description: >-
        Start an input device that is attached to a MediaConnect flow. (There is
        no need to start a device that is attached to a MediaLive input;
        MediaLive starts the device when the channel starts.)
      tags:
        - Device
        - Devices
        - Inputs
  /prod/inputDevices/{inputDeviceId}/startInputDeviceMaintenanceWindow:
    POST:
      summary: 'Start Input Device Maintenance Window '
      description: >-
        Start a maintenance window for the specified input device. Starting a
        maintenance window will give the device up to two hours to install
        software. If the device was streaming prior to the maintenance, it will
        resume streaming when the software is fully installed. Devices
        automatically install updates while they are powered on and their
        MediaLive channels are stopped. A maintenance window allows you to
        update a device without having to stop MediaLive channels that use the
        device. The device must remain powered on and connected to the internet
        for the duration of the maintenance.
      tags:
        - Device
        - Devices
        - Inputs
        - Maintenance
        - Window
  /prod/multiplexes/{multiplexId}/start:
    POST:
      summary: 'Start Multiplex '
      description: >-
        Start (run) the multiplex. Starting the multiplex does not start the
        channels. You must explicitly start each channel.
      tags:
        - Multiplex
        - Multiplexes
  /prod/channels/{channelId}/stop:
    POST:
      summary: 'Stop Channel '
      description: Stops a running channel
      tags:
        - Channels
        - Stop
  /prod/inputDevices/{inputDeviceId}/stop:
    POST:
      summary: 'Stop Input Device '
      description: >-
        Stop an input device that is attached to a MediaConnect flow. (There is
        no need to stop a device that is attached to a MediaLive input;
        MediaLive automatically stops the device when the channel stops.)
      tags:
        - Device
        - Devices
        - Inputs
        - Stop
  /prod/multiplexes/{multiplexId}/stop:
    POST:
      summary: 'Stop Multiplex '
      description: >-
        Stops a running multiplex. If the multiplex isn't running, this action
        has no effect.
      tags:
        - Multiplex
        - Multiplexes
        - Stop
  /prod/inputDevices/{inputDeviceId}/transfer:
    POST:
      summary: 'Transfer Input Device '
      description: >-
        Start an input device transfer to another AWS account. After you make
        the request, the other account must accept or reject the transfer.
      tags:
        - Device
        - Devices
        - Inputs
        - Transfers
  /prod/channels/{channelId}/channelClass:
    PUT:
      summary: 'Update Channel Class '
      description: Changes the class of t
      tags:
        - Channels
        - Classes
