openapi: 3.1.0
info:
  title: mediatailor
paths:
  /configureLogs/channel:
    PUT:
      summary: 'Configure Logs For Channel '
      description: <p>Configures Amazon CloudWatch log settings for a channel.</p>
      tags:
        - Channels
        - Configure
        - Logs
  /configureLogs/playbackConfiguration:
    PUT:
      summary: 'Configure Logs For Playback Configuration '
      description: <p>Amazon CloudWatch log settings for a playback configuration.</p>
      tags:
        - Configurations
        - Configure
        - Logs
        - Playback
  /channel/{ChannelName}:
    PUT:
      summary: 'Update Channel '
      description: >-
        <p>Updates a channel. For information about MediaTailor channels, see <a
        href="https://docs.aws.amazon.com/mediatailor/latest/ug/channel-assembly-channels.html">Working
        with channels</a> in the <i>MediaTailor User Guide</i>.</p>
      tags:
        - Channels
        - Names
  /sourceLocation/{SourceLocationName}/liveSource/{LiveSourceName}:
    PUT:
      summary: 'Update Live Source '
      description: <p>Updates a live source's configuration.</p>
      tags:
        - Live
        - Locations
        - Names
        - Sources
  /prefetchSchedule/{PlaybackConfigurationName}/{Name}:
    GET:
      summary: 'Get Prefetch Schedule '
      description: >-
        <p>Retrieves a prefetch schedule for a playback configuration. A
        prefetch schedule allows you to tell MediaTailor to fetch and prepare
        certain ads before an ad break happens. For more information about ad
        prefetching, see <a
        href="https://docs.aws.amazon.com/mediatailor/latest/ug/prefetching-ads.html">Using
        ad prefetching</a> in the <i>MediaTailor User Guide</i>.</p>
      tags:
        - Configurations
        - Names
        - Playback
        - Prefetch
        - Schedules
  /channel/{ChannelName}/program/{ProgramName}:
    PUT:
      summary: 'Update Program '
      description: <p>Updates a program within a channel.</p>
      tags:
        - Channels
        - Names
        - Program
  /sourceLocation/{SourceLocationName}:
    PUT:
      summary: 'Update Source Location '
      description: >-
        <p>Updates a source location. A source location is a container for
        sources. For more information about source locations, see <a
        href="https://docs.aws.amazon.com/mediatailor/latest/ug/channel-assembly-source-locations.html">Working
        with source locations</a> in the <i>MediaTailor User Guide</i>.</p>
      tags:
        - Locations
        - Names
        - Sources
  /sourceLocation/{SourceLocationName}/vodSource/{VodSourceName}:
    PUT:
      summary: 'Update Vod Source '
      description: <p>Updates a VOD source's configuration.</p>
      tags:
        - Locations
        - Names
        - Sources
  /channel/{ChannelName}/policy:
    PUT:
      summary: 'Put Channel Policy '
      description: >-
        <p>Creates an IAM policy for the channel. IAM policies are used to
        control access to your channel.</p>
      tags:
        - Channels
        - Names
        - Policies
  /playbackConfiguration/{Name}:
    GET:
      summary: 'Get Playback Configuration '
      description: >-
        <p>Retrieves a playback configuration. For information about MediaTailor
        configurations, see <a
        href="https://docs.aws.amazon.com/mediatailor/latest/ug/configurations.html">Working
        with configurations in AWS Elemental MediaTailor</a>.</p>
      tags:
        - Configurations
        - Names
        - Playback
  /channel/{ChannelName}/schedule:
    GET:
      summary: 'Get Channel Schedule '
      description: <p>Retrieves information about your channel's schedule.</p>
      tags:
        - Channels
        - Names
        - Schedules
  /alerts:
    GET:
      summary: 'List Alerts '
      description: >-
        <p>Lists the alerts that are associated with a MediaTailor channel
        assembly resource.</p>
      tags:
        - Alerts
  /channels:
    GET:
      summary: 'List Channels '
      description: >-
        <p>Retrieves information about the channels that are associated with the
        current AWS account.</p>
      tags:
        - Channels
  /sourceLocation/{SourceLocationName}/liveSources:
    GET:
      summary: 'List Live Sources '
      description: >-
        <p>Lists the live sources contained in a source location. A source
        represents a piece of content.</p>
      tags:
        - Live
        - Locations
        - Names
        - Sources
  /playbackConfigurations:
    GET:
      summary: 'List Playback Configurations '
      description: >-
        <p>Retrieves existing playback configurations. For information about
        MediaTailor configurations, see <a
        href="https://docs.aws.amazon.com/mediatailor/latest/ug/configurations.html">Working
        with Configurations in AWS Elemental MediaTailor</a>.</p>
      tags:
        - Configurations
        - Playback
  /prefetchSchedule/{PlaybackConfigurationName}:
    POST:
      summary: 'List Prefetch Schedules '
      description: <p>Lists the prefetch schedules for a playback configuration.</p>
      tags:
        - Configurations
        - Names
        - Playback
        - Prefetch
        - Schedules
  /sourceLocations:
    GET:
      summary: 'List Source Locations '
      description: >-
        <p>Lists the source locations for a channel. A source location defines
        the host server URL, and contains a list of sources.</p>
      tags:
        - Locations
        - Sources
  /tags/{ResourceArn}:
    DELETE:
      summary: 'Untag Resource '
      description: <p>The resource to untag.</p>
      tags:
        - ARN
        - Resources
        - Tags
        - Untag
  /sourceLocation/{SourceLocationName}/vodSources:
    GET:
      summary: 'List Vod Sources '
      description: >-
        <p>Lists the VOD sources contained in a source location. A source
        represents a piece of content.</p>
      tags:
        - Locations
        - Names
        - Sources
  /playbackConfiguration:
    PUT:
      summary: 'Put Playback Configuration '
      description: >-
        <p>Creates a playback configuration. For information about MediaTailor
        configurations, see <a
        href="https://docs.aws.amazon.com/mediatailor/latest/ug/configurations.html">Working
        with configurations in AWS Elemental MediaTailor</a>.</p>
      tags:
        - Configurations
        - Playback
  /channel/{ChannelName}/start:
    PUT:
      summary: 'Start Channel '
      description: >-
        <p>Starts a channel. For information about MediaTailor channels, see <a
        href="https://docs.aws.amazon.com/mediatailor/latest/ug/channel-assembly-channels.html">Working
        with channels</a> in the <i>MediaTailor User Guide</i>.</p>
      tags:
        - Channels
        - Names
  /channel/{ChannelName}/stop:
    PUT:
      summary: 'Stop Channel '
      description: >-
        <p>Stops a channel. For information about MediaTailor channels, see <a
        href="https://docs.aws.amazon.com/mediatailor/latest/ug/channel-assembly-channels.html">Working
        with channels</a> in the <i>MediaTailor User Guid
      tags:
        - Channels
        - Names
        - Stop
