openapi: 3.1.0
info:
  title: mgn
paths:
  /ArchiveApplication:
    POST:
      summary: 'Archive Application '
      description: <p>Archive application.</p>
      tags:
        - Applications
        - Archive
  /ArchiveWave:
    POST:
      summary: 'Archive Wave '
      description: <p>Archive wave.</p>
      tags:
        - Archive
        - Waves
  /AssociateApplications:
    POST:
      summary: 'Associate Applications '
      description: <p>Associate applications to wave.</p>
      tags:
        - Applications
        - Associate
  /AssociateSourceServers:
    POST:
      summary: 'Associate Source Servers '
      description: <p>Associate source servers to application.</p>
      tags:
        - Associate
        - Servers
        - Sources
  /ChangeServerLifeCycleState:
    POST:
      summary: 'Change Server Life Cycle State '
      description: >-
        <p>Allows the user to set the SourceServer.LifeCycle.state property for
        specific Source Server IDs to one of the following: READY_FOR_TEST or
        READY_FOR_CUTOVER. This command only works if the Source Server is
        already launchable (dataReplicationInfo.lagDuration is not null.)</p>
      tags:
        - Change
        - Cycle
        - Life
        - Servers
        - States
  /CreateApplication:
    POST:
      summary: 'Create Application '
      description: <p>Create application.</p>
      tags:
        - Applications
  /CreateConnector:
    POST:
      summary: 'Create Connector '
      description: <p>Create Connector.</p>
      tags:
        - Connectors
  /CreateLaunchConfigurationTemplate:
    POST:
      summary: 'Create Launch Configuration Template '
      description: <p>Creates a new Launch Configuration Template.</p>
      tags:
        - Configurations
        - Launch
        - Templates
  /CreateReplicationConfigurationTemplate:
    POST:
      summary: 'Create Replication Configuration Template '
      description: <p>Creates a new ReplicationConfigurationTemplate.</p>
      tags:
        - Configurations
        - Replication
        - Templates
  /CreateWave:
    POST:
      summary: 'Create Wave '
      description: <p>Create wave.</p>
      tags:
        - Waves
  /DeleteApplication:
    POST:
      summary: 'Delete Application '
      description: <p>Delete application.</p>
      tags:
        - Applications
  /DeleteConnector:
    POST:
      summary: 'Delete Connector '
      description: <p>Delete Connector.</p>
      tags:
        - Connectors
  /DeleteJob:
    POST:
      summary: 'Delete Job '
      description: <p>Deletes a single Job by ID.</p>
      tags:
        - Jobs
  /DeleteLaunchConfigurationTemplate:
    POST:
      summary: 'Delete Launch Configuration Template '
      description: <p>Deletes a single Launch Configuration Template by ID.</p>
      tags:
        - Configurations
        - Launch
        - Templates
  /DeleteReplicationConfigurationTemplate:
    POST:
      summary: 'Delete Replication Configuration Template '
      description: <p>Deletes a single Replication Configuration Template by ID</p>
      tags:
        - Configurations
        - Replication
        - Templates
  /DeleteSourceServer:
    POST:
      summary: 'Delete Source Server '
      description: <p>Deletes a single source server by ID.</p>
      tags:
        - Servers
        - Sources
  /DeleteVcenterClient:
    POST:
      summary: 'Delete Vcenter Client '
      description: <p>Deletes a given vCenter client by ID.</p>
      tags:
        - Clients
  /DeleteWave:
    POST:
      summary: 'Delete Wave '
      description: <p>Delete wave.</p>
      tags:
        - Waves
  /DescribeJobLogItems:
    POST:
      summary: 'Describe Job Log Items '
      description: <p>Retrieves detailed job log items with paging.</p>
      tags:
        - Describe
        - Items
        - Jobs
        - Logs
  /DescribeJobs:
    POST:
      summary: 'Describe Jobs '
      description: >-
        <p>Returns a list of Jobs. Use the JobsID and fromDate and toData
        filters to limit which jobs are returned. The response is sorted by
        creationDataTime - latest date first. Jobs are normally created by the
        StartTest, StartCutover, and TerminateTargetInstances APIs. Jobs are
        also created by DiagnosticLaunch and TerminateDiagnosticInstances, which
        are APIs available only to *Support* and only used in response to
        relevant support tickets.</p>
      tags:
        - Describe
        - Jobs
  /DescribeLaunchConfigurationTemplates:
    POST:
      summary: 'Describe Launch Configuration Templates '
      description: >-
        <p>Lists all Launch Configuration Templates, filtered by Launch
        Configuration Template IDs</p>
      tags:
        - Configurations
        - Describe
        - Launch
        - Templates
  /DescribeReplicationConfigurationTemplates:
    POST:
      summary: 'Describe Replication Configuration Templates '
      description: >-
        <p>Lists all ReplicationConfigurationTemplates, filtered by Source
        Server IDs.</p>
      tags:
        - Configurations
        - Describe
        - Replication
        - Templates
  /DescribeSourceServers:
    POST:
      summary: 'Describe Source Servers '
      description: <p>Retrieves all SourceServers or multiple SourceServers by ID.</p>
      tags:
        - Describe
        - Servers
        - Sources
  /DescribeVcenterClients:
    GET:
      summary: 'Describe Vcenter Clients '
      description: <p>Returns a list of the installed vCenter clients.</p>
      tags:
        - Clients
        - Describe
  /DisassociateApplications:
    POST:
      summary: 'Disassociate Applications '
      description: <p>Disassociate applications from wave.</p>
      tags:
        - Applications
        - Disassociate
  /DisassociateSourceServers:
    POST:
      summary: 'Disassociate Source Servers '
      description: <p>Disassociate source servers from application.</p>
      tags:
        - Disassociate
        - Servers
        - Sources
  /DisconnectFromService:
    POST:
      summary: 'Disconnect From Service '
      description: >-
        <p>Disconnects specific Source Servers from Application Migration
        Service. Data replication is stopped immediately. All AWS resources
        created by Application Migration Service for enabling the replication of
        these source servers will be terminated / deleted within 90 minutes.
        Launched Test or Cutover instances will NOT be terminated. If the agent
        on the source server has not been prevented from communicating with the
        Application Migration Service service, then it will receive a command to
        uninstall itself (within approximately 10 minutes). The following
        properties of the SourceServer will be changed immediately:
        dataReplicationInfo.dataReplicationState will be set to DISCONNECTED;
        The totalStorageBytes property for each of
        dataReplicationInfo.replicatedDisks will be set to zero;
        dataReplicationInfo.lagDuration and dataReplicationInfo.lagDuration will
        be nullified.</p>
      tags:
        - Disconnect
        - Services
  /FinalizeCutover:
    POST:
      summary: 'Finalize Cutover '
      description: >-
        <p>Finalizes the cutover immediately for specific Source Servers. All
        AWS resources created by Application Migration Service for enabling the
        replication of these source servers will be terminated / deleted within
        90 minutes. Launched Test or Cutover instances will NOT be terminated.
        The AWS Replication Agent will receive a command to uninstall itself
        (within 10 minutes). The following properties of the SourceServer will
        be changed immediately: dataReplicationInfo.dataReplicationState will be
        changed to DISCONNECTED; The SourceServer.lifeCycle.state will be
        changed to CUTOVER; The totalStorageBytes property fo each of
        dataReplicationInfo.replicatedDisks will be set to zero;
        dataReplicationInfo.lagDuration and dataReplicationInfo.lagDuration will
        be nullified.</p>
      tags:
        - Finalize
  /GetLaunchConfiguration:
    POST:
      summary: 'Get Launch Configuration '
      description: >-
        <p>Lists all LaunchConfigurations available, filtered by Source Server
        IDs.</p>
      tags:
        - Configurations
        - Launch
  /GetReplicationConfiguration:
    POST:
      summary: 'Get Replication Configuration '
      description: >-
        <p>Lists all ReplicationConfigurations, filtered by Source Server
        ID.</p>
      tags:
        - Configurations
        - Replication
  /InitializeService:
    POST:
      summary: 'Initialize Service '
      description: <p>Initialize Application Migration Service.</p>
      tags:
        - Initialize
        - Services
  /ListApplications:
    POST:
      summary: 'List Applications '
      description: <p>Retrieves all applications or multiple applications by ID.</p>
      tags:
        - Applications
  /ListConnectors:
    POST:
      summary: 'List Connectors '
      description: <p>List Connectors.</p>
      tags:
        - Connectors
  /ListExportErrors:
    POST:
      summary: 'List Export Errors '
      description: <p>List export errors.</p>
      tags:
        - Errors
        - Exports
  /ListExports:
    POST:
      summary: 'List Exports '
      description: <p>List exports.</p>
      tags:
        - Exports
  /ListImportErrors:
    POST:
      summary: 'List Import Errors '
      description: <p>List import errors.</p>
      tags:
        - Errors
        - Import
  /ListImports:
    POST:
      summary: 'List Imports '
      description: <p>List imports.</p>
      tags:
        - Imports
  /ListManagedAccounts:
    POST:
      summary: 'List Managed Accounts '
      description: <p>List Managed Accounts.</p>
      tags:
        - Accounts
        - Managed
  /ListSourceServerActions:
    POST:
      summary: 'List Source Server Actions '
      description: <p>List source server post migration custom actions.</p>
      tags:
        - Actions
        - Servers
        - Sources
  /tags/{resourceArn}:
    DELETE:
      summary: 'Untag Resource '
      description: >-
        <p>Deletes the specified set of tags from the specified set of
        Application Migration Service resources.</p>
      tags:
        - ARN
        - Resources
        - Tags
        - Untag
  /ListTemplateActions:
    POST:
      summary: 'List Template Actions '
      description: <p>List template post migration custom actions.</p>
      tags:
        - Actions
        - Templates
  /ListWaves:
    POST:
      summary: 'List Waves '
      description: <p>Retrieves all waves or multiple waves by ID.</p>
      tags:
        - Waves
  /MarkAsArchived:
    POST:
      summary: 'Mark As Archived '
      description: >-
        <p>Archives specific Source Servers by setting the
        SourceServer.isArchived property to true for specified SourceServers by
        ID. This command only works for SourceServers with a lifecycle. state
        which equals DISCONNECTED or CUTOVER.</p>
      tags:
        - Archived
        - Mark
  /PauseReplication:
    POST:
      summary: 'Pause Replication '
      description: <p>Pause Replication.</p>
      tags:
        - Pause
        - Replication
  /PutSourceServerAction:
    POST:
      summary: 'Put Source Server Action '
      description: <p>Put source server post migration custom action.</p>
      tags:
        - Actions
        - Servers
        - Sources
  /PutTemplateAction:
    POST:
      summary: 'Put Template Action '
      description: <p>Put template post migration custom action.</p>
      tags:
        - Actions
        - Templates
  /RemoveSourceServerAction:
    POST:
      summary: 'Remove Source Server Action '
      description: <p>Remove source server post migration custom action.</p>
      tags:
        - Actions
        - Removes
        - Servers
        - Sources
  /RemoveTemplateAction:
    POST:
      summary: 'Remove Template Action '
      description: <p>Remove template post migration custom action.</p>
      tags:
        - Actions
        - Removes
        - Templates
  /ResumeReplication:
    POST:
      summary: 'Resume Replication '
      description: <p>Resume Replication.</p>
      tags:
        - Replication
        - Resume
  /RetryDataReplication:
    POST:
      summary: 'Retry Data Replication '
      description: >-
        <p>Causes the data replication initiation sequence to begin immediately
        upon next Handshake for specified SourceServer IDs, regardless of when
        the previous initiation started. This command will not work if the
        SourceServer is not stalled or is in a DISCONNECTED or STOPPED
        state.</p>
      tags:
        - Data
        - Replication
        - Retry
  /StartCutover:
    POST:
      summary: 'Start Cutover '
      description: >-
        <p>Launches a Cutover Instance for specific Source Servers. This command
        starts a LAUNCH job whose initiatedBy property is StartCutover and
        changes the SourceServer.lifeCycle.state property to CUTTING_OVER.</p>
      tags: []
  /StartExport:
    POST:
      summary: 'Start Export '
      description: <p>Start export.</p>
      tags:
        - Exports
  /StartImport:
    POST:
      summary: 'Start Import '
      description: <p>Start import.</p>
      tags:
        - Import
  /StartReplication:
    POST:
      summary: 'Start Replication '
      description: <p>Starts replication for SNAPSHOT_SHIPPING agents.</p>
      tags:
        - Replication
  /StartTest:
    POST:
      summary: 'Start Test '
      description: >-
        <p>Launches a Test Instance for specific Source Servers. This command
        starts a LAUNCH job whose initiatedBy property is StartTest and changes
        the SourceServer.lifeCycle.state property to TESTING.</p>
      tags:
        - Tests
  /StopReplication:
    POST:
      summary: 'Stop Replication '
      description: <p>Stop Replication.</p>
      tags:
        - Replication
        - Stop
  /TerminateTargetInstances:
    POST:
      summary: 'Terminate Target Instances '
      description: >-
        <p>Starts a job that terminates specific launched EC2 Test and Cutover
        instances. This command will not work for any Source Server with a
        lifecycle.state of TESTING, CUTTING_OVER, or CUTOVER.</p>
      tags:
        - Instances
        - Target
        - Terminate
  /UnarchiveApplication:
    POST:
      summary: 'Unarchive Application '
      description: <p>Unarchive application.</p>
      tags:
        - Applications
        - Unarchive
  /UnarchiveWave:
    POST:
      summary: 'Unarchive Wave '
      description: <p>Unarchive wave.</p>
      tags:
        - Unarchive
        - Waves
  /UpdateApplication:
    POST:
      summary: 'Update Application '
      description: <p>Update application.</p>
      tags:
        - Applications
  /UpdateConnector:
    POST:
      summary: 'Update Connector '
      description: <p>Update Connector.</p>
      tags:
        - Connectors
  /UpdateLaunchConfiguration:
    POST:
      summary: 'Update Launch Configuration '
      description: <p>Updates multiple LaunchConfigurations by Source Server ID.</p>
      tags:
        - Configurations
        - Launch
  /UpdateLaunchConfigurationTemplate:
    POST:
      summary: 'Update Launch Configuration Template '
      description: <p>Updates an existing Launch Configuration Template by ID.</p>
      tags:
        - Configurations
        - Launch
        - Templates
  /UpdateReplicationConfiguration:
    POST:
      summary: 'Update Replication Configuration '
      description: >-
        <p>Allows you to update multiple ReplicationConfigurations by Source
        Server ID.</p>
      tags:
        - Configurations
        - Replication
  /UpdateReplicationConfigurationTemplate:
    POST:
      summary: 'Update Replication Configuration Template '
      description: <p>Updates multiple ReplicationConfigurationTemplates by ID.</p>
      tags:
        - Configurations
        - Replication
        - Templates
  /UpdateSourceServer:
    POST:
      summary: 'Update Source Server '
      description: <p>Update Source Server.</p>
      tags:
        - Servers
        - Sources
  /UpdateSourceServerReplicationType:
    POST:
      summary: 'Update Source Server Replication Type '
      description: >-
        <p>Allows you to change between the AGENT_BASED replication type and the
        SNAPSHOT_SHIPPING replication type.</p>
      tags:
        - Replication
        - Servers
        - Sources
        - Types
  /UpdateWave:
    POST:
      summary: 'Update Wave '
      description: <p>Update
      tags:
        - Waves
