openapi: 3.1.0
info:
  title: migrationhubstrategy
paths:
  /get-applicationcomponent-details/{applicationComponentId}:
    GET:
      summary: 'Get Application Component Details '
      description: <p> Retrieves details about an application component. </p>
      tags:
        - Application Components
        - Applications
        - Components
        - Details
  /get-applicationcomponent-strategies/{applicationComponentId}:
    GET:
      summary: 'Get Application Component Strategies '
      description: >-
        <p> Retrieves a list of all the recommended strategies and tools for an
        application component running on a server. </p>
      tags:
        - Application Components
        - Applications
        - Components
        - Strategies
  /get-assessment/{id}:
    GET:
      summary: 'Get Assessment '
      description: <p> Retrieves the status of an on-going assessment. </p>
      tags:
        - Assessments
  /get-import-file-task/{id}:
    GET:
      summary: 'Get Import File Task '
      description: <p> Retrieves the details about a specific import task. </p>
      tags:
        - File
        - Import
        - Tasks
  /get-latest-assessment-id:
    GET:
      summary: 'Get Latest Assessment Id '
      description: <p>Retrieve the latest ID of a specific assessment task.</p>
      tags:
        - Assessments
        - Latest
  /get-portfolio-preferences:
    GET:
      summary: 'Get Portfolio Preferences '
      description: <p> Retrieves your migration and modernization preferences. </p>
      tags:
        - Portfolio
        - Preferences
  /get-portfolio-summary:
    GET:
      summary: 'Get Portfolio Summary '
      description: >-
        <p> Retrieves overall summary including the number of servers to rehost
        and the overall number of anti-patterns. </p>
      tags:
        - Portfolio
        - Summaries
  /get-recommendation-report-details/{id}:
    GET:
      summary: 'Get Recommendation Report Details '
      description: >-
        <p> Retrieves detailed information about the specified recommendation
        report. </p>
      tags:
        - Details
        - Recommendations
        - Reports
  /get-server-details/{serverId}:
    GET:
      summary: 'Get Server Details '
      description: <p> Retrieves detailed information about a specified server. </p>
      tags:
        - Details
        - Servers
  /get-server-strategies/{serverId}:
    GET:
      summary: 'Get Server Strategies '
      description: >-
        <p> Retrieves recommended strategies and tools for the specified server.
        </p>
      tags:
        - Servers
        - Strategies
  /list-analyzable-servers:
    POST:
      summary: 'List Analyzable Servers '
      description: >-
        <p>Retrieves a list of all the servers fetched from customer vCenter
        using Strategy Recommendation Collector.</p>
      tags:
        - Analyzable
        - Servers
  /list-applicationcomponents:
    POST:
      summary: 'List Application Components '
      description: <p> Retrieves a list of all the application components (processes). </p>
      tags:
        - Application Components
        - Applications
        - Components
  /list-collectors:
    GET:
      summary: 'List Collectors '
      description: <p> Retrieves a list of all the installed collectors. </p>
      tags:
        - Collectors
  /list-import-file-task:
    GET:
      summary: 'List Import File Task '
      description: <p> Retrieves a list of all the imports performed. </p>
      tags:
        - File
        - Import
        - Tasks
  /list-servers:
    POST:
      summary: 'List Servers '
      description: <p> Returns a list of all the servers. </p>
      tags:
        - Servers
  /put-portfolio-preferences:
    POST:
      summary: 'Put Portfolio Preferences '
      description: <p> Saves the specified migration and modernization preferences. </p>
      tags:
        - Portfolio
        - Preferences
  /start-assessment:
    POST:
      summary: 'Start Assessment '
      description: <p> Starts the assessment of an on-premises environment. </p>
      tags:
        - Assessments
  /start-import-file-task:
    POST:
      summary: 'Start Import File Task '
      description: <p> Starts a file import. </p>
      tags:
        - File
        - Import
        - Tasks
  /start-recommendation-report-generation:
    POST:
      summary: 'Start Recommendation Report Generation '
      description: <p> Starts generating a recommendation report. </p>
      tags:
        - Generation
        - Recommendations
        - Reports
  /stop-assessment:
    POST:
      summary: 'Stop Assessment '
      description: <p> Stops the assessment of an on-premises environment. </p>
      tags:
        - Assessments
        - Stop
  /update-applicationcomponent-config/:
    POST:
      summary: 'Update Application Component Config '
      description: <p> Updates the configuration of an application component. </p>
      tags:
        - Application Components
        - Applications
        - Components
        - Configurations
  /update-server-config/:
    POST:
      summary: 'Update Server Config '
      description: <p> Updates the configuration of the specified s
      tags:
        - Configurations
        - Servers
