openapi: 3.1.0
info:
  title: migrationhuborchestrator
paths:
  /migrationworkflow/:
    POST:
      summary: 'Create Workflow '
      description: <p>Create a workflow to orchestrate your migrations.</p>
      tags:
        - Migration Workflows
        - Workflows
  /workflowstep:
    POST:
      summary: 'Create Workflow Step '
      description: <p>Create a step in the migration workflow.</p>
      tags:
        - Steps
        - Workflow Step
        - Workflows
  /workflowstepgroups:
    GET:
      summary: 'List Workflow Step Groups '
      description: <p>List the step groups in a migration workflow.</p>
      tags:
        - Groups
        - Steps
        - Workflow Step Groups
        - Workflows
  /migrationworkflow/{id}:
    POST:
      summary: 'Update Workflow '
      description: <p>Update a migration workflow.</p>
      tags:
        - Migration Workflows
        - Workflows
  /workflowstep/{id}:
    POST:
      summary: 'Update Workflow Step '
      description: <p>Update a step in a migration workflow.</p>
      tags:
        - Steps
        - Workflow Step
        - Workflows
  /workflowstepgroup/{id}:
    POST:
      summary: 'Update Workflow Step Group '
      description: <p>Update the step group in a migration workflow.</p>
      tags:
        - Groups
        - Steps
        - Workflow Step Group
        - Workflows
  /migrationworkflowtemplate/{id}:
    GET:
      summary: 'Get Template '
      description: >-
        <p>Get the template you want to use for creating a migration
        workflow.</p>
      tags:
        - Migration Workflow Templates
        - Templates
  /templatestep/{id}:
    GET:
      summary: 'Get Template Step '
      description: <p>Get a specific step in a template.</p>
      tags:
        - Steps
        - Template Steps
        - Templates
  /templates/{templateId}/stepgroups/{id}:
    GET:
      summary: 'Get Template Step Group '
      description: <p>Get a step group in a template.</p>
      tags:
        - Groups
        - Step Groups
        - Steps
        - Templates
  /plugins:
    GET:
      summary: 'List Plugins '
      description: <p>List AWS Migration Hub Orchestrator plugins.</p>
      tags:
        - Plugins
  /tags/{resourceArn}:
    DELETE:
      summary: 'Untag Resource '
      description: <p>Deletes the tags for a resource.</p>
      tags:
        - ARN
        - Resources
        - Tags
        - Untag
  /templatestepgroups/{templateId}:
    GET:
      summary: 'List Template Step Groups '
      description: <p>List the step groups in a template.</p>
      tags:
        - Groups
        - Steps
        - Templates
        - Templatestepgroups
  /templatesteps:
    GET:
      summary: 'List Template Steps '
      description: <p>List the steps in a template.</p>
      tags:
        - Steps
        - Template Steps
        - Templates
  /migrationworkflowtemplates:
    GET:
      summary: 'List Templates '
      description: >-
        <p>List the templates available in Migration Hub Orchestrator to create
        a migration workflow.</p>
      tags:
        - Migration Workflow Templates
        - Templates
  /workflow/{workflowId}/workflowstepgroups/{stepGroupId}/workflowsteps:
    GET:
      summary: 'List Workflow Steps '
      description: <p>List the steps in a workflow.</p>
      tags:
        - Groups
        - Steps
        - Workflow Step Groups
        - Workflow Steps
        - Workflows
  /migrationworkflows:
    GET:
      summary: 'List Workflows '
      description: <p>List the migration workflows.</p>
      tags:
        - Migration Workflows
        - Workflows
  /retryworkflowstep/{id}:
    POST:
      summary: 'Retry Workflow Step '
      description: <p>Retry a failed step in a migration workflow.</p>
      tags:
        - Retry
        - Retry Workflow Steps
        - Steps
        - Workflows
  /migrationworkflow/{id}/start:
    POST:
      summary: 'Start Workflow '
      description: <p>Start a migration workflow.</p>
      tags:
        - Migration Workflows
        - Workflows
  /migrationworkflow/{id}/stop:
    POST:
      summary: 'Stop Workflow '
      description: <p>Stop an ongoing migration wor
      tags:
        - Migration Workflows
        - Stop
        - Workflows
