openapi: 3.1.0
info:
  title: monitoring
paths:
  /:
    POST:
      summary: 'Untag Resource '
      description: <p>Removes one or more tags from the specified res
      tags:
        - Resources
        - Untag
