openapi: 3.1.0
info:
  title: mwaa
paths:
  /clitoken/{Name}:
    POST:
      summary: 'Create Cli Token '
      description: >-
        <p>Creates a CLI token for the Airflow CLI. To learn more, see <a
        href="https://docs.aws.amazon.com/mwaa/latest/userguide/call-mwaa-apis-cli.html">Creating
        an Apache Airflow CLI token</a>.</p>
      tags:
        - CLI
        - Clitoken
        - Names
        - Tokens
  /environments/{Name}:
    PATCH:
      summary: 'Update Environment '
      description: >-
        <p>Updates an Amazon Managed Workflows for Apache Airflow (MWAA)
        environment.</p>
      tags:
        - Environments
        - Names
  /webtoken/{Name}:
    POST:
      summary: 'Create Web Login Token '
      description: >-
        <p>Creates a web login token for the Airflow Web UI. To learn more, see
        <a
        href="https://docs.aws.amazon.com/mwaa/latest/userguide/call-mwaa-apis-web.html">Creating
        an Apache Airflow web login token</a>.</p>
      tags:
        - Login
        - Names
        - Tokens
        - Web
        - Webtoken
  /environments:
    GET:
      summary: 'List Environments '
      description: >-
        <p>Lists the Amazon Managed Workflows for Apache Airflow (MWAA)
        environments.</p>
      tags:
        - Environments
  /tags/{ResourceArn}:
    DELETE:
      summary: 'Untag Resource '
      description: >-
        <p>Removes key-value tag pairs associated to your Amazon Managed
        Workflows for Apache Airflow (MWAA) environment. For example,
        <code>"Environment": "Staging"</code>.</p>
      tags:
        - ARN
        - Resources
        - Tags
        - Untag
  /metrics/environments/{EnvironmentName}:
    POST:
      summary: 'Publish Metrics '
      description: >-
        <p> <b>Internal only</b>. Publishes environment health metrics to Amazon
        Cloud
      tags:
        - Environments
        - Metrics
        - Names
        - Publish
