openapi: 3.1.0
info:
  title: neptune-graph
paths:
  /importtasks/{taskIdentifier}:
    GET:
      summary: 'Get Import Task '
      description: <p>Retrieves a specified import task.</p>
      tags:
        - Import
        - Import Tasks
        - Tasks
  /queries/{queryId}:
    GET:
      summary: 'Get Query '
      description: >-
        <p>Retrieves the status of a specified query.</p> <note> <p> When
        invoking this operation in a Neptune Analytics cluster, the IAM user or
        role making the request must have the
        <code>neptune-graph:GetQueryStatus</code> IAM action attached. </p>
        </note>
      tags:
        - Queries
  /graphs:
    GET:
      summary: 'List Graphs '
      description: <p>Lists available Neptune Analytics graphs.</p>
      tags:
        - Graphs
  /snapshots:
    GET:
      summary: 'List Graph Snapshots '
      description: <p>Lists available snapshots of a specified Neptune Analytics graph.</p>
      tags:
        - Graphs
        - Snapshots
  /importtasks:
    GET:
      summary: 'List Import Tasks '
      description: <p>Lists import tasks.</p>
      tags:
        - Import
        - Import Tasks
        - Tasks
  /graphs/{graphIdentifier}/endpoints/:
    GET:
      summary: 'List Private Graph Endpoints '
      description: <p>Lists private endpoints for a specified Neptune Analytics graph.</p>
      tags:
        - Endpoints
        - Graphs
        - Private
  /graphs/{graphIdentifier}:
    PATCH:
      summary: 'Update Graph '
      description: <p>Updates the configuration of a specified Neptune Analytics graph</p>
      tags:
        - Graphs
  /snapshots/{snapshotIdentifier}:
    GET:
      summary: 'Get Graph Snapshot '
      description: <p>Retrieves a specified graph snapshot.</p>
      tags:
        - Graphs
        - Snapshots
  /graphs/{graphIdentifier}/endpoints/{vpcId}:
    GET:
      summary: 'Get Private Graph Endpoint '
      description: <p>Retrieves information about a specified private endpoint.</p>
      tags:
        - Endpoints
        - Graphs
        - Private
        - VPC
  /queries:
    GET:
      summary: 'List Queries '
      description: <p>Lists active openCypher queries.</p>
      tags:
        - Queries
  /summary:
    GET:
      summary: 'Get Graph Summary '
      description: <p>Gets a graph summary for a property graph.</p>
      tags:
        - Graphs
        - Summaries
  /tags/{resourceArn}:
    DELETE:
      summary: 'Untag Resource '
      description: <p>Removes the specified tags from the specified resource.</p>
      tags:
        - ARN
        - Resources
        - Tags
        - Untag
  /snapshots/{snapshotIdentifier}/restore:
    POST:
      summary: 'Restore Graph From Snapshot '
      description: <p>Restores a graph from a sna
      tags:
        - Graphs
        - Restore
        - Snapshots
