openapi: 3.1.0
info:
  title: networkmanager
paths:
  /attachments/{attachmentId}/accept:
    POST:
      summary: 'Accept Attachment '
      description: >-
        <p>Accepts a core network attachment request. </p> <p>Once the
        attachment request is accepted by a core network owner, the attachment
        is created and connected to a core network.</p>
      tags:
        - Accept
        - Attachments
  /global-networks/{globalNetworkId}/connect-peer-associations:
    GET:
      summary: 'Get Connect Peer Associations '
      description: >-
        <p>Returns information about a core network Connect peer
        associations.</p>
      tags:
        - Associations
        - Connect
        - Global
        - Networks
        - Peer
  /global-networks/{globalNetworkId}/customer-gateway-associations:
    GET:
      summary: 'Get Customer Gateway Associations '
      description: >-
        <p>Gets the association information for customer gateways that are
        associated with devices and links in your global network.</p>
      tags:
        - Associations
        - Customers
        - Gateways
        - Global
        - Networks
  /global-networks/{globalNetworkId}/link-associations:
    GET:
      summary: 'Get Link Associations '
      description: >-
        <p>Gets the link associations for a device or a link. Either the device
        ID or the link ID must be specified.</p>
      tags:
        - Associations
        - Global
        - Link
        - Networks
  /global-networks/{globalNetworkId}/transit-gateway-connect-peer-associations:
    GET:
      summary: 'Get Transit Gateway Connect Peer Associations '
      description: >-
        <p>Gets information about one or more of your transit gateway Connect
        peer associations in a global network.</p>
      tags:
        - Associations
        - Connect
        - Gateways
        - Global
        - Networks
        - Peer
        - Transit
  /connect-attachments:
    POST:
      summary: 'Create Connect Attachment '
      description: >-
        <p>Creates a core network Connect attachment from a specified core
        network attachment. </p> <p>A core network Connect attachment is a
        GRE-based tunnel attachment that you can use to establish a connection
        between a core network and an appliance. A core network Connect
        attachment uses an existing VPC attachment as the underlying transport
        mechanism.</p>
      tags:
        - Attachments
        - Connect
  /connect-peers:
    GET:
      summary: 'List Connect Peers '
      description: <p>Returns a list of core network Connect peers.</p>
      tags:
        - Connect
        - Peers
  /global-networks/{globalNetworkId}/connections:
    GET:
      summary: 'Get Connections '
      description: >-
        <p>Gets information about one or more of your connections in a global
        network.</p>
      tags:
        - Connections
        - Global
        - Networks
  /core-networks:
    GET:
      summary: 'List Core Networks '
      description: <p>Returns a list of owned and shared core networks.</p>
      tags:
        - Core
        - Networks
  /global-networks/{globalNetworkId}/devices:
    GET:
      summary: 'Get Devices '
      description: >-
        <p>Gets information about one or more of your devices in a global
        network.</p>
      tags:
        - Devices
        - Global
        - Networks
  /global-networks:
    GET:
      summary: 'Describe Global Networks '
      description: >-
        <p>Describes one or more global networks. By default, all global
        networks are described. To describe the objects in your global network,
        you must use the appropriate <code>Get*</code> action. For example, to
        list the transit gateways in your global network, use
        <a>GetTransitGatewayRegistrations</a>.</p>
      tags:
        - Describe
        - Global
        - Networks
  /global-networks/{globalNetworkId}/links:
    GET:
      summary: 'Get Links '
      description: >-
        <p>Gets information about one or more links in a specified global
        network.</p> <p>If you specify the site ID, you cannot specify the type
        or provider in the same request. You can specify the type and provider
        in the same request.</p>
      tags:
        - Global
        - Links
        - Networks
  /global-networks/{globalNetworkId}/sites:
    GET:
      summary: 'Get Sites '
      description: >-
        <p>Gets information about one or more of your sites in a global
        network.</p>
      tags:
        - Global
        - Networks
        - Sites
  /site-to-site-vpn-attachments:
    POST:
      summary: 'Create Site To Site Vpn Attachment '
      description: >-
        <p>Creates an Amazon Web Services site-to-site VPN attachment on an edge
        location of a core network.</p>
      tags:
        - Attachments
        - Sites
        - VPN
  /transit-gateway-peerings:
    POST:
      summary: 'Create Transit Gateway Peering '
      description: <p>Creates a transit gateway peering connection.</p>
      tags:
        - Gateways
        - Peerings
        - Transit
  /transit-gateway-route-table-attachments:
    POST:
      summary: 'Create Transit Gateway Route Table Attachment '
      description: <p>Creates a transit gateway route table attachment.</p>
      tags:
        - Attachments
        - Gateways
        - Routes
        - Tables
        - Transit
  /vpc-attachments:
    POST:
      summary: 'Create Vpc Attachment '
      description: <p>Creates a VPC attachment on an edge location of a core network.</p>
      tags:
        - Attachments
        - VPC
  /attachments/{attachmentId}:
    DELETE:
      summary: 'Delete Attachment '
      description: <p>Deletes an attachment. Supports all attachment types.</p>
      tags:
        - Attachments
  /connect-peers/{connectPeerId}:
    GET:
      summary: 'Get Connect Peer '
      description: <p>Returns information about a core network Connect peer.</p>
      tags:
        - Connect
        - Peer
        - Peers
  /global-networks/{globalNetworkId}/connections/{connectionId}:
    PATCH:
      summary: 'Update Connection '
      description: >-
        <p>Updates the information for an existing connection. To remove
        information for any of the parameters, specify an empty string.</p>
      tags:
        - Connections
        - Global
        - Networks
  /core-networks/{coreNetworkId}:
    PATCH:
      summary: 'Update Core Network '
      description: <p>Updates the description of a core network.</p>
      tags:
        - Core
        - Networks
  /core-networks/{coreNetworkId}/core-network-policy-versions/{policyVersionId}:
    DELETE:
      summary: 'Delete Core Network Policy Version '
      description: >-
        <p>Deletes a policy version from a core network. You can't delete the
        current LIVE policy.</p>
      tags:
        - Core
        - Networks
        - Policies
        - Versions
  /global-networks/{globalNetworkId}/devices/{deviceId}:
    PATCH:
      summary: 'Update Device '
      description: >-
        <p>Updates the details for an existing device. To remove information for
        any of the parameters, specify an empty string.</p>
      tags:
        - Device
        - Devices
        - Global
        - Networks
  /global-networks/{globalNetworkId}:
    PATCH:
      summary: 'Update Global Network '
      description: >-
        <p>Updates an existing global network. To remove information for any of
        the parameters, specify an empty string.</p>
      tags:
        - Global
        - Networks
  /global-networks/{globalNetworkId}/links/{linkId}:
    PATCH:
      summary: 'Update Link '
      description: >-
        <p>Updates the details for an existing link. To remove information for
        any of the parameters, specify an empty string.</p>
      tags:
        - Global
        - Link
        - Links
        - Networks
  /peerings/{peeringId}:
    DELETE:
      summary: 'Delete Peering '
      description: <p>Deletes an existing peering connection.</p>
      tags:
        - Peerings
  /resource-policy/{resourceArn}:
    POST:
      summary: 'Put Resource Policy '
      description: <p>Creates or updates a resource policy.</p>
      tags:
        - ARN
        - Policies
        - Resources
  /global-networks/{globalNetworkId}/sites/{siteId}:
    PATCH:
      summary: 'Update Site '
      description: >-
        <p>Updates the information for an existing site. To remove information
        for any of the parameters, specify an empty string.</p>
      tags:
        - Global
        - Networks
        - Sites
  /global-networks/{globalNetworkId}/transit-gateway-registrations/{transitGatewayArn}:
    DELETE:
      summary: 'Deregister Transit Gateway '
      description: >-
        <p>Deregisters a transit gateway from your global network. This action
        does not delete your transit gateway, or modify any of its attachments.
        This action removes any customer gateway associations.</p>
      tags:
        - ARN
        - Deregister
        - Gateways
        - Global
        - Networks
        - Registrations
        - Transit
  /global-networks/{globalNetworkId}/connect-peer-associations/{connectPeerId}:
    DELETE:
      summary: 'Disassociate Connect Peer '
      description: >-
        <p>Disassociates a core network Connect peer from a device and a link.
        </p>
      tags:
        - Associations
        - Connect
        - Disassociate
        - Global
        - Networks
        - Peer
  /global-networks/{globalNetworkId}/customer-gateway-associations/{customerGatewayArn}:
    DELETE:
      summary: 'Disassociate Customer Gateway '
      description: <p>Disassociates a customer gateway from a device and a link.</p>
      tags:
        - ARN
        - Associations
        - Customers
        - Disassociate
        - Gateways
        - Global
        - Networks
  /global-networks/{globalNetworkId}/transit-gateway-connect-peer-associations/{transitGatewayConnectPeerArn}:
    DELETE:
      summary: 'Disassociate Transit Gateway Connect Peer '
      description: >-
        <p>Disassociates a transit gateway Connect peer from a device and
        link.</p>
      tags:
        - ARN
        - Associations
        - Connect
        - Disassociate
        - Gateways
        - Global
        - Networks
        - Peer
        - Transit
  /core-networks/{coreNetworkId}/core-network-change-sets/{policyVersionId}/execute:
    POST:
      summary: 'Execute Core Network Change Set '
      description: >-
        <p>Executes a change set on your core network. Deploys changes globally
        based on the policy submitted..</p>
      tags:
        - Change
        - Core
        - Execute
        - Networks
        - Policies
        - Sets
        - Versions
  /connect-attachments/{attachmentId}:
    GET:
      summary: 'Get Connect Attachment '
      description: <p>Returns information about a core network Connect attachment.</p>
      tags:
        - Attachments
        - Connect
  /core-networks/{coreNetworkId}/core-network-change-events/{policyVersionId}:
    GET:
      summary: 'Get Core Network Change Events '
      description: <p>Returns information about a core network change event.</p>
      tags:
        - Change
        - Core
        - Events
        - Networks
        - Policies
        - Versions
  /core-networks/{coreNetworkId}/core-network-change-sets/{policyVersionId}:
    GET:
      summary: 'Get Core Network Change Set '
      description: >-
        <p>Returns a change set between the LIVE core network policy and a
        submitted policy.</p>
      tags:
        - Change
        - Core
        - Networks
        - Policies
        - Sets
        - Versions
  /core-networks/{coreNetworkId}/core-network-policy:
    POST:
      summary: 'Put Core Network Policy '
      description: >-
        <p>Creates a new, immutable version of a core network policy. A
        subsequent change set is created showing the differences between the
        LIVE policy and the submitted policy.</p>
      tags:
        - Core
        - Networks
        - Policies
  /global-networks/{globalNetworkId}/network-resource-count:
    GET:
      summary: 'Get Network Resource Counts '
      description: >-
        <p>Gets the count of network resources, by resource type, for the
        specified global network.</p>
      tags:
        - Count
        - Counts
        - Global
        - Networks
        - Resources
  /global-networks/{globalNetworkId}/network-resource-relationships:
    GET:
      summary: 'Get Network Resource Relationships '
      description: >-
        <p>Gets the network resource relationships for the specified global
        network.</p>
      tags:
        - Global
        - Networks
        - Relationships
        - Resources
  /global-networks/{globalNetworkId}/network-resources:
    GET:
      summary: 'Get Network Resources '
      description: >-
        <p>Describes the network resources for the specified global network.</p>
        <p>The results include information from the corresponding Describe call
        for the resource, minus any sensitive information such as pre-shared
        keys.</p>
      tags:
        - Global
        - Networks
        - Resources
  /global-networks/{globalNetworkId}/network-routes:
    POST:
      summary: 'Get Network Routes '
      description: <p>Gets the network routes of the specified global network.</p>
      tags:
        - Global
        - Networks
        - Routes
  /global-networks/{globalNetworkId}/network-telemetry:
    GET:
      summary: 'Get Network Telemetry '
      description: <p>Gets the network telemetry of the specified global network.</p>
      tags:
        - Global
        - Networks
        - Telemetry
  /global-networks/{globalNetworkId}/route-analyses/{routeAnalysisId}:
    GET:
      summary: 'Get Route Analysis '
      description: <p>Gets information about the specified route analysis.</p>
      tags:
        - Analysis
        - Global
        - Networks
        - Routes
  /site-to-site-vpn-attachments/{attachmentId}:
    GET:
      summary: 'Get Site To Site Vpn Attachment '
      description: <p>Returns information about a site-to-site VPN attachment.</p>
      tags:
        - Attachments
        - Sites
        - VPN
  /transit-gateway-peerings/{peeringId}:
    GET:
      summary: 'Get Transit Gateway Peering '
      description: <p>Returns information about a transit gateway peer.</p>
      tags:
        - Gateways
        - Peerings
        - Transit
  /global-networks/{globalNetworkId}/transit-gateway-registrations:
    POST:
      summary: 'Register Transit Gateway '
      description: >-
        <p>Registers a transit gateway in your global network. Not all Regions
        support transit gateways for global networks. For a list of the
        supported Regions, see <a
        href="https://docs.aws.amazon.com/network-manager/latest/tgwnm/what-are-global-networks.html#nm-available-regions">Region
        Availability</a> in the <i>Amazon Web Services Transit Gateways for
        Global Networks User Guide</i>. The transit gateway can be in any of the
        supported Amazon Web Services Regions, but it must be owned by the same
        Amazon Web Services account that owns the global network. You cannot
        register a transit gateway in more than one global network.</p>
      tags:
        - Gateways
        - Global
        - Networks
        - Register
        - Registrations
        - Transit
  /transit-gateway-route-table-attachments/{attachmentId}:
    GET:
      summary: 'Get Transit Gateway Route Table Attachment '
      description: >-
        <p>Returns information about a transit gateway route table
        attachment.</p>
      tags:
        - Attachments
        - Gateways
        - Routes
        - Tables
        - Transit
  /vpc-attachments/{attachmentId}:
    PATCH:
      summary: 'Update Vpc Attachment '
      description: <p>Updates a VPC attachment.</p>
      tags:
        - Attachments
        - VPC
  /attachments:
    GET:
      summary: 'List Attachments '
      description: <p>Returns a list of core network attachments.</p>
      tags:
        - Attachments
  /core-networks/{coreNetworkId}/core-network-policy-versions:
    GET:
      summary: 'List Core Network Policy Versions '
      description: <p>Returns a list of core network policy versions.</p>
      tags:
        - Core
        - Networks
        - Policies
        - Versions
  /organizations/service-access:
    POST:
      summary: 'Start Organization Service Access Update '
      description: >-
        <p>Enables the Network Manager service for an Amazon Web Services
        Organization. This can only be called by a management account within the
        organization. </p>
      tags:
        - Access
        - Organizations
        - Services
  /peerings:
    GET:
      summary: 'List Peerings '
      description: <p>Lists the peerings for a core network.</p>
      tags:
        - Peerings
  /tags/{resourceArn}:
    DELETE:
      summary: 'Untag Resource '
      description: <p>Removes tags from a specified resource.</p>
      tags:
        - ARN
        - Resources
        - Tags
        - Untag
  /attachments/{attachmentId}/reject:
    POST:
      summary: 'Reject Attachment '
      description: <p>Rejects a core network attachment request.</p>
      tags:
        - Attachments
        - Reject
  /core-networks/{coreNetworkId}/core-network-policy-versions/{policyVersionId}/restore:
    POST:
      summary: 'Restore Core Network Policy Version '
      description: >-
        <p>Restores a previous policy version as a new, immutable version of a
        core network policy. A subsequent change set is created showing the
        differences between the LIVE policy and restored policy.</p>
      tags:
        - Core
        - Networks
        - Policies
        - Restore
        - Versions
  /global-networks/{globalNetworkId}/route-analyses:
    POST:
      summary: 'Start Route Analysis '
      description: >-
        <p>Starts analyzing the routing path between the specified source and
        destination. For more information, see <a
        href="https://docs.aws.amazon.com/vpc/latest/tgw/route-analyzer.html">Route
        Analyzer</a>.</p>
      tags:
        - Analysis
        - Global
        - Networks
        - Routes
  /global-networks/{globalNetworkId}/network-resources/{resourceArn}/metadata:
    PATCH:
      summary: 'Update Network Resource Metadata '
      description: <p>Updates the resource metadata for the specified global ne
      tags:
        - ARN
        - Global
        - Metadata
        - Networks
        - Resources
