openapi: 3.1.0
info:
  title: nimble
paths:
  /2020-08-01/studios/{studioId}/eula-acceptances:
    GET:
      summary: 'List Eula Acceptances '
      description: <p>List EULA acceptances.</p>
      tags:
        - Acceptances
        - EULA
        - Studios
  /2020-08-01/studios/{studioId}/launch-profiles:
    GET:
      summary: 'List Launch Profiles '
      description: <p>List all the launch profiles a studio.</p>
      tags:
        - Launch
        - Profiles
        - Studios
  /2020-08-01/studios/{studioId}/streaming-images:
    GET:
      summary: 'List Streaming Images '
      description: >-
        <p>List the streaming image resources available to this studio.</p>
        <p>This list will contain both images provided by Amazon Web Services,
        as well as streaming images that you have created in your studio.</p>
      tags:
        - Images
        - Streaming
        - Studios
  /2020-08-01/studios/{studioId}/streaming-sessions:
    GET:
      summary: 'List Streaming Sessions '
      description: <p>Lists the streaming sessions in a studio.</p>
      tags:
        - Sessions
        - Streaming
        - Studios
  /2020-08-01/studios/{studioId}/streaming-sessions/{sessionId}/streams:
    POST:
      summary: 'Create Streaming Session Stream '
      description: >-
        <p>Creates a streaming session stream for a streaming session.</p>
        <p>After invoking this API, invoke GetStreamingSessionStream with the
        returned streamId to poll the resource until it is in the
        <code>READY</code> state.</p>
      tags:
        - Sessions
        - Stream
        - Streaming
        - Streams
        - Studios
  /2020-08-01/studios:
    GET:
      summary: 'List Studios '
      description: >-
        <p>List studios in your Amazon Web Services accounts in the requested
        Amazon Web Services Region.</p>
      tags:
        - Studios
  /2020-08-01/studios/{studioId}/studio-components:
    GET:
      summary: 'List Studio Components '
      description: <p>Lists the <code>StudioComponents</code> in a studio.</p>
      tags:
        - Components
        - Studios
  /2020-08-01/studios/{studioId}/launch-profiles/{launchProfileId}:
    PATCH:
      summary: 'Update Launch Profile '
      description: <p>Update a launch profile.</p>
      tags:
        - Launch
        - Profiles
        - Studios
  /2020-08-01/studios/{studioId}/launch-profiles/{launchProfileId}/membership/{principalId}:
    PATCH:
      summary: 'Update Launch Profile Member '
      description: <p>Update a user persona in launch profile membership.</p>
      tags:
        - Launch
        - Members
        - Memberships
        - Principals
        - Profiles
        - Studios
  /2020-08-01/studios/{studioId}/streaming-images/{streamingImageId}:
    PATCH:
      summary: 'Update Streaming Image '
      description: <p>Update streaming image.</p>
      tags:
        - Images
        - Streaming
        - Studios
  /2020-08-01/studios/{studioId}/streaming-sessions/{sessionId}:
    GET:
      summary: 'Get Streaming Session '
      description: >-
        <p>Gets StreamingSession resource.</p> <p>Invoke this operation to poll
        for a streaming session state while creating or deleting a session.</p>
      tags:
        - Sessions
        - Streaming
        - Studios
  /2020-08-01/studios/{studioId}:
    PATCH:
      summary: 'Update Studio '
      description: >-
        <p>Update a Studio resource.</p> <p>Currently, this operation only
        supports updating the displayName of your studio.</p>
      tags:
        - Studios
  /2020-08-01/studios/{studioId}/studio-components/{studioComponentId}:
    PATCH:
      summary: 'Update Studio Component '
      description: <p>Updates a studio component resource.</p>
      tags:
        - Components
        - Studios
  /2020-08-01/studios/{studioId}/membership/{principalId}:
    GET:
      summary: 'Get Studio Member '
      description: <p>Get a user's membership in a studio.</p>
      tags:
        - Members
        - Memberships
        - Principals
        - Studios
  /2020-08-01/eulas/{eulaId}:
    GET:
      summary: 'Get Eula '
      description: <p>Get EULA.</p>
      tags:
        - EULA
        - Eulas
  /2020-08-01/studios/{studioId}/launch-profiles/{launchProfileId}/details:
    GET:
      summary: 'Get Launch Profile Details '
      description: >-
        <p>Launch profile details include the launch profile resource and
        summary information of resources that are used by, or available to, the
        launch profile. This includes the name and description of all studio
        components used by the launch profiles, and the name and description of
        streaming images that can be used with this launch profile.</p>
      tags:
        - Details
        - Launch
        - Profiles
        - Studios
  /2020-08-01/studios/{studioId}/launch-profiles/{launchProfileId}/init:
    GET:
      summary: 'Get Launch Profile Initialization '
      description: <p>Get a launch profile initialization.</p>
      tags:
        - Initialization
        - Initialize
        - Launch
        - Profiles
        - Studios
  /2020-08-01/studios/{studioId}/streaming-session-backups/{backupId}:
    GET:
      summary: 'Get Streaming Session Backup '
      description: >-
        <p>Gets <code>StreamingSessionBackup</code> resource.</p> <p>Invoke this
        operation to poll for a streaming session backup while stopping a
        streaming session.</p>
      tags:
        - Backup
        - Backups
        - Sessions
        - Streaming
        - Studios
  /2020-08-01/studios/{studioId}/streaming-sessions/{sessionId}/streams/{streamId}:
    GET:
      summary: 'Get Streaming Session Stream '
      description: >-
        <p>Gets a StreamingSessionStream for a streaming session.</p> <p>Invoke
        this operation to poll the resource after invoking
        <code>CreateStreamingSessionStream</code>.</p> <p>After the
        <code>StreamingSessionStream</code> changes to the <code>READY</code>
        state, the url property will contain a stream to be used with the DCV
        streaming client.</p>
      tags:
        - Sessions
        - Stream
        - Streaming
        - Streams
        - Studios
  /2020-08-01/eulas:
    GET:
      summary: 'List Eulas '
      description: <p>List EULAs.</p>
      tags:
        - Eulas
  /2020-08-01/studios/{studioId}/launch-profiles/{launchProfileId}/membership:
    POST:
      summary: 'Put Launch Profile Members '
      description: <p>Add/update users with given persona to launch profile membership.</p>
      tags:
        - Launch
        - Members
        - Memberships
        - Profiles
        - Studios
  /2020-08-01/studios/{studioId}/streaming-session-backups:
    GET:
      summary: 'List Streaming Session Backups '
      description: <p>Lists the backups of a streaming session in a studio.</p>
      tags:
        - Backups
        - Sessions
        - Streaming
        - Studios
  /2020-08-01/studios/{studioId}/membership:
    POST:
      summary: 'Put Studio Members '
      description: <p>Add/update users with given persona to studio membership.</p>
      tags:
        - Members
        - Memberships
        - Studios
  /2020-08-01/tags/{resourceArn}:
    DELETE:
      summary: 'Untag Resource '
      description: <p>Deletes the tags for a resource.</p>
      tags:
        - ARN
        - Resources
        - Tags
        - Untag
  /2020-08-01/studios/{studioId}/streaming-sessions/{sessionId}/start:
    POST:
      summary: 'Start Streaming Session '
      description: >-
        <p>Transitions sessions from the <code>STOPPED</code> state into the
        <code>READY</code> state. The <code>START_IN_PROGRESS</code> state is
        the intermediate state between the <code>STOPPED</code> and
        <code>READY</code> states.</p>
      tags:
        - Sessions
        - Streaming
        - Studios
  /2020-08-01/studios/{studioId}/sso-configuration:
    PUT:
      summary: 'Start Studio SSOConfiguration Repair '
      description: >-
        <p>Repairs the IAM Identity Center configuration for a given studio.</p>
        <p>If the studio has a valid IAM Identity Center configuration currently
        associated with it, this operation will fail with a validation
        error.</p> <p>If the studio does not have a valid IAM Identity Center
        configuration currently associated with it, then a new IAM Identity
        Center application is created for the studio and the studio is changed
        to the <code>READY</code> state.</p> <p>After the IAM Identity Center
        application is repaired, you must use the Amazon Nimble Studio console
        to add administrators and users to your studio.</p>
      tags:
        - Configurations
        - Repair
        - SSO
        - SSOConfiguration
        - Studios
  /2020-08-01/studios/{studioId}/streaming-sessions/{sessionId}/stop:
    POST:
      summary: 'Stop Streaming Session '
      description: >-
        <p>Transitions sessions from the <code>READY</code> state into the
        <code>STOPPED</code> state. The <code>STOP_IN_PROGRESS</code> state is
        the intermediate state between the <code>READY</code> and
        <code>STOPPED</code> s
      tags:
        - Sessions
        - Stop
        - Streaming
        - Studios
