openapi: 3.1.0
info:
  title: oam
paths:
  /CreateLink:
    POST:
      summary: 'Create Link '
      description: >-
        <p>Creates a link between a source account and a sink that you have
        created in a monitoring account.</p> <p>Before you create a link, you
        must create a sink in the monitoring account and create a sink policy in
        that account. The sink policy must permit the source account to link to
        it. You can grant permission to source accounts by granting permission
        to an entire organization or to individual accounts.</p> <p>For more
        information, see <a
        href="https://docs.aws.amazon.com/OAM/latest/APIReference/API_CreateSink.html">CreateSink</a>
        and <a
        href="https://docs.aws.amazon.com/OAM/latest/APIReference/API_PutSinkPolicy.html">PutSinkPolicy</a>.</p>
        <p>Each monitoring account can be linked to as many as 100,000 source
        accounts.</p> <p>Each source account can be linked to as many as five
        monitoring accounts.</p>
      tags:
        - Link
  /CreateSink:
    POST:
      summary: 'Create Sink '
      description: >-
        <p>Use this to create a <i>sink</i> in the current account, so that it
        can be used as a monitoring account in CloudWatch cross-account
        observability. A sink is a resource that represents an attachment point
        in a monitoring account. Source accounts can link to the sink to send
        observability data.</p> <p>After you create a sink, you must create a
        sink policy that allows source accounts to attach to it. For more
        information, see <a
        href="https://docs.aws.amazon.com/OAM/latest/APIReference/API_PutSinkPolicy.html">PutSinkPolicy</a>.</p>
        <p>Each account can contain one sink. If you delete a sink, you can then
        create a new one in that account.</p>
      tags:
        - Sink
  /DeleteLink:
    POST:
      summary: 'Delete Link '
      description: >-
        <p>Deletes a link between a monitoring account sink and a source
        account. You must run this operation in the source account.</p>
      tags:
        - Link
  /DeleteSink:
    POST:
      summary: 'Delete Sink '
      description: >-
        <p>Deletes a sink. You must delete all links to a sink before you can
        delete that sink.</p>
      tags:
        - Sink
  /GetLink:
    POST:
      summary: 'Get Link '
      description: >-
        <p>Returns complete information about one link.</p> <p>To use this
        operation, provide the link ARN. To retrieve a list of link ARNs, use <a
        href="https://docs.aws.amazon.com/OAM/latest/APIReference/API_ListLinks.html">ListLinks</a>.</p>
      tags:
        - Link
  /GetSink:
    POST:
      summary: 'Get Sink '
      description: >-
        <p>Returns complete information about one monitoring account sink.</p>
        <p>To use this operation, provide the sink ARN. To retrieve a list of
        sink ARNs, use <a
        href="https://docs.aws.amazon.com/OAM/latest/APIReference/API_ListSinks.html">ListSinks</a>.</p>
      tags:
        - Sink
  /GetSinkPolicy:
    POST:
      summary: 'Get Sink Policy '
      description: >-
        <p>Returns the current sink policy attached to this sink. The sink
        policy specifies what accounts can attach to this sink as source
        accounts, and what types of data they can share.</p>
      tags:
        - Policies
        - Sink
  /ListAttachedLinks:
    POST:
      summary: 'List Attached Links '
      description: >-
        <p>Returns a list of source account links that are linked to this
        monitoring account sink.</p> <p>To use this operation, provide the sink
        ARN. To retrieve a list of sink ARNs, use <a
        href="https://docs.aws.amazon.com/OAM/latest/APIReference/API_ListSinks.html">ListSinks</a>.</p>
        <p>To find a list of links for one source account, use <a
        href="https://docs.aws.amazon.com/OAM/latest/APIReference/API_ListLinks.html">ListLinks</a>.</p>
      tags:
        - Attached
        - Links
  /ListLinks:
    POST:
      summary: 'List Links '
      description: >-
        <p>Use this operation in a source account to return a list of links to
        monitoring account sinks that this source account has.</p> <p>To find a
        list of links for one monitoring account sink, use <a
        href="https://docs.aws.amazon.com/OAM/latest/APIReference/API_ListAttachedLinks.html">ListAttachedLinks</a>
        from within the monitoring account.</p>
      tags:
        - Links
  /ListSinks:
    POST:
      summary: 'List Sinks '
      description: >-
        <p>Use this operation in a monitoring account to return the list of
        sinks created in that account.</p>
      tags:
        - Sinks
  /tags/{ResourceArn}:
    DELETE:
      summary: 'Untag Resource '
      description: >-
        <p>Removes one or more tags from the specified resource.</p> <important>
        <p>Unlike tagging permissions in other Amazon Web Services services, to
        tag or untag links and sinks you must have the
        <code>oam:ResourceTag</code> permission. The
        <code>iam:TagResource</code> permission does not allow you to tag and
        untag links and sinks.</p> </important>
      tags:
        - ARN
        - Resources
        - Tags
        - Untag
  /PutSinkPolicy:
    POST:
      summary: 'Put Sink Policy '
      description: >-
        <p>Creates or updates the resource policy that grants permissions to
        source accounts to link to the monitoring account sink. When you create
        a sink policy, you can grant permissions to all accounts in an
        organization or to individual accounts.</p> <p>You can also use a sink
        policy to limit the types of data that is shared. The three types that
        you can allow or deny are:</p> <ul> <li> <p> <b>Metrics</b> - Specify
        with <code>AWS::CloudWatch::Metric</code> </p> </li> <li> <p> <b>Log
        groups</b> - Specify with <code>AWS::Logs::LogGroup</code> </p> </li>
        <li> <p> <b>Traces</b> - Specify with <code>AWS::XRay::Trace</code> </p>
        </li> <li> <p> <b>Application Insights - Applications</b> - Specify with
        <code>AWS::ApplicationInsights::Application</code> </p> </li> </ul>
        <p>See the examples in this section to see how to specify permitted
        source accounts and data types.</p>
      tags:
        - Policies
        - Sink
  /UpdateLink:
    POST:
      summary: 'Update Link '
      description: >-
        <p>Use this operation to change what types of data are shared from a
        source account to its linked monitoring account sink. You can't change
        the sink or change the monitoring account with this operation.</p> <p>To
        update the list of tags associated with the sink, use <a
        href="https://docs.aws.amazon.com/OAM/latest/APIReference/API_TagResource.html">TagResourc
      tags:
        - Link
