openapi: 3.1.0
info:
  title: omics
paths:
  /sequencestore/{sequenceStoreId}/upload/{uploadId}/abort:
    DELETE:
      summary: 'Abort Multipart Read Set Upload '
      description: <p> Stops a multipart upload. </p>
      tags:
        - Abort
        - Multipart
        - Read
        - Sequence
        - Sequence Stores
        - Sets
        - Store
        - Uploads
  /share/{shareId}:
    GET:
      summary: 'Get Share '
      description: <p> Retrieves the metadata for a share. </p>
      tags:
        - Share
  /sequencestore/{sequenceStoreId}/readset/batch/delete:
    POST:
      summary: 'Batch Delete Read Set '
      description: <p>Deletes one or more read sets.</p>
      tags:
        - Batches
        - Read
        - Readsets
        - Sequence
        - Sequence Stores
        - Sets
        - Store
  /import/annotation/{jobId}:
    GET:
      summary: 'Get Annotation Import Job '
      description: <p>Gets information about an annotation import job.</p>
      tags:
        - Annotations
        - Import
        - Jobs
  /run/{id}/cancel:
    POST:
      summary: 'Cancel Run '
      description: <p>Cancels a run.</p>
      tags:
        - Cancel
        - Runs
  /import/variant/{jobId}:
    GET:
      summary: 'Get Variant Import Job '
      description: <p>Gets information about a variant import job.</p>
      tags:
        - Import
        - Jobs
        - Variants
  /sequencestore/{sequenceStoreId}/upload/{uploadId}/complete:
    POST:
      summary: 'Complete Multipart Read Set Upload '
      description: >-
        <p> Concludes a multipart upload once you have uploaded all the
        components. </p>
      tags:
        - Complete
        - Multipart
        - Read
        - Sequence
        - Sequence Stores
        - Sets
        - Store
        - Uploads
  /annotationStore:
    POST:
      summary: 'Create Annotation Store '
      description: <p>Creates an annotation store.</p>
      tags:
        - Annotations
        - Store
  /annotationStore/{name}/version:
    POST:
      summary: 'Create Annotation Store Version '
      description: <p> Creates a new version of an annotation store. </p>
      tags:
        - Annotations
        - Names
        - Store
        - Versions
  /sequencestore/{sequenceStoreId}/upload:
    POST:
      summary: 'Create Multipart Read Set Upload '
      description: <p> Begins a multipart read set upload. </p>
      tags:
        - Multipart
        - Read
        - Sequence
        - Sequence Stores
        - Sets
        - Store
        - Uploads
  /referencestore:
    POST:
      summary: 'Create Reference Store '
      description: <p>Creates a reference store.</p>
      tags:
        - Reference Store
        - References
        - Store
  /runGroup:
    GET:
      summary: 'List Run Groups '
      description: <p>Retrieves a list of run groups.</p>
      tags:
        - Groups
        - Runs
  /sequencestore:
    POST:
      summary: 'Create Sequence Store '
      description: <p>Creates a sequence store.</p>
      tags:
        - Sequence
        - Sequence Stores
        - Store
  /share:
    POST:
      summary: 'Create Share '
      description: >-
        <p> Creates a share offer that can be accepted outside the account by a
        subscriber. The share is created by the owner and accepted by the
        principal subscriber. </p>
      tags:
        - Share
  /variantStore:
    POST:
      summary: 'Create Variant Store '
      description: <p>Creates a variant store.</p>
      tags:
        - Store
        - Variants
  /workflow:
    GET:
      summary: 'List Workflows '
      description: <p>Retrieves a list of workflows.</p>
      tags:
        - Workflows
  /annotationStore/{name}:
    POST:
      summary: 'Update Annotation Store '
      description: <p>Updates an annotation store.</p>
      tags:
        - Annotations
        - Names
        - Store
  /annotationStore/{name}/versions/delete:
    POST:
      summary: 'Delete Annotation Store Versions '
      description: <p> Deletes one or multiple versions of an annotation store. </p>
      tags:
        - Annotations
        - Names
        - Store
        - Versions
  /referencestore/{referenceStoreId}/reference/{id}:
    GET:
      summary: 'Get Reference '
      description: <p>Gets a reference file.</p>
      tags:
        - Reference Store
        - References
        - Store
  /referencestore/{id}:
    GET:
      summary: 'Get Reference Store '
      description: <p>Gets information about a reference store.</p>
      tags:
        - Reference Store
        - References
        - Store
  /run/{id}:
    GET:
      summary: 'Get Run '
      description: <p>Gets information about a workflow run.</p>
      tags:
        - Runs
  /runGroup/{id}:
    POST:
      summary: 'Update Run Group '
      description: <p>Updates a run group.</p>
      tags:
        - Groups
        - Runs
  /sequencestore/{id}:
    GET:
      summary: 'Get Sequence Store '
      description: <p>Gets information about a sequence store.</p>
      tags:
        - Sequence
        - Sequence Stores
        - Store
  /variantStore/{name}:
    POST:
      summary: 'Update Variant Store '
      description: <p>Updates a variant store.</p>
      tags:
        - Names
        - Store
        - Variants
  /workflow/{id}:
    POST:
      summary: 'Update Workflow '
      description: <p>Updates a workflow.</p>
      tags:
        - Workflows
  /annotationStore/{name}/version/{versionName}:
    POST:
      summary: 'Update Annotation Store Version '
      description: <p> Updates the description of an annotation store version. </p>
      tags:
        - Annotations
        - Names
        - Store
        - Versions
  /sequencestore/{sequenceStoreId}/readset/{id}:
    GET:
      summary: 'Get Read Set '
      description: <p>Gets a file from a read set.</p>
      tags:
        - Read
        - Readsets
        - Sequence
        - Sequence Stores
        - Sets
        - Store
  /sequencestore/{sequenceStoreId}/activationjob/{id}:
    GET:
      summary: 'Get Read Set Activation Job '
      description: <p>Gets information about a read set activation job.</p>
      tags:
        - Activation
        - Activation Jobs
        - Jobs
        - Read
        - Sequence
        - Sequence Stores
        - Sets
        - Store
  /sequencestore/{sequenceStoreId}/exportjob/{id}:
    GET:
      summary: 'Get Read Set Export Job '
      description: <p>Gets information about a read set export job.</p>
      tags:
        - Export Jobs
        - Exports
        - Jobs
        - Read
        - Sequence
        - Sequence Stores
        - Sets
        - Store
  /sequencestore/{sequenceStoreId}/importjob/{id}:
    GET:
      summary: 'Get Read Set Import Job '
      description: <p>Gets information about a read set import job.</p>
      tags:
        - Import
        - Import Jobs
        - Jobs
        - Read
        - Sequence
        - Sequence Stores
        - Sets
        - Store
  /sequencestore/{sequenceStoreId}/readset/{id}/metadata:
    GET:
      summary: 'Get Read Set Metadata '
      description: <p>Gets details about a read set.</p>
      tags:
        - Metadata
        - Read
        - Readsets
        - Sequence
        - Sequence Stores
        - Sets
        - Store
  /referencestore/{referenceStoreId}/importjob/{id}:
    GET:
      summary: 'Get Reference Import Job '
      description: <p>Gets information about a reference import job.</p>
      tags:
        - Import
        - Import Jobs
        - Jobs
        - Reference Store
        - References
        - Store
  /referencestore/{referenceStoreId}/reference/{id}/metadata:
    GET:
      summary: 'Get Reference Metadata '
      description: <p>Gets information about a genome reference's metadata.</p>
      tags:
        - Metadata
        - Reference Store
        - References
        - Store
  /run/{id}/task/{taskId}:
    GET:
      summary: 'Get Run Task '
      description: <p>Gets information about a workflow run task.</p>
      tags:
        - Runs
        - Tasks
  /import/annotations:
    POST:
      summary: 'List Annotation Import Jobs '
      description: <p>Retrieves a list of annotation import jobs.</p>
      tags:
        - Annotations
        - Import
        - Jobs
  /annotationStore/{name}/versions:
    POST:
      summary: 'List Annotation Store Versions '
      description: <p> Lists the versions of an annotation store. </p>
      tags:
        - Annotations
        - Names
        - Store
        - Versions
  /annotationStores:
    POST:
      summary: 'List Annotation Stores '
      description: <p>Retrieves a list of annotation stores.</p>
      tags:
        - Annotations
        - Stores
  /sequencestore/{sequenceStoreId}/uploads:
    POST:
      summary: 'List Multipart Read Set Uploads '
      description: >-
        <p> Lists multipart read set uploads and for in progress uploads. Once
        the upload is completed, a read set is created and the upload will no
        longer be returned in the respone. </p>
      tags:
        - Multipart
        - Read
        - Sequence
        - Sequence Stores
        - Sets
        - Store
        - Uploads
  /sequencestore/{sequenceStoreId}/activationjobs:
    POST:
      summary: 'List Read Set Activation Jobs '
      description: <p>Retrieves a list of read set activation jobs.</p>
      tags:
        - Activation
        - Activation Jobs
        - Jobs
        - Read
        - Sequence
        - Sequence Stores
        - Sets
        - Store
  /sequencestore/{sequenceStoreId}/exportjobs:
    POST:
      summary: 'List Read Set Export Jobs '
      description: <p>Retrieves a list of read set export jobs.</p>
      tags:
        - Export Jobs
        - Exports
        - Jobs
        - Read
        - Sequence
        - Sequence Stores
        - Sets
        - Store
  /sequencestore/{sequenceStoreId}/importjobs:
    POST:
      summary: 'List Read Set Import Jobs '
      description: <p>Retrieves a list of read set import jobs.</p>
      tags:
        - Import
        - Import JObs
        - Jobs
        - Read
        - Sequence
        - Sequence Stores
        - Sets
        - Store
  /sequencestore/{sequenceStoreId}/upload/{uploadId}/parts:
    POST:
      summary: 'List Read Set Upload Parts '
      description: >-
        <p> This operation will list all parts in a requested multipart upload
        for a sequence store. </p>
      tags:
        - Parts
        - Read
        - Sequence
        - Sequence Stores
        - Sets
        - Store
        - Uploads
  /sequencestore/{sequenceStoreId}/readsets:
    POST:
      summary: 'List Read Sets '
      description: <p>Retrieves a list of read sets.</p>
      tags:
        - Read
        - Readsets
        - Sequence
        - Sequence Stores
        - Sets
        - Store
  /referencestore/{referenceStoreId}/importjobs:
    POST:
      summary: 'List Reference Import Jobs '
      description: <p>Retrieves a list of reference import jobs.</p>
      tags:
        - Import
        - Import JObs
        - Jobs
        - Reference Store
        - References
        - Store
  /referencestores:
    POST:
      summary: 'List Reference Stores '
      description: <p>Retrieves a list of reference stores.</p>
      tags:
        - Reference Store
        - References
        - Stores
  /referencestore/{referenceStoreId}/references:
    POST:
      summary: 'List References '
      description: <p>Retrieves a list of references.</p>
      tags:
        - Reference Store
        - References
        - Store
  /run/{id}/task:
    GET:
      summary: 'List Run Tasks '
      description: <p>Retrieves a list of tasks for a run.</p>
      tags:
        - Runs
        - Tasks
  /run:
    POST:
      summary: 'Start Run '
      description: >-
        <p>Starts a workflow run. To duplicate a run, specify the run's ID and a
        role ARN. The remaining parameters are copied from the previous run.</p>
        <p>The total number of runs in your account is subject to a quota per
        Region. To avoid needing to delete runs manually, you can set the
        retention mode to <code>REMOVE</code>. Runs with this setting are
        deleted automatically when the run quoata is exceeded.</p>
      tags:
        - Runs
  /sequencestores:
    POST:
      summary: 'List Sequence Stores '
      description: <p>Retrieves a list of sequence stores.</p>
      tags:
        - Sequence
        - Sequence Stores
        - Stores
  /shares:
    POST:
      summary: 'List Shares '
      description: <p> Lists all shares associated with an account. </p>
      tags:
        - Shares
  /tags/{resourceArn}:
    DELETE:
      summary: 'Untag Resource '
      description: <p>Removes tags from a resource.</p>
      tags:
        - ARN
        - Resources
        - Tags
        - Untag
  /import/variants:
    POST:
      summary: 'List Variant Import Jobs '
      description: <p>Retrieves a list of variant import jobs.</p>
      tags:
        - Import
        - Jobs
        - Variants
  /variantStores:
    POST:
      summary: 'List Variant Stores '
      description: <p>Retrieves a list of variant stores.</p>
      tags:
        - Stores
        - Variants
  /import/annotation:
    POST:
      summary: 'Start Annotation Import Job '
      description: <p>Starts an annotation import job.</p>
      tags:
        - Annotations
        - Import
        - Jobs
  /sequencestore/{sequenceStoreId}/activationjob:
    POST:
      summary: 'Start Read Set Activation Job '
      description: >-
        <p>Activates an archived read set. To reduce storage charges, Amazon
        Omics archives unused read sets after 30 days.</p>
      tags:
        - Activation
        - Activation Jobs
        - Jobs
        - Read
        - Sequence
        - Sequence Stores
        - Sets
        - Store
  /sequencestore/{sequenceStoreId}/exportjob:
    POST:
      summary: 'Start Read Set Export Job '
      description: <p>Exports a read set to Amazon S3.</p>
      tags:
        - Export Jobs
        - Exports
        - Jobs
        - Read
        - Sequence
        - Sequence Stores
        - Sets
        - Store
  /sequencestore/{sequenceStoreId}/importjob:
    POST:
      summary: 'Start Read Set Import Job '
      description: <p>Starts a read set import job.</p>
      tags:
        - Import
        - Import Jobs
        - Jobs
        - Read
        - Sequence
        - Sequence Stores
        - Sets
        - Store
  /referencestore/{referenceStoreId}/importjob:
    POST:
      summary: 'Start Reference Import Job '
      description: <p>Starts a reference import job.</p>
      tags:
        - Import
        - Import Jobs
        - Jobs
        - Reference Store
        - References
        - Store
  /import/variant:
    POST:
      summary: 'Start Variant Import Job '
      description: <p>Starts a variant import job.</p>
      tags:
        - Import
        - Jobs
        - Variants
  /sequencestore/{sequenceStoreId}/upload/{uploadId}/part:
    PUT:
      summary: 'Upload Read Set Part '
      description: >-
        <p> This operation uploads a specific part of a read set. If you upload
        a new part using a previously used part number, the previously uploaded
        part will be overwri
      tags:
        - Read
        - Sequence
        - Sequence Stores
        - Sets
        - Store
        - Uploads
