openapi: 3.1.0
info:
  title: osis
paths:
  /2022-01-01/osis/createPipeline:
    POST:
      summary: 'Create Pipeline '
      description: >-
        <p>Creates an OpenSearch Ingestion pipeline. For more information, see
        <a
        href="https://docs.aws.amazon.com/opensearch-service/latest/developerguide/creating-pipeline.html">Creating
        Amazon OpenSearch Ingestion pipelines</a>.</p>
      tags:
        - '2022'
        - Osis
        - Pipelines
  /2022-01-01/osis/deletePipeline/{PipelineName}:
    DELETE:
      summary: 'Delete Pipeline '
      description: >-
        <p>Deletes an OpenSearch Ingestion pipeline. For more information, see
        <a
        href="https://docs.aws.amazon.com/opensearch-service/latest/developerguide/delete-pipeline.html">Deleting
        Amazon OpenSearch Ingestion pipelines</a>.</p>
      tags:
        - '2022'
        - Names
        - Osis
        - Pipelines
  /2022-01-01/osis/getPipeline/{PipelineName}:
    GET:
      summary: 'Get Pipeline '
      description: <p>Retrieves information about an OpenSearch Ingestion pipeline.</p>
      tags:
        - '2022'
        - Names
        - Osis
        - Pipelines
  /2022-01-01/osis/getPipelineBlueprint/{BlueprintName}:
    GET:
      summary: 'Get Pipeline Blueprint '
      description: >-
        <p>Retrieves information about a specific blueprint for OpenSearch
        Ingestion. Blueprints are templates for the configuration needed for a
        <code>CreatePipeline</code> request. For more information, see <a
        href="https://docs.aws.amazon.com/opensearch-service/latest/developerguide/creating-pipeline.html#pipeline-blueprint">Using
        blueprints to create a pipeline</a>.</p>
      tags:
        - '2022'
        - Blueprints
        - Names
        - Osis
        - Pipelines
  /2022-01-01/osis/getPipelineChangeProgress/{PipelineName}:
    GET:
      summary: 'Get Pipeline Change Progress '
      description: >-
        <p>Returns progress information for the current change happening on an
        OpenSearch Ingestion pipeline. Currently, this operation only returns
        information when a pipeline is being created.</p> <p>For more
        information, see <a
        href="https://docs.aws.amazon.com/opensearch-service/latest/developerguide/creating-pipeline.html#get-pipeline-progress">Tracking
        the status of pipeline creation</a>.</p>
      tags:
        - '2022'
        - Change
        - Names
        - Osis
        - Pipelines
        - Progress
  /2022-01-01/osis/listPipelineBlueprints:
    POST:
      summary: 'List Pipeline Blueprints '
      description: >-
        <p>Retrieves a list of all available blueprints for Data Prepper. For
        more information, see <a
        href="https://docs.aws.amazon.com/opensearch-service/latest/developerguide/creating-pipeline.html#pipeline-blueprint">Using
        blueprints to create a pipeline</a>.</p>
      tags:
        - '2022'
        - Blueprints
        - Osis
        - Pipelines
  /2022-01-01/osis/listPipelines:
    GET:
      summary: 'List Pipelines '
      description: >-
        <p>Lists all OpenSearch Ingestion pipelines in the current Amazon Web
        Services account and Region. For more information, see <a
        href="https://docs.aws.amazon.com/opensearch-service/latest/developerguide/list-pipeline.html">Viewing
        Amazon OpenSearch Ingestion pipelines</a>.</p>
      tags:
        - '2022'
        - Osis
        - Pipelines
  /2022-01-01/osis/listTagsForResource/:
    GET:
      summary: 'List Tags For Resource '
      description: >-
        <p>Lists all resource tags associated with an OpenSearch Ingestion
        pipeline. For more information, see <a
        href="https://docs.aws.amazon.com/opensearch-service/latest/developerguide/tag-pipeline.html">Tagging
        Amazon OpenSearch Ingestion pipelines</a>.</p>
      tags:
        - '2022'
        - Osis
        - Resources
        - Tags
  /2022-01-01/osis/startPipeline/{PipelineName}:
    PUT:
      summary: 'Start Pipeline '
      description: >-
        <p>Starts an OpenSearch Ingestion pipeline. For more information, see <a
        href="https://docs.aws.amazon.com/opensearch-service/latest/developerguide/pipeline--stop-start.html#pipeline--start">Starting
        an OpenSearch Ingestion pipeline</a>.</p>
      tags:
        - '2022'
        - Names
        - Osis
        - Pipelines
  /2022-01-01/osis/stopPipeline/{PipelineName}:
    PUT:
      summary: 'Stop Pipeline '
      description: >-
        <p>Stops an OpenSearch Ingestion pipeline. For more information, see <a
        href="https://docs.aws.amazon.com/opensearch-service/latest/developerguide/pipeline--stop-start.html#pipeline--stop">Stopping
        an OpenSearch Ingestion pipeline</a>.</p>
      tags:
        - '2022'
        - Names
        - Osis
        - Pipelines
        - Stop
  /2022-01-01/osis/tagResource/:
    POST:
      summary: 'Tag Resource '
      description: >-
        <p>Tags an OpenSearch Ingestion pipeline. For more information, see <a
        href="https://docs.aws.amazon.com/opensearch-service/latest/developerguide/tag-pipeline.html">Tagging
        Amazon OpenSearch Ingestion pipelines</a>.</p>
      tags:
        - '2022'
        - Osis
        - Resources
        - Tags
  /2022-01-01/osis/untagResource/:
    POST:
      summary: 'Untag Resource '
      description: >-
        <p>Removes one or more tags from an OpenSearch Ingestion pipeline. For
        more information, see <a
        href="https://docs.aws.amazon.com/opensearch-service/latest/developerguide/tag-pipeline.html">Tagging
        Amazon OpenSearch Ingestion pipelines</a>.</p>
      tags:
        - '2022'
        - Osis
        - Resources
        - Untag
  /2022-01-01/osis/updatePipeline/{PipelineName}:
    PUT:
      summary: 'Update Pipeline '
      description: >-
        <p>Updates an OpenSearch Ingestion pipeline. For more information, see
        <a
        href="https://docs.aws.amazon.com/opensearch-service/latest/developerguide/update-pipeline.html">Updating
        Amazon OpenSearch Ingestion pipelines</a>.</p>
      tags:
        - '2022'
        - Names
        - Osis
        - Pipelines
  /2022-01-01/osis/validatePipeline:
    POST:
      summary: 'Validate Pipeline '
      description: >-
        <p>Checks whether an OpenSearch Ingestion pipeline configuration is
        valid prior to creation. For more information, see <a
        href="https://docs.aws.amazon.com/opensearch-service/latest/developerguide/creating-pipeline.html">Creating
        Amazon OpenSearch Ingestion pipeline
      tags:
        - '2022'
        - Ate
        - Osis
        - Pipelines
        - Val
        - Validate
