openapi: 3.1.0
info:
  title: outposts
paths:
  /orders/{OrderId}/cancel:
    POST:
      summary: 'Cancel Order '
      description: <p>Cancels the specified order for an Outpost.</p>
      tags:
        - Cancel
        - Orders
  /orders:
    POST:
      summary: 'Create Order '
      description: <p>Creates an order for an Outpost.</p>
      tags:
        - Orders
  /outposts:
    GET:
      summary: 'List Outposts '
      description: >-
        <p>Lists the Outposts for your Amazon Web Services account.</p> <p>Use
        filters to return specific results. If you specify multiple filters, the
        results include only the resources that match all of the specified
        filters. For a filter where you can specify multiple values, the results
        include items that match any of the values that you specify for the
        filter.</p>
      tags:
        - Outposts
  /sites:
    GET:
      summary: 'List Sites '
      description: >-
        <p>Lists the Outpost sites for your Amazon Web Services account. Use
        filters to return specific results.</p> <p>Use filters to return
        specific results. If you specify multiple filters, the results include
        only the resources that match all of the specified filters. For a filter
        where you can specify multiple values, the results include items that
        match any of the values that you specify for the filter.</p>
      tags:
        - Sites
  /outposts/{OutpostId}:
    PATCH:
      summary: 'Update Outpost '
      description: <p> Updates an Outpost. </p>
      tags:
        - Outposts
  /sites/{SiteId}:
    PATCH:
      summary: 'Update Site '
      description: <p>Updates the specified site.</p>
      tags:
        - Sites
  /catalog/item/{CatalogItemId}:
    GET:
      summary: 'Get Catalog Item '
      description: <p>Gets information about the specified catalog item.</p>
      tags:
        - Catalog
        - Items
  /connections/{ConnectionId}:
    GET:
      summary: 'Get Connection '
      description: >-
        <note> <p> Amazon Web Services uses this action to install Outpost
        servers.</p> </note> <p> Gets information about the specified
        connection. </p> <p> Use CloudTrail to monitor this action or Amazon Web
        Services managed policy for Amazon Web Services Outposts to secure it.
        For more information, see <a
        href="https://docs.aws.amazon.com/outposts/latest/userguide/security-iam-awsmanpol.html">
        Amazon Web Services managed policies for Amazon Web Services
        Outposts</a> and <a
        href="https://docs.aws.amazon.com/outposts/latest/userguide/logging-using-cloudtrail.html">
        Logging Amazon Web Services Outposts API calls with Amazon Web Services
        CloudTrail</a> in the <i>Amazon Web Services Outposts User Guide</i>.
        </p>
      tags:
        - Connections
  /orders/{OrderId}:
    GET:
      summary: 'Get Order '
      description: <p>Gets information about the specified order.</p>
      tags:
        - Orders
  /outposts/{OutpostId}/instanceTypes:
    GET:
      summary: 'Get Outpost Instance Types '
      description: <p>Gets the instance types for the specified Outpost.</p>
      tags:
        - Instances
        - Outposts
        - Types
  /sites/{SiteId}/address:
    PUT:
      summary: 'Update Site Address '
      description: >-
        <p>Updates the address of the specified site.</p> <p>You can't update a
        site address if there is an order in progress. You must wait for the
        order to complete or cancel the order.</p> <p>You can update the
        operating address before you place an order at the site, or after all
        Outposts that belong to the site have been deactivated.</p>
      tags:
        - Addresses
        - Sites
  /outposts/{OutpostId}/assets:
    GET:
      summary: 'List Assets '
      description: >-
        <p>Lists the hardware assets for the specified Outpost.</p> <p>Use
        filters to return specific results. If you specify multiple filters, the
        results include only the resources that match all of the specified
        filters. For a filter where you can specify multiple values, the results
        include items that match any of the values that you specify for the
        filter.</p>
      tags:
        - Assets
        - Outposts
  /catalog/items:
    GET:
      summary: 'List Catalog Items '
      description: >-
        <p>Lists the items in the catalog.</p> <p>Use filters to return specific
        results. If you specify multiple filters, the results include only the
        resources that match all of the specified filters. For a filter where
        you can specify multiple values, the results include items that match
        any of the values that you specify for the filter.</p>
      tags:
        - Catalog
        - Items
  /list-orders:
    GET:
      summary: 'List Orders '
      description: <p>Lists the Outpost orders for your Amazon Web Services account.</p>
      tags:
        - Orders
  /tags/{ResourceArn}:
    DELETE:
      summary: 'Untag Resource '
      description: <p>Removes tags from the specified resource.</p>
      tags:
        - ARN
        - Resources
        - Tags
        - Untag
  /connections:
    POST:
      summary: 'Start Connection '
      description: >-
        <note> <p> Amazon Web Services uses this action to install Outpost
        servers.</p> </note> <p> Starts the connection required for Outpost
        server installation. </p> <p> Use CloudTrail to monitor this action or
        Amazon Web Services managed policy for Amazon Web Services Outposts to
        secure it. For more information, see <a
        href="https://docs.aws.amazon.com/outposts/latest/userguide/security-iam-awsmanpol.html">
        Amazon Web Services managed policies for Amazon Web Services
        Outposts</a> and <a
        href="https://docs.aws.amazon.com/outposts/latest/userguide/logging-using-cloudtrail.html">
        Logging Amazon Web Services Outposts API calls with Amazon Web Services
        CloudTrail</a> in the <i>Amazon Web Services Outposts User Guide</i>.
        </p>
      tags:
        - Connections
  /sites/{SiteId}/rackPhysicalProperties:
    PATCH:
      summary: 'Update Site Rack Physical Properties '
      description: >-
        <p>Update the physical and logistical details for a rack at a site. For
        more information about hardware requirements for racks, see <a
        href="https://docs.aws.amazon.com/outposts/latest/userguide/outposts-requirements.html#checklist">Network
        readiness checklist</a> in the Amazon Web Services Outposts User Guide.
        </p> <p>To update a rack at a site with an order of
        <code>IN_PROGRESS</code>, you must wait for the order to complete or
        cancel the 
      tags:
        - Physical
        - Properties
        - Rack
        - Sites
