openapi: 3.1.0
info:
  title: panorama
paths:
  /application-instances:
    GET:
      summary: 'List Application Instances '
      description: <p>Returns a list of application instances.</p>
      tags:
        - Applications
        - Instances
  /jobs:
    GET:
      summary: 'List Devices Jobs '
      description: <p>Returns a list of jobs.</p>
      tags:
        - Devices
        - Jobs
  /packages/template-job:
    GET:
      summary: 'List Node From Template Jobs '
      description: <p>Returns a list of camera stream node jobs.</p>
      tags:
        - Jobs
        - Nodes
        - Packages
        - Templates
  /packages:
    GET:
      summary: 'List Packages '
      description: <p>Returns a list of packages.</p>
      tags:
        - Packages
  /packages/import-jobs:
    GET:
      summary: 'List Package Import Jobs '
      description: <p>Returns a list of package import jobs.</p>
      tags:
        - Import
        - Jobs
        - Packages
  /devices/{DeviceId}:
    PUT:
      summary: 'Update Device Metadata '
      description: <p>Updates a device's metadata.</p>
      tags:
        - Device
        - Devices
        - Metadata
  /packages/{PackageId}:
    DELETE:
      summary: 'Delete Package '
      description: >-
        <p>Deletes a package.</p> <note> <p>To delete a package, you need
        permission to call <code>s3:DeleteObject</code> in addition to
        permissions for the AWS Panorama API.</p> </note>
      tags:
        - Packages
  /packages/{PackageId}/versions/{PackageVersion}/patch/{PatchVersion}:
    PUT:
      summary: 'Register Package Version '
      description: <p>Registers a package version.</p>
      tags:
        - Packages
        - Patch
        - Register
        - Versions
  /application-instances/{ApplicationInstanceId}:
    DELETE:
      summary: 'Remove Application Instance '
      description: <p>Removes an application instance.</p>
      tags:
        - Applications
        - Instances
        - Removes
  /application-instances/{ApplicationInstanceId}/details:
    GET:
      summary: 'Describe Application Instance Details '
      description: >-
        <p>Returns information about an application instance's configuration
        manifest.</p>
      tags:
        - Applications
        - Describe
        - Details
        - Instances
  /jobs/{JobId}:
    GET:
      summary: 'Describe Device Job '
      description: <p>Returns information about a device job.</p>
      tags:
        - Describe
        - Device
        - Jobs
  /nodes/{NodeId}:
    GET:
      summary: 'Describe Node '
      description: <p>Returns information about a node.</p>
      tags:
        - Describe
        - Nodes
  /packages/template-job/{JobId}:
    GET:
      summary: 'Describe Node From Template Job '
      description: <p>Returns information about a job to create a camera stream node.</p>
      tags:
        - Describe
        - Jobs
        - Nodes
        - Packages
        - Templates
  /packages/metadata/{PackageId}:
    GET:
      summary: 'Describe Package '
      description: <p>Returns information about a package.</p>
      tags:
        - Describe
        - Metadata
        - Packages
  /packages/import-jobs/{JobId}:
    GET:
      summary: 'Describe Package Import Job '
      description: <p>Returns information about a package import job.</p>
      tags:
        - Describe
        - Import
        - Jobs
        - Packages
  /packages/metadata/{PackageId}/versions/{PackageVersion}:
    GET:
      summary: 'Describe Package Version '
      description: <p>Returns information about a package version.</p>
      tags:
        - Describe
        - Metadata
        - Packages
        - Versions
  /application-instances/{ApplicationInstanceId}/package-dependencies:
    GET:
      summary: 'List Application Instance Dependencies '
      description: <p>Returns a list of application instance dependencies.</p>
      tags:
        - Applications
        - Dependencies
        - Instances
        - Packages
  /application-instances/{ApplicationInstanceId}/node-instances:
    GET:
      summary: 'List Application Instance Node Instances '
      description: <p>Returns a list of application node instances.</p>
      tags:
        - Applications
        - Instances
        - Nodes
  /devices:
    POST:
      summary: 'Provision Device '
      description: >-
        <p>Creates a device and returns a configuration archive. The
        configuration archive is a ZIP file that contains a provisioning
        certificate that is valid for 5 minutes. Name the configuration archive
        <code>certificates-omni_<i>device-name</i>.zip</code> and transfer it to
        the device within 5 minutes. Use the included USB storage device and
        connect it to the USB 3.0 port next to the HDMI output.</p>
      tags:
        - Device
        - Devices
        - Provision
  /nodes:
    GET:
      summary: 'List Nodes '
      description: <p>Returns a list of nodes.</p>
      tags:
        - Nodes
  /tags/{ResourceArn}:
    DELETE:
      summary: 'Untag Resource '
      description: <p>Removes tags from a resource.</p>
      tags:
        - ARN
        - Resources
        - Tags
        - Untag
  /application-instances/{ApplicationInstanceId}/node-signals:
    PUT:
      summary: 'Signal Application Instance Node Instances '
      description: <p>Signal camera nodes to stop or r
      tags:
        - Applications
        - Instances
        - Nodes
        - Signals
