openapi: 3.1.0
info:
  title: pi
paths:
  /:
    POST:
      summary: 'Untag Resource '
      description: >-
        <p>Deletes the metadata tags from the Amazon RDS Performance Insights
        res
      tags:
        - Resources
        - Untag
