openapi: 3.1.0
info:
  title: pinpoint-email
paths:
  /v1/email/configuration-sets:
    GET:
      summary: 'List Configuration Sets '
      description: >-
        <p>List all of the configuration sets associated with your Amazon
        Pinpoint account in the current region.</p> <p>In Amazon Pinpoint,
        <i>configuration sets</i> are groups of rules that you can apply to the
        emails you send. You apply a configuration set to an email by including
        a reference to the configuration set in the headers of the email. When
        you apply a configuration set to an email, all of the rules in that
        configuration set are applied to the email.</p>
      tags:
        - Configurations
        - Emails
        - Sets
  /v1/email/configuration-sets/{ConfigurationSetName}/event-destinations:
    GET:
      summary: 'Get Configuration Set Event Destinations '
      description: >-
        <p>Retrieve a list of event destinations that are associated with a
        configuration set.</p> <p>In Amazon Pinpoint, <i>events</i> include
        message sends, deliveries, opens, clicks, bounces, and complaints.
        <i>Event destinations</i> are places that you can send information about
        these events to. For example, you can send event data to Amazon SNS to
        receive notifications when you receive bounces or complaints, or you can
        use Amazon Kinesis Data Firehose to stream data to Amazon S3 for
        long-term storage.</p>
      tags:
        - Configurations
        - Destinations
        - Emails
        - Events
        - Names
        - Sets
  /v1/email/dedicated-ip-pools:
    GET:
      summary: 'List Dedicated Ip Pools '
      description: >-
        <p>List all of the dedicated IP pools that exist in your Amazon Pinpoint
        account in the current AWS Region.</p>
      tags:
        - Dedicated
        - Emails
        - IP
        - Pools
  /v1/email/deliverability-dashboard/test:
    POST:
      summary: 'Create Deliverability Test Report '
      description: >-
        <p>Create a new predictive inbox placement test. Predictive inbox
        placement tests can help you predict how your messages will be handled
        by various email providers around the world. When you perform a
        predictive inbox placement test, you provide a sample message that
        contains the content that you plan to send to your customers. Amazon
        Pinpoint then sends that message to special email addresses spread
        across several major email providers. After about 24 hours, the test is
        complete, and you can use the <code>GetDeliverabilityTestReport</code>
        operation to view the results of the test.</p>
      tags:
        - Dashboard
        - Deliverability
        - Emails
        - Reports
        - Tests
  /v1/email/identities:
    GET:
      summary: 'List Email Identities '
      description: >-
        <p>Returns a list of all of the email identities that are associated
        with your Amazon Pinpoint account. An identity can be either an email
        address or a domain. This operation returns identities that are verified
        as well as those that aren't.</p>
      tags:
        - Emails
        - Entities
        - Identities
  /v1/email/configuration-sets/{ConfigurationSetName}:
    GET:
      summary: 'Get Configuration Set '
      description: >-
        <p>Get information about an existing configuration set, including the
        dedicated IP pool that it's associated with, whether or not it's enabled
        for sending email, and more.</p> <p>In Amazon Pinpoint, <i>configuration
        sets</i> are groups of rules that you can apply to the emails you send.
        You apply a configuration set to an email by including a reference to
        the configuration set in the headers of the email. When you apply a
        configuration set to an email, all of the rules in that configuration
        set are applied to the email.</p>
      tags:
        - Configurations
        - Emails
        - Names
        - Sets
  /v1/email/configuration-sets/{ConfigurationSetName}/event-destinations/{EventDestinationName}:
    PUT:
      summary: 'Update Configuration Set Event Destination '
      description: >-
        <p>Update the configuration of an event destination for a configuration
        set.</p> <p>In Amazon Pinpoint, <i>events</i> include message sends,
        deliveries, opens, clicks, bounces, and complaints. <i>Event
        destinations</i> are places that you can send information about these
        events to. For example, you can send event data to Amazon SNS to receive
        notifications when you receive bounces or complaints, or you can use
        Amazon Kinesis Data Firehose to stream data to Amazon S3 for long-term
        storage.</p>
      tags:
        - Configurations
        - Destinations
        - Emails
        - Events
        - Names
        - Sets
  /v1/email/dedicated-ip-pools/{PoolName}:
    DELETE:
      summary: 'Delete Dedicated Ip Pool '
      description: <p>Delete a dedicated IP pool.</p>
      tags:
        - Dedicated
        - Emails
        - IP
        - Names
        - Pools
  /v1/email/identities/{EmailIdentity}:
    GET:
      summary: 'Get Email Identity '
      description: >-
        <p>Provides information about a specific identity associated with your
        Amazon Pinpoint account, including the identity's verification status,
        its DKIM authentication status, and its custom Mail-From settings.</p>
      tags:
        - Emails
        - Entities
        - Identity
  /v1/email/account:
    GET:
      summary: 'Get Account '
      description: >-
        <p>Obtain information about the email-sending status and capabilities of
        your Amazon Pinpoint account in the current AWS Region.</p>
      tags:
        - Accounts
        - Emails
  /v1/email/deliverability-dashboard/blacklist-report:
    GET:
      summary: 'Get Blacklist Reports '
      description: >-
        <p>Retrieve a list of the blacklists that your dedicated IP addresses
        appear on.</p>
      tags:
        - Blacklist
        - Dashboard
        - Deliverability
        - Emails
        - Reports
  /v1/email/dedicated-ips/{IP}:
    GET:
      summary: 'Get Dedicated Ip '
      description: >-
        <p>Get information about a dedicated IP address, including the name of
        the dedicated IP pool that it's associated with, as well information
        about the automatic warm-up process for the address.</p>
      tags:
        - Dedicated
        - Emails
        - IP
        - IP Addresses
  /v1/email/dedicated-ips:
    GET:
      summary: 'Get Dedicated Ips '
      description: >-
        <p>List the dedicated IP addresses that are associated with your Amazon
        Pinpoint account.</p>
      tags:
        - Dedicated
        - Emails
        - IP Addresses
  /v1/email/deliverability-dashboard:
    PUT:
      summary: 'Put Deliverability Dashboard Option '
      description: >-
        <p>Enable or disable the Deliverability dashboard for your Amazon
        Pinpoint account. When you enable the Deliverability dashboard, you gain
        access to reputation, deliverability, and other metrics for the domains
        that you use to send email using Amazon Pinpoint. You also gain the
        ability to perform predictive inbox placement tests.</p> <p>When you use
        the Deliverability dashboard, you pay a monthly subscription charge, in
        addition to any other fees that you accrue by using Amazon Pinpoint. For
        more information about the features and cost of a Deliverability
        dashboard subscription, see <a
        href="http://aws.amazon.com/pinpoint/pricing/">Amazon Pinpoint
        Pricing</a>.</p>
      tags:
        - Dashboard
        - Deliverability
        - Emails
        - Options
  /v1/email/deliverability-dashboard/test-reports/{ReportId}:
    GET:
      summary: 'Get Deliverability Test Report '
      description: <p>Retrieve the results of a predictive inbox placement test.</p>
      tags:
        - Dashboard
        - Deliverability
        - Emails
        - Reports
        - Tests
  /v1/email/deliverability-dashboard/campaigns/{CampaignId}:
    GET:
      summary: 'Get Domain Deliverability Campaign '
      description: >-
        <p>Retrieve all the deliverability data for a specific campaign. This
        data is available for a campaign only if the campaign sent email by
        using a domain that the Deliverability dashboard is enabled for
        (<code>PutDeliverabilityDashboardOption</code> operation).</p>
      tags:
        - Campaigns
        - Dashboard
        - Deliverability
        - Domains
        - Emails
  /v1/email/deliverability-dashboard/statistics-report/{Domain}:
    GET:
      summary: 'Get Domain Statistics Report '
      description: >-
        <p>Retrieve inbox placement and engagement rates for the domains that
        you use to send email.</p>
      tags:
        - Dashboard
        - Deliverability
        - Domains
        - Emails
        - Reports
        - Statistics
  /v1/email/deliverability-dashboard/test-reports:
    GET:
      summary: 'List Deliverability Test Reports '
      description: >-
        <p>Show a list of the predictive inbox placement tests that you've
        performed, regardless of their statuses. For predictive inbox placement
        tests that are complete, you can use the
        <code>GetDeliverabilityTestReport</code> operation to view the
        results.</p>
      tags:
        - Dashboard
        - Deliverability
        - Emails
        - Reports
        - Tests
  /v1/email/deliverability-dashboard/domains/{SubscribedDomain}/campaigns:
    GET:
      summary: 'List Domain Deliverability Campaigns '
      description: >-
        <p>Retrieve deliverability data for all the campaigns that used a
        specific domain to send email during a specified time range. This data
        is available for a domain only if you enabled the Deliverability
        dashboard (<code>PutDeliverabilityDashboardOption</code> operation) for
        the domain.</p>
      tags:
        - Campaigns
        - Dashboard
        - Deliverability
        - Domains
        - Emails
        - Subscribed
  /v1/email/tags:
    DELETE:
      summary: 'Untag Resource '
      description: >-
        <p>Remove one or more tags (keys and values) from a specified
        resource.</p>
      tags:
        - Emails
        - Resources
        - Tags
        - Untag
  /v1/email/account/dedicated-ips/warmup:
    PUT:
      summary: 'Put Account Dedicated Ip Warmup Attributes '
      description: >-
        <p>Enable or disable the automatic warm-up feature for dedicated IP
        addresses.</p>
      tags:
        - Accounts
        - Attributes
        - Dedicated
        - Emails
        - IP
        - IP Addresses
        - Warmup
  /v1/email/account/sending:
    PUT:
      summary: 'Put Account Sending Attributes '
      description: <p>Enable or disable the ability of your account to send email.</p>
      tags:
        - Accounts
        - Attributes
        - Emails
        - Sending
  /v1/email/configuration-sets/{ConfigurationSetName}/delivery-options:
    PUT:
      summary: 'Put Configuration Set Delivery Options '
      description: >-
        <p>Associate a configuration set with a dedicated IP pool. You can use
        dedicated IP pools to create groups of dedicated IP addresses for
        sending specific types of email.</p>
      tags:
        - Configurations
        - Deliveries
        - Emails
        - Names
        - Options
        - Sets
  /v1/email/configuration-sets/{ConfigurationSetName}/reputation-options:
    PUT:
      summary: 'Put Configuration Set Reputation Options '
      description: >-
        <p>Enable or disable collection of reputation metrics for emails that
        you send using a particular configuration set in a specific AWS
        Region.</p>
      tags:
        - Configurations
        - Emails
        - Names
        - Options
        - Reputation
        - Sets
  /v1/email/configuration-sets/{ConfigurationSetName}/sending:
    PUT:
      summary: 'Put Configuration Set Sending Options '
      description: >-
        <p>Enable or disable email sending for messages that use a particular
        configuration set in a specific AWS Region.</p>
      tags:
        - Configurations
        - Emails
        - Names
        - Options
        - Sending
        - Sets
  /v1/email/configuration-sets/{ConfigurationSetName}/tracking-options:
    PUT:
      summary: 'Put Configuration Set Tracking Options '
      description: >-
        <p>Specify a custom domain to use for open and click tracking elements
        in email that you send using Amazon Pinpoint.</p>
      tags:
        - Configurations
        - Emails
        - Names
        - Options
        - Sets
        - Tracking
  /v1/email/dedicated-ips/{IP}/pool:
    PUT:
      summary: 'Put Dedicated Ip In Pool '
      description: >-
        <p>Move a dedicated IP address to an existing dedicated IP pool.</p>
        <note> <p>The dedicated IP address that you specify must already exist,
        and must be associated with your Amazon Pinpoint account. </p> <p>The
        dedicated IP pool you specify must already exist. You can create a new
        pool by using the <code>CreateDedicatedIpPool</code> operation.</p>
        </note>
      tags:
        - Dedicated
        - Emails
        - IP
        - IP Addresses
        - Pools
  /v1/email/dedicated-ips/{IP}/warmup:
    PUT:
      summary: 'Put Dedicated Ip Warmup Attributes '
      description: <p/>
      tags:
        - Attributes
        - Dedicated
        - Emails
        - IP
        - IP Addresses
        - Warmup
  /v1/email/identities/{EmailIdentity}/dkim:
    PUT:
      summary: 'Put Email Identity Dkim Attributes '
      description: >-
        <p>Used to enable or disable DKIM authentication for an email
        identity.</p>
      tags:
        - Attributes
        - DKIM
        - Emails
        - Entities
        - Identity
  /v1/email/identities/{EmailIdentity}/feedback:
    PUT:
      summary: 'Put Email Identity Feedback Attributes '
      description: >-
        <p>Used to enable or disable feedback forwarding for an identity. This
        setting determines what happens when an identity is used to send an
        email that results in a bounce or complaint event.</p> <p>When you
        enable feedback forwarding, Amazon Pinpoint sends you email
        notifications when bounce or complaint events occur. Amazon Pinpoint
        sends this notification to the address that you specified in the
        Return-Path header of the original email.</p> <p>When you disable
        feedback forwarding, Amazon Pinpoint sends notifications through other
        mechanisms, such as by notifying an Amazon SNS topic. You're required to
        have a method of tracking bounces and complaints. If you haven't set up
        another mechanism for receiving bounce or complaint notifications,
        Amazon Pinpoint sends an email notification when these events occur
        (even if this setting is disabled).</p>
      tags:
        - Attributes
        - Emails
        - Entities
        - Feedback
        - Identity
  /v1/email/identities/{EmailIdentity}/mail-from:
    PUT:
      summary: 'Put Email Identity Mail From Attributes '
      description: >-
        <p>Used to enable or disable the custom Mail-From domain configuration
        for an email identity.</p>
      tags:
        - Attributes
        - Emails
        - Entities
        - Identity
        - Mail
  /v1/email/outbound-emails:
    POST:
      summary: 'Send Email '
      description: >-
        <p>Sends an email message. You can use the Amazon Pinpoint Email API to
        send two types of messages:</p> <ul> <li> <p> <b>Simple</b> – A standard
        email message. When you create this type of message, you specify the
        sender, the recipient, and the message body, and Amazon Pinpoint
        assembles the message for you.</p> </li> <li> <p> <b>Raw</b> – A raw,
        MIME-formatted email message. When you send this type of email, you have
        to specify all of the message headers, as well as the message body. You
        can use this message type to send messages that contain attachments. The
        message that you specify has to be a valid MIME message.</p> <
      tags:
        - Emails
        - Outbound
        - Send
