openapi: 3.1.0
info:
  title: pinpoint-sms-voice-v2
paths:
  /:
    POST:
      summary: 'Verify Destination Number '
      description: >-
        <p>Use the verification code that was received by the verified
        destination phone number to opt-in the verified destination phone number
        to receive more mes
      tags:
        - Destinations
        - Numbers
        - Verify
