openapi: 3.1.0
info:
  title: pipes
paths:
  /v1/pipes/{Name}:
    PUT:
      summary: 'Update Pipe '
      description: >-
        <p>Update an existing pipe. When you call <code>UpdatePipe</code>,
        EventBridge only the updates fields you have specified in the request;
        the rest remain unchanged. The exception to this is if you modify any
        Amazon Web Services-service specific fields in the
        <code>SourceParameters</code>, <code>EnrichmentParameters</code>, or
        <code>TargetParameters</code> objects. For example,
        <code>DynamoDBStreamParameters</code> or
        <code>EventBridgeEventBusParameters</code>. EventBridge updates the
        fields in these objects atomically as one and overrides existing values.
        This is by design, and means that if you don't specify an optional field
        in one of these <code>Parameters</code> objects, EventBridge sets that
        field to its system-default value during the update.</p> <p>For more
        information about pipes, see <a
        href="https://docs.aws.amazon.com/eventbridge/latest/userguide/eb-pipes.html">
        Amazon EventBridge Pipes</a> in the Amazon EventBridge User Guide.</p>
      tags:
        - Names
        - Pipe
        - Pipes
  /v1/pipes:
    GET:
      summary: 'List Pipes '
      description: >-
        <p>Get the pipes associated with this account. For more information
        about pipes, see <a
        href="https://docs.aws.amazon.com/eventbridge/latest/userguide/eb-pipes.html">Amazon
        EventBridge Pipes</a> in the Amazon EventBridge User Guide.</p>
      tags:
        - Pipes
  /tags/{resourceArn}:
    DELETE:
      summary: 'Untag Resource '
      description: <p>Removes one or more tags from the specified pipes.</p>
      tags:
        - ARN
        - Resources
        - Tags
        - Untag
  /v1/pipes/{Name}/start:
    POST:
      summary: 'Start Pipe '
      description: <p>Start an existing pipe.</p>
      tags:
        - Names
        - Pipe
        - Pipes
  /v1/pipes/{Name}/stop:
    POST:
      summary: 'Stop Pipe '
      description: <p>Stop an existing
      tags:
        - Names
        - Pipe
        - Pipes
        - Stop
