openapi: 3.1.0
info:
  title: privatenetworks
paths:
  /v1/orders/acknowledge:
    POST:
      summary: 'Acknowledge Order Receipt '
      description: <p>Acknowledges that the specified network order was received.</p>
      tags:
        - Acknowledge
        - Orders
        - Receipts
  /v1/device-identifiers/activate:
    POST:
      summary: 'Activate Device Identifier '
      description: <p>Activates the specified device identifier.</p>
      tags:
        - Activate
        - Device
        - Entifiers
  /v1/network-sites/activate:
    POST:
      summary: 'Activate Network Site '
      description: <p>Activates the specified network site.</p>
      tags:
        - Activate
        - Networks
        - Sites
  /v1/network-resources/configure:
    POST:
      summary: 'Configure Access Point '
      description: >-
        <p>Configures the specified network resource. </p> <p> Use this action
        to specify the geographic position of the hardware. You must provide
        Certified Professional Installer (CPI) credentials in the request so
        that we can obtain spectrum grants. For more information, see <a
        href="https://docs.aws.amazon.com/private-networks/latest/userguide/radio-units.html">Radio
        units</a> in the <i>Amazon Web Services Private 5G User Guide</i>. </p>
      tags:
        - Access
        - Configure
        - Networks
        - Points
        - Resources
  /v1/networks:
    POST:
      summary: 'Create Network '
      description: <p>Creates a network.</p>
      tags:
        - Networks
  /v1/network-sites:
    POST:
      summary: 'Create Network Site '
      description: <p>Creates a network site.</p>
      tags:
        - Networks
        - Sites
  /v1/device-identifiers/deactivate:
    POST:
      summary: 'Deactivate Device Identifier '
      description: <p>Deactivates the specified device identifier.</p>
      tags:
        - Deactivate
        - Device
        - Entifiers
  /v1/networks/{networkArn}:
    GET:
      summary: 'Get Network '
      description: <p>Gets the specified network.</p>
      tags:
        - ARN
        - Networks
  /v1/network-sites/{networkSiteArn}:
    GET:
      summary: 'Get Network Site '
      description: <p>Gets the specified network site.</p>
      tags:
        - ARN
        - Networks
        - Sites
  /v1/device-identifiers/{deviceIdentifierArn}:
    GET:
      summary: 'Get Device Identifier '
      description: <p>Gets the specified device identifier.</p>
      tags:
        - ARN
        - Device
        - Entifiers
  /v1/network-resources/{networkResourceArn}:
    GET:
      summary: 'Get Network Resource '
      description: <p>Gets the specified network resource.</p>
      tags:
        - ARN
        - Networks
        - Resources
  /v1/orders/{orderArn}:
    GET:
      summary: 'Get Order '
      description: <p>Gets the specified order.</p>
      tags:
        - ARN
        - Orders
  /v1/device-identifiers/list:
    POST:
      summary: 'List Device Identifiers '
      description: >-
        <p>Lists device identifiers. Add filters to your request to return a
        more specific list of results. Use filters to match the Amazon Resource
        Name (ARN) of an order, the status of device identifiers, or the ARN of
        the traffic group.</p> <p>If you specify multiple filters, filters are
        joined with an OR, and the request returns results that match all of the
        specified filters.</p>
      tags:
        - Device
        - Entifiers
  /v1/network-resources:
    POST:
      summary: 'List Network Resources '
      description: >-
        <p>Lists network resources. Add filters to your request to return a more
        specific list of results. Use filters to match the Amazon Resource Name
        (ARN) of an order or the status of network resources.</p> <p>If you
        specify multiple filters, filters are joined with an OR, and the request
        returns results that match all of the specified filters.</p>
      tags:
        - Networks
        - Resources
  /v1/network-sites/list:
    POST:
      summary: 'List Network Sites '
      description: >-
        <p>Lists network sites. Add filters to your request to return a more
        specific list of results. Use filters to match the status of the network
        site.</p>
      tags:
        - Networks
        - Sites
  /v1/networks/list:
    POST:
      summary: 'List Networks '
      description: >-
        <p>Lists networks. Add filters to your request to return a more specific
        list of results. Use filters to match the status of the network.</p>
      tags:
        - Networks
  /v1/orders/list:
    POST:
      summary: 'List Orders '
      description: >-
        <p>Lists orders. Add filters to your request to return a more specific
        list of results. Use filters to match the Amazon Resource Name (ARN) of
        the network site or the status of the order.</p> <p>If you specify
        multiple filters, filters are joined with an OR, and the request returns
        results that match all of the specified filters.</p>
      tags:
        - Orders
  /tags/{resourceArn}:
    DELETE:
      summary: 'Untag Resource '
      description: <p>Removes tags from the specified resource.</p>
      tags:
        - ARN
        - Resources
        - Tags
        - Untag
  /ping:
    GET:
      summary: 'Ping '
      description: <p>Checks the health of the service.</p>
      tags:
        - Ping
  /v1/network-resources/update:
    POST:
      summary: 'Start Network Resource Update '
      description: >-
        <p>Use this action to do the following tasks:</p> <ul> <li> <p>Update
        the duration and renewal status of the commitment period for a radio
        unit. The update goes into effect immediately.</p> </li> <li> <p>Request
        a replacement for a network resource.</p> </li> <li> <p>Request that you
        return a network resource.</p> </li> </ul> <p>After you submit a request
        to replace or return a network resource, the status of the network
        resource changes to <code>CREATING_SHIPPING_LABEL</code>. The shipping
        label is available when the status of the network resource is
        <code>PENDING_RETURN</code>. After the network resource is successfully
        returned, its status changes to <code>DELETED</code>. For more
        information, see <a
        href="https://docs.aws.amazon.com/private-networks/latest/userguide/radio-units.html#return-radio-unit">Return
        a radio unit</a>.</p>
      tags:
        - Networks
        - Resources
  /v1/network-sites/site:
    PUT:
      summary: 'Update Network Site '
      description: <p>Updates the specified network site.</p>
      tags:
        - Networks
        - Sites
  /v1/network-sites/plan:
    PUT:
      summary: 'Update Network Site Plan '
      description: <p>Updates the specified network site
      tags:
        - Networks
        - Plan
        - Sites
