openapi: 3.1.0
info:
  title: qbusiness
paths:
  /applications/{applicationId}/indices/{indexId}/documents/delete:
    POST:
      summary: 'Batch Delete Document '
      description: >-
        <p>Asynchronously deletes one or more documents added using the
        <code>BatchPutDocument</code> API from an Amazon Q index.</p> <p>You can
        see the progress of the deletion, and any error messages related to the
        process, by using CloudWatch.</p>
      tags:
        - Applications
        - Batches
        - Document
        - Documents
        - Index
        - Indices
  /applications/{applicationId}/indices/{indexId}/documents:
    POST:
      summary: 'Batch Put Document '
      description: >-
        <p>Adds one or more documents to an Amazon Q index.</p> <p>You use this
        API to:</p> <ul> <li> <p>ingest your structured and unstructured
        documents and documents stored in an Amazon S3 bucket into an Amazon Q
        index.</p> </li> <li> <p>add custom attributes to documents in an Amazon
        Q index.</p> </li> <li> <p>attach an access control list to the
        documents added to an Amazon Q index.</p> </li> </ul> <p>You can see the
        progress of the deletion, and any error messages related to the process,
        by using CloudWatch.</p>
      tags:
        - Applications
        - Batches
        - Document
        - Documents
        - Index
        - Indices
  /applications/{applicationId}/conversations?sync:
    POST:
      summary: 'Chat Sync '
      description: <p>Starts or continues a non-streaming Amazon Q conversation.</p>
      tags:
        - Applications
        - Chat
        - Conversations
        - Sync
  /applications:
    GET:
      summary: 'List Applications '
      description: <p>Lists Amazon Q applications.</p>
      tags:
        - Applications
  /applications/{applicationId}/indices/{indexId}/datasources:
    GET:
      summary: 'List Data Sources '
      description: <p>Lists the Amazon Q data source connectors that you have created.</p>
      tags:
        - Applications
        - Data
        - Data Source
        - Index
        - Indices
        - Sources
  /applications/{applicationId}/indices:
    GET:
      summary: 'List Indices '
      description: <p>Lists the Amazon Q indices you have created.</p>
      tags:
        - Applications
        - Indices
  /applications/{applicationId}/plugins:
    GET:
      summary: 'List Plugins '
      description: <p>Lists configured Amazon Q plugins.</p>
      tags:
        - Applications
        - Plugins
  /applications/{applicationId}/retrievers:
    GET:
      summary: 'List Retrievers '
      description: <p>Lists the retriever used by an Amazon Q application.</p>
      tags:
        - Applications
  /applications/{applicationId}/users:
    POST:
      summary: 'Create User '
      description: >-
        <p>Creates a universally unique identifier (UUID) mapped to a list of
        local user ids within an application.</p>
      tags:
        - Applications
        - Users
  /applications/{applicationId}/experiences:
    GET:
      summary: 'List Web Experiences '
      description: <p>Lists one or more Amazon Q Web Experiences.</p>
      tags:
        - Applications
        - Experiences
        - Web
  /applications/{applicationId}:
    PUT:
      summary: 'Update Application '
      description: <p>Updates an existing Amazon Q application.</p>
      tags:
        - Applications
  /applications/{applicationId}/chatcontrols:
    PATCH:
      summary: 'Update Chat Controls Configuration '
      description: >-
        <p>Updates an set of chat controls configured for an existing Amazon Q
        application.</p>
      tags:
        - Applications
        - Chat
        - Chat Controls
        - Configurations
        - Controls
  /applications/{applicationId}/conversations/{conversationId}:
    GET:
      summary: 'List Messages '
      description: >-
        <p>Gets a list of messages associated with an Amazon Q web
        experience.</p>
      tags:
        - Applications
        - Conversations
        - Messages
  /applications/{applicationId}/indices/{indexId}/datasources/{dataSourceId}:
    PUT:
      summary: 'Update Data Source '
      description: <p>Updates an existing Amazon Q data source connector.</p>
      tags:
        - Applications
        - Data
        - Data Source
        - Index
        - Indices
        - Sources
  /applications/{applicationId}/indices/{indexId}/groups/{groupName}:
    GET:
      summary: 'Get Group '
      description: <p>Describes a group by group name.</p>
      tags:
        - Applications
        - Groups
        - Index
        - Indices
        - Names
  /applications/{applicationId}/indices/{indexId}:
    PUT:
      summary: 'Update Index '
      description: <p>Updates an Amazon Q index.</p>
      tags:
        - Applications
        - Index
        - Indices
  /applications/{applicationId}/plugins/{pluginId}:
    PUT:
      summary: 'Update Plugin '
      description: <p>Updates an Amazon Q plugin.</p>
      tags:
        - Applications
        - Plugins
  /applications/{applicationId}/retrievers/{retrieverId}:
    PUT:
      summary: 'Update Retriever '
      description: <p>Updates the retriever used for your Amazon Q application.</p>
      tags:
        - Applications
  /applications/{applicationId}/users/{userId}:
    PUT:
      summary: 'Update User '
      description: <p>Updates a information associated with a user id.</p>
      tags:
        - Applications
        - Users
  /applications/{applicationId}/experiences/{webExperienceId}:
    PUT:
      summary: 'Update Web Experience '
      description: <p>Updates an Amazon Q web experience. </p>
      tags:
        - Applications
        - Experience
        - Experiences
        - Web
  /applications/{applicationId}/conversations:
    GET:
      summary: 'List Conversations '
      description: <p>Lists one or more Amazon Q conversations.</p>
      tags:
        - Applications
        - Conversations
  /applications/{applicationId}/indices/{indexId}/datasources/{dataSourceId}/syncjobs:
    GET:
      summary: 'List Data Source Sync Jobs '
      description: >-
        <p>Get information about an Amazon Q data source connector
        synchronization.</p>
      tags:
        - Applications
        - Data
        - Data Source
        - Index
        - Indices
        - Jobs
        - Sources
        - Sync
        - Sync Jobs
  /applications/{applicationId}/index/{indexId}/documents:
    GET:
      summary: 'List Documents '
      description: <p>A list of documents attached to an index.</p>
      tags:
        - Applications
        - Documents
        - Index
  /applications/{applicationId}/indices/{indexId}/groups:
    PUT:
      summary: 'Put Group '
      description: >-
        <p>Create, or updates, a mapping of users—who have access to a
        document—to groups.</p> <p>You can also map sub groups to groups. For
        example, the group "Company Intellectual Property Teams" includes sub
        groups "Research" and "Engineering". These sub groups include their own
        list of users or people who work in these teams. Only users who work in
        research and engineering, and therefore belong in the intellectual
        property group, can see top-secret company documents in their Amazon Q
        chat results.</p>
      tags:
        - Applications
        - Groups
        - Index
        - Indices
  /v1/tags/{resourceARN}:
    DELETE:
      summary: 'Untag Resource '
      description: <p>Removes a tag from an Amazon Q application or a data source.</p>
      tags:
        - ARN
        - Resources
        - Tags
        - Untag
  /applications/{applicationId}/conversations/{conversationId}/messages/{messageId}/feedback:
    POST:
      summary: 'Put Feedback '
      description: >-
        <p>Enables your end user to to provide feedback on their Amazon Q
        generated chat responses.</p>
      tags:
        - Applications
        - Conversations
        - Feedback
        - Messages
  /applications/{applicationId}/indices/{indexId}/datasources/{dataSourceId}/startsync:
    POST:
      summary: 'Start Data Source Sync Job '
      description: >-
        <p>Starts a data source connector synchronization job. If a
        synchronization job is already in progress, Amazon Q returns a
        <code>ConflictException</code>.</p>
      tags:
        - Applications
        - Data
        - Data Source
        - Index
        - Indices
        - Jobs
        - Sources
        - Start Sync
        - Sync
  /applications/{applicationId}/indices/{indexId}/datasources/{dataSourceId}/stopsync:
    POST:
      summary: 'Stop Data Source Sync Job '
      description: >-
        <p>Stops an Amazon Q data source connector synchronization job already
        in pro
      tags:
        - Applications
        - Data
        - Data Source
        - Index
        - Indices
        - Jobs
        - Sources
        - Stop
        - Stopsync
        - Sync
