openapi: 3.1.0
info:
  title: rbin
paths:
  /rules:
    POST:
      summary: 'Create Rule '
      description: >-
        <p>Creates a Recycle Bin retention rule. For more information, see <a
        href="https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/recycle-bin-working-with-rules.html#recycle-bin-create-rule">
        Create Recycle Bin retention rules</a> in the <i>Amazon Elastic Compute
        Cloud User Guide</i>.</p>
      tags:
        - Rules
  /rules/{identifier}:
    PATCH:
      summary: 'Update Rule '
      description: >-
        <p>Updates an existing Recycle Bin retention rule. You can update a
        retention rule's description, resource tags, and retention period at any
        time after creation. You can't update a retention rule's resource type
        after creation. For more information, see <a
        href="https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/recycle-bin-working-with-rules.html#recycle-bin-update-rule">
        Update Recycle Bin retention rules</a> in the <i>Amazon Elastic Compute
        Cloud User Guide</i>.</p>
      tags:
        - Rules
  /list-rules:
    POST:
      summary: 'List Rules '
      description: <p>Lists the Recycle Bin retention rules in the Region.</p>
      tags:
        - Rules
  /tags/{resourceArn}:
    DELETE:
      summary: 'Untag Resource '
      description: <p>Unassigns a tag from a retention rule.</p>
      tags:
        - ARN
        - Resources
        - Tags
        - Untag
  /rules/{identifier}/lock:
    PATCH:
      summary: 'Lock Rule '
      description: >-
        <p>Locks a retention rule. A locked retention rule can't be modified or
        deleted.</p>
      tags:
        - Locks
        - Rules
  /rules/{identifier}/unlock:
    PATCH:
      summary: 'Unlock Rule '
      description: >-
        <p>Unlocks a retention rule. After a retention rule is unlocked, it can
        be modified or deleted only after the unlock delay period ex
      tags:
        - Rules
        - Unlock
