openapi: 3.1.0
info:
  title: redshift-serverless
paths:
  /:
    POST:
      summary: 'Update Workgroup '
      description: >-
        <p>Updates a workgroup with the specified configuration settings. You
        can't update multiple parameters in one request. For example, you can
        update <code>baseCapacity</code> or <code>port</code> in a single
        request, but you can't update both in the same re
      tags:
        - Workgroup
