openapi: 3.1.0
info:
  title: redshift
paths:
  /:
    POST:
      summary: 'Update Partner Status '
      description: <p>Updates the status of a partner integr
      tags:
        - Partners
        - Status
