openapi: 3.1.0
info:
  title: rekognition
paths:
  /:
    POST:
      summary: 'Update Stream Processor '
      description: >-
        <p> Allows you to update a stream processor. You can change some
        settings and regions of interest and delete certain parame
      tags:
        - Processor
        - Stream
