openapi: 3.1.0
info:
  title: repostspace
paths:
  /spaces:
    GET:
      summary: 'List Spaces '
      description: >-
        <p>Returns a list of AWS re:Post Private private re:Posts in the account
        with some information about each private re:Post.</p>
      tags:
        - Spaces
  /spaces/{spaceId}:
    PUT:
      summary: 'Update Space '
      description: <p>Modifies an existing AWS re:Post Private private re:Post.</p>
      tags:
        - Space
        - Spaces
  /spaces/{spaceId}/admins/{adminId}:
    POST:
      summary: 'Register Admin '
      description: >-
        <p>Adds a user or group to the list of administrators of the private
        re:Post.</p>
      tags:
        - Administrative
        - Administrator
        - Register
        - Space
        - Spaces
  /tags/{resourceArn}:
    DELETE:
      summary: 'Untag Resource '
      description: >-
        <p>Removes the association of the tag with the AWS re:Post Private
        resource.</p>
      tags:
        - ARN
        - Resources
        - Tags
        - Untag
  /spaces/{spaceId}/invite:
    POST:
      summary: 'Send Invites '
      description: <p>Sends an invitation email to selected users and g
      tags:
        - Invite
        - Invites
        - Send
        - Space
        - Spaces
