openapi: 3.1.0
info:
  title: route53resolver
paths:
  /:
    POST:
      summary: 'Update Resolver Rule '
      description: >-
        <p>Updates settings for a specified Resolver rule.
        <code>ResolverRuleId</code> is required, and all other parameters are
        optional. If you don't specify a parameter, it retains its current 
      tags:
        - Resolvers
        - Rules
