openapi: 3.1.0
info:
  title: rum
paths:
  /rummetrics/{AppMonitorName}/metrics:
    PATCH:
      summary: 'Update Rum Metric Definition '
      description: >-
        <p>Modifies one existing metric definition for CloudWatch RUM extended
        metrics. For more information about extended metrics, see <a
        href="https://docs.aws.amazon.com/cloudwatchrum/latest/APIReference/API_BatchCreateRumMetricsDefinitions.html">BatchCreateRumMetricsDefinitions</a>.</p>
      tags:
        - Applications
        - Definitions
        - Metrics
        - Monitors
        - Names
        - Rummetrics
  /appmonitor:
    POST:
      summary: 'Create App Monitor '
      description: >-
        <p>Creates a Amazon CloudWatch RUM app monitor, which collects telemetry
        data from your application and sends that data to RUM. The data includes
        performance and reliability information such as page load time,
        client-side errors, and user behavior.</p> <p>You use this operation
        only to create a new app monitor. To update an existing app monitor, use
        <a
        href="https://docs.aws.amazon.com/cloudwatchrum/latest/APIReference/API_UpdateAppMonitor.html">UpdateAppMonitor</a>
        instead.</p> <p>After you create an app monitor, sign in to the
        CloudWatch RUM console to get the JavaScript code snippet to add to your
        web application. For more information, see <a
        href="https://docs.aws.amazon.com/AmazonCloudWatch/latest/monitoring/CloudWatch-RUM-find-code-snippet.html">How
        do I find a code snippet that I've already generated?</a> </p>
      tags:
        - Applications
        - Monitors
  /appmonitor/{Name}:
    PATCH:
      summary: 'Update App Monitor '
      description: >-
        <p>Updates the configuration of an existing app monitor. When you use
        this operation, only the parts of the app monitor configuration that you
        specify in this operation are changed. For any parameters that you omit,
        the existing values are kept.</p> <p>You can't use this operation to
        change the tags of an existing app monitor. To change the tags of an
        existing app monitor, use <a
        href="https://docs.aws.amazon.com/cloudwatchrum/latest/APIReference/API_TagResource.html">TagResource</a>.</p>
        <p>To create a new app monitor, use <a
        href="https://docs.aws.amazon.com/cloudwatchrum/latest/APIReference/API_CreateAppMonitor.html">CreateAppMonitor</a>.</p>
        <p>After you update an app monitor, sign in to the CloudWatch RUM
        console to get the updated JavaScript code snippet to add to your web
        application. For more information, see <a
        href="https://docs.aws.amazon.com/AmazonCloudWatch/latest/monitoring/CloudWatch-RUM-find-code-snippet.html">How
        do I find a code snippet that I've already generated?</a> </p>
      tags:
        - Applications
        - Monitors
        - Names
  /rummetrics/{AppMonitorName}/metricsdestination:
    POST:
      summary: 'Put Rum Metrics Destination '
      description: >-
        <p>Creates or updates a destination to receive extended metrics from
        CloudWatch RUM. You can send extended metrics to CloudWatch or to a
        CloudWatch Evidently experiment.</p> <p>For more information about
        extended metrics, see <a
        href="https://docs.aws.amazon.com/cloudwatchrum/latest/APIReference/API_BatchCreateRumMetricDefinitions.html">BatchCreateRumMetricDefinitions</a>.</p>
      tags:
        - Applications
        - Destinations
        - Metric Destination
        - Metrics
        - Monitors
        - Names
        - Rummetrics
  /appmonitor/{Name}/data:
    POST:
      summary: 'Get App Monitor Data '
      description: >-
        <p>Retrieves the raw performance events that RUM has collected from your
        web application, so that you can do your own processing or analysis of
        this data.</p>
      tags:
        - Applications
        - Data
        - Monitors
        - Names
  /appmonitors:
    POST:
      summary: 'List App Monitors '
      description: >-
        <p>Returns a list of the Amazon CloudWatch RUM app monitors in the
        account.</p>
      tags:
        - Application Monitors
        - Applications
        - Monitors
  /tags/{ResourceArn}:
    DELETE:
      summary: 'Untag Resource '
      description: <p>Removes one or more tags from the specified resource.</p>
      tags:
        - ARN
        - Resources
        - Tags
        - Untag
  /appmonitors/{Id}/:
    POST:
      summary: 'Put Rum Events '
      description: >-
        <p>Sends telemetry events about your application performance and user
        behavior to CloudWatch RUM. The code snippet that RUM generates for you
        to add to your application includes <code>PutRumEvents</code> operations
        to send this data to RUM.</p> <p>Each <code>PutRumEvents</code>
        operation can send a batch of events from one user se
      tags:
        - Application Monitors
        - Events
