openapi: 3.1.0
info:
  title: s3outposts
paths:
  /S3Outposts/CreateEndpoint:
    POST:
      summary: 'Create Endpoint '
      description: >-
        <p>Creates an endpoint and associates it with the specified Outpost.</p>
        <note> <p>It can take up to 5 minutes for this action to finish.</p>
        </note> <p/> <p>Related actions include:</p> <ul> <li> <p> <a
        href="https://docs.aws.amazon.com/AmazonS3/latest/API/API_s3outposts_DeleteEndpoint.html">DeleteEndpoint</a>
        </p> </li> <li> <p> <a
        href="https://docs.aws.amazon.com/AmazonS3/latest/API/API_s3outposts_ListEndpoints.html">ListEndpoints</a>
        </p> </li> </ul>
      tags:
        - Endpoints
        - S3outposts
  /S3Outposts/DeleteEndpoint:
    DELETE:
      summary: 'Delete Endpoint '
      description: >-
        <p>Deletes an endpoint.</p> <note> <p>It can take up to 5 minutes for
        this action to finish.</p> </note> <p/> <p>Related actions include:</p>
        <ul> <li> <p> <a
        href="https://docs.aws.amazon.com/AmazonS3/latest/API/API_s3outposts_CreateEndpoint.html">CreateEndpoint</a>
        </p> </li> <li> <p> <a
        href="https://docs.aws.amazon.com/AmazonS3/latest/API/API_s3outposts_ListEndpoints.html">ListEndpoints</a>
        </p> </li> </ul>
      tags:
        - Endpoints
        - S3outposts
  /S3Outposts/ListEndpoints:
    GET:
      summary: 'List Endpoints '
      description: >-
        <p>Lists endpoints associated with the specified Outpost. </p>
        <p>Related actions include:</p> <ul> <li> <p> <a
        href="https://docs.aws.amazon.com/AmazonS3/latest/API/API_s3outposts_CreateEndpoint.html">CreateEndpoint</a>
        </p> </li> <li> <p> <a
        href="https://docs.aws.amazon.com/AmazonS3/latest/API/API_s3outposts_DeleteEndpoint.html">DeleteEndpoint</a>
        </p> </li> </ul>
      tags:
        - Endpoints
        - S3outposts
  /S3Outposts/ListOutpostsWithS3:
    GET:
      summary: 'List Outposts With S3 '
      description: >-
        <p>Lists the Outposts with S3 on Outposts capacity for your Amazon Web
        Services account. Includes S3 on Outposts that you have access to as the
        Outposts owner, or as a shared user from Resource Access Manager (RAM).
        </p>
      tags:
        - Outposts
        - S3outposts
  /S3Outposts/ListSharedEndpoints:
    GET:
      summary: 'List Shared Endpoints '
      description: >-
        <p>Lists all endpoints associated with an Outpost that has been shared
        by Amazon Web Services Resource Access Manager (RAM).</p> <p>Related
        actions include:</p> <ul> <li> <p> <a
        href="https://docs.aws.amazon.com/AmazonS3/latest/API/API_s3outposts_CreateEndpoint.html">CreateEndpoint</a>
        </p> </li> <li> <p> <a
        href="https://docs.aws.amazon.com/AmazonS3/latest/API/API_s3outposts_DeleteEndpoint.html">DeleteEndpoint</a>
        </p> <
      tags:
        - Endpoints
        - S3outposts
        - Shared
