openapi: 3.1.0
info:
  title: sagemaker-edge
paths:
  /GetDeployments:
    POST:
      summary: 'Get Deployments '
      description: <p>Use to get the active deployments from a device.</p>
      tags:
        - Deployments
  /GetDeviceRegistration:
    POST:
      summary: 'Get Device Registration '
      description: >-
        <p>Use to check if a device is registered with SageMaker Edge
        Manager.</p>
      tags:
        - Device
        - Registrations
  /SendHeartbeat:
    POST:
      summary: 'Send Heartbeat '
      description: >-
        <p>Use to get the current status of devices registered on SageMaker Edge
        Ma
      tags:
        - Heart Beats
        - Send
