openapi: 3.1.0
info:
  title: sagemaker-a2i-runtime
paths:
  /human-loops/{HumanLoopName}:
    GET:
      summary: 'Describe Human Loop '
      description: >-
        <p>Returns information about the specified human loop. If the human loop
        was deleted, this operation will return a
        <code>ResourceNotFoundException</code> error. </p>
      tags:
        - Describe
        - Human
        - Loops
        - Names
  /human-loops:
    POST:
      summary: 'Start Human Loop '
      description: >-
        <p>Starts a human loop, provided that at least one activation condition
        is met.</p>
      tags:
        - Human
        - Loops
  /human-loops/stop:
    POST:
      summary: 'Stop Human Loop '
      description: <p>Stops the specified human
      tags:
        - Human
        - Loops
        - Stop
