openapi: 3.1.0
info:
  title: sagemaker-geospatial
paths:
  /earth-observation-jobs/{Arn}:
    GET:
      summary: 'Get Earth Observation Job '
      description: <p>Get the details for a previously initiated Earth Observation job.</p>
      tags:
        - ARN
        - Earth
        - Jobs
        - Observation
  /vector-enrichment-jobs/{Arn}:
    GET:
      summary: 'Get Vector Enrichment Job '
      description: >-
        <p>Retrieves details of a Vector Enrichment Job for a given job Amazon
        Resource Name (ARN).</p>
      tags:
        - ARN
        - Enrichment
        - Jobs
        - Vectors
  /export-earth-observation-job:
    POST:
      summary: 'Export Earth Observation Job '
      description: >-
        <p>Use this operation to export results of an Earth Observation job and
        optionally source images used as input to the EOJ to an Amazon S3
        location.</p>
      tags:
        - Earth
        - Exports
        - Jobs
        - Observation
  /export-vector-enrichment-jobs:
    POST:
      summary: 'Export Vector Enrichment Job '
      description: >-
        <p>Use this operation to copy results of a Vector Enrichment job to an
        Amazon S3 location.</p>
      tags:
        - Enrichment
        - Exports
        - Jobs
        - Vectors
  /raster-data-collection/{Arn}:
    GET:
      summary: 'Get Raster Data Collection '
      description: >-
        <p>Use this operation to get details of a specific raster data
        collection.</p>
      tags:
        - ARN
        - Collections
        - Data
        - Raster
  /tile/{z}/{x}/{y}:
    GET:
      summary: 'Get Tile '
      description: <p>Gets a web mercator tile for the given Earth Observation job.</p>
      tags:
        - Tiles
  /list-earth-observation-jobs:
    POST:
      summary: 'List Earth Observation Jobs '
      description: >-
        <p>Use this operation to get a list of the Earth Observation jobs
        associated with the calling Amazon Web Services account.</p>
      tags:
        - Earth
        - Jobs
        - Observation
  /raster-data-collections:
    GET:
      summary: 'List Raster Data Collections '
      description: <p>Use this operation to get raster data collections.</p>
      tags:
        - Collections
        - Data
        - Raster
  /tags/{ResourceArn}:
    DELETE:
      summary: 'Untag Resource '
      description: <p>The resource you want to untag.</p>
      tags:
        - ARN
        - Resources
        - Tags
        - Untag
  /list-vector-enrichment-jobs:
    POST:
      summary: 'List Vector Enrichment Jobs '
      description: <p>Retrieves a list of vector enrichment jobs.</p>
      tags:
        - Enrichment
        - Jobs
        - Vectors
  /search-raster-data-collection:
    POST:
      summary: 'Search Raster Data Collection '
      description: >-
        <p>Allows you run image query on a specific raster data collection to
        get a list of the satellite imagery matching the selected filters.</p>
      tags:
        - Collections
        - Data
        - Raster
        - Search
  /earth-observation-jobs:
    POST:
      summary: 'Start Earth Observation Job '
      description: <p>Use this operation to create an Earth observation job.</p>
      tags:
        - Earth
        - Jobs
        - Observation
  /vector-enrichment-jobs:
    POST:
      summary: 'Start Vector Enrichment Job '
      description: >-
        <p>Creates a Vector Enrichment job for the supplied job type. Currently,
        there are two supported job types: reverse geocoding and map
        matching.</p>
      tags:
        - Enrichment
        - Jobs
        - Vectors
  /earth-observation-jobs/stop:
    POST:
      summary: 'Stop Earth Observation Job '
      description: <p>Use this operation to stop an existing earth observation job.</p>
      tags:
        - Earth
        - Jobs
        - Observation
        - Stop
  /vector-enrichment-jobs/stop:
    POST:
      summary: 'Stop Vector Enrichment Job '
      description: <p>Stops the Vector Enrichment job for a given j
      tags:
        - Enrichment
        - Jobs
        - Stop
        - Vectors
