openapi: 3.1.0
info:
  title: sagemaker
paths:
  /:
    POST:
      summary: 'Update Workteam '
      description: <p>Updates an existing work team with new member definitions or descri
      tags:
        - Workteam
