openapi: 3.1.0
info:
  title: savingsplans
paths:
  /CreateSavingsPlan:
    POST:
      summary: 'Create Savings Plan '
      description: <p>Creates a Savings Plan.</p>
      tags:
        - Plan
        - Savings
  /DeleteQueuedSavingsPlan:
    POST:
      summary: 'Delete Queued Savings Plan '
      description: <p>Deletes the queued purchase for the specified Savings Plan.</p>
      tags:
        - Plan
        - Queued
        - Savings
  /DescribeSavingsPlanRates:
    POST:
      summary: 'Describe Savings Plan Rates '
      description: <p>Describes the specified Savings Plans rates.</p>
      tags:
        - Describe
        - Plan
        - Rates
        - Savings
  /DescribeSavingsPlans:
    POST:
      summary: 'Describe Savings Plans '
      description: <p>Describes the specified Savings Plans.</p>
      tags:
        - Describe
        - Plans
        - Savings
  /DescribeSavingsPlansOfferingRates:
    POST:
      summary: 'Describe Savings Plans Offering Rates '
      description: <p>Describes the specified Savings Plans offering rates.</p>
      tags:
        - Describe
        - Offerings
        - Plans
        - Rates
        - Savings
  /DescribeSavingsPlansOfferings:
    POST:
      summary: 'Describe Savings Plans Offerings '
      description: <p>Describes the specified Savings Plans offerings.</p>
      tags:
        - Describe
        - Offerings
        - Plans
        - Savings
  /ListTagsForResource:
    POST:
      summary: 'List Tags For Resource '
      description: <p>Lists the tags for the specified resource.</p>
      tags:
        - Resources
        - Tags
  /TagResource:
    POST:
      summary: 'Tag Resource '
      description: <p>Adds the specified tags to the specified resource.</p>
      tags:
        - Resources
        - Tags
  /UntagResource:
    POST:
      summary: 'Untag Resource '
      description: <p>Removes the specified tags from the specified res
      tags:
        - Resources
        - Untag
