openapi: 3.1.0
info:
  title: securitylake
paths:
  /v1/datalake/logsources/aws:
    POST:
      summary: 'Create Aws Log Source '
      description: >-
        <p>Adds a natively supported Amazon Web Service as an Amazon Security
        Lake source. Enables source types for member accounts in required Amazon
        Web Services Regions, based on the parameters you specify. You can
        choose any source type in any Region for either accounts that are part
        of a trusted organization or standalone accounts. Once you add an Amazon
        Web Service as a source, Security Lake starts collecting logs and events
        from it.</p> <p>You can use this API only to enable natively supported
        Amazon Web Services as a source. Use <code>CreateCustomLogSource</code>
        to enable data collection from a custom source.</p>
      tags:
        - Data Lakes
        - Log Sources
        - Logs
        - Sources
  /v1/datalake/logsources/custom:
    POST:
      summary: 'Create Custom Log Source '
      description: >-
        <p>Adds a third-party custom source in Amazon Security Lake, from the
        Amazon Web Services Region where you want to create a custom source.
        Security Lake can collect logs and events from third-party custom
        sources. After creating the appropriate IAM role to invoke Glue crawler,
        use this API to add a custom source name in Security Lake. This
        operation creates a partition in the Amazon S3 bucket for Security Lake
        as the target location for log files from the custom source. In
        addition, this operation also creates an associated Glue table and an
        Glue crawler.</p>
      tags:
        - Custom
        - Data Lakes
        - Log Sources
        - Logs
        - Sources
  /v1/datalake:
    PUT:
      summary: 'Update Data Lake '
      description: >-
        <p>Specifies where to store your security data and for how long. You can
        add a rollup Region to consolidate data from multiple Amazon Web
        Services Regions.</p>
      tags:
        - Data
        - Data Lakes
        - Lakes
  /v1/datalake/exceptions/subscription:
    PUT:
      summary: 'Update Data Lake Exception Subscription '
      description: >-
        <p>Updates the specified notification subscription in Amazon Security
        Lake for the organization you specify.</p>
      tags:
        - Data
        - Data Lakes
        - Exceptions
        - Lakes
        - Subscriptions
  /v1/datalake/organization/configuration:
    GET:
      summary: 'Get Data Lake Organization Configuration '
      description: >-
        <p>Retrieves the configuration that will be automatically set up for
        accounts added to the organization after the organization has onboarded
        to Amazon Security Lake. This API does not take input parameters.</p>
      tags:
        - Configurations
        - Data
        - Data Lakes
        - Lakes
        - Organizations
  /v1/subscribers:
    GET:
      summary: 'List Subscribers '
      description: >-
        <p>List all subscribers for the specific Amazon Security Lake account
        ID. You can retrieve a list of subscriptions associated with a specific
        organization or Amazon Web Services account.</p>
      tags:
        - Subscribers
  /v1/subscribers/{subscriberId}/notification:
    PUT:
      summary: 'Update Subscriber Notification '
      description: >-
        <p>Updates an existing notification method for the subscription (SQS or
        HTTPs endpoint) or switches the notification subscription endpoint for a
        subscriber.</p>
      tags:
        - Notifications
        - Subscribers
  /v1/datalake/logsources/aws/delete:
    POST:
      summary: 'Delete Aws Log Source '
      description: >-
        <p>Removes a natively supported Amazon Web Service as an Amazon Security
        Lake source. You can remove a source for one or more Regions. When you
        remove the source, Security Lake stops collecting data from that source
        in the specified Regions and accounts, and subscribers can no longer
        consume new data from the source. However, subscribers can still consume
        data that Security Lake collected from the source before removal.</p>
        <p>You can choose any source type in any Amazon Web Services Region for
        either accounts that are part of a trusted organization or standalone
        accounts. </p>
      tags:
        - Data Lakes
        - Log Sources
        - Logs
        - Sources
  /v1/datalake/logsources/custom/{sourceName}:
    DELETE:
      summary: 'Delete Custom Log Source '
      description: >-
        <p>Removes a custom log source from Amazon Security Lake, to stop
        sending data from the custom source to Security Lake.</p>
      tags:
        - Custom
        - Data Lakes
        - Log Sources
        - Logs
        - Names
        - Sources
  /v1/datalake/delete:
    POST:
      summary: 'Delete Data Lake '
      description: >-
        <p>When you disable Amazon Security Lake from your account, Security
        Lake is disabled in all Amazon Web Services Regions and it stops
        collecting data from your sources. Also, this API automatically takes
        steps to remove the account from Security Lake. However, Security Lake
        retains all of your existing settings and the resources that it created
        in your Amazon Web Services account in the current Amazon Web Services
        Region.</p> <p>The <code>DeleteDataLake</code> operation does not delete
        the data that is stored in your Amazon S3 bucket, which is owned by your
        Amazon Web Services account. For more information, see the <a
        href="https://docs.aws.amazon.com/security-lake/latest/userguide/disable-security-lake.html">Amazon
        Security Lake User Guide</a>.</p>
      tags:
        - Data
        - Data Lakes
        - Lakes
  /v1/datalake/organization/configuration/delete:
    POST:
      summary: 'Delete Data Lake Organization Configuration '
      description: >-
        <p>Turns off automatic enablement of Amazon Security Lake for member
        accounts that are added to an organization in Organizations. Only the
        delegated Security Lake administrator for an organization can perform
        this operation. If the delegated Security Lake administrator performs
        this operation, new member accounts won't automatically contribute data
        to the data lake.</p>
      tags:
        - Configurations
        - Data
        - Data Lakes
        - Lakes
        - Organizations
  /v1/subscribers/{subscriberId}:
    PUT:
      summary: 'Update Subscriber '
      description: >-
        <p>Updates an existing subscription for the given Amazon Security Lake
        account ID. You can update a subscriber by changing the sources that the
        subscriber consumes data from.</p>
      tags:
        - Subscribers
  /v1/datalake/delegate:
    POST:
      summary: 'Register Data Lake Delegated Administrator '
      description: >-
        <p>Designates the Amazon Security Lake delegated administrator account
        for the organization. This API can only be called by the organization
        management account. The organization management account cannot be the
        delegated administrator account.</p>
      tags:
        - Administrator
        - Data
        - Data Lakes
        - Delegate
        - Delegated
        - Lakes
        - Register
  /v1/datalake/sources:
    POST:
      summary: 'Get Data Lake Sources '
      description: >-
        <p>Retrieves a snapshot of the current Region, including whether Amazon
        Security Lake is enabled for those accounts and which sources Security
        Lake is collecting data from.</p>
      tags:
        - Data
        - Data Lakes
        - Lakes
        - Sources
  /v1/datalake/exceptions:
    POST:
      summary: 'List Data Lake Exceptions '
      description: >-
        <p>Lists the Amazon Security Lake exceptions that you can use to find
        the source of problems and fix them.</p>
      tags:
        - Data
        - Data Lakes
        - Exceptions
        - Lakes
  /v1/datalakes:
    GET:
      summary: 'List Data Lakes '
      description: >-
        <p>Retrieves the Amazon Security Lake configuration object for the
        specified Amazon Web Services Regions. You can use this operation to
        determine whether Security Lake is enabled for a Region.</p>
      tags:
        - Data
        - Data Lakes
        - Lakes
  /v1/datalake/logsources/list:
    POST:
      summary: 'List Log Sources '
      description: >-
        <p>Retrieves the log sources in the current Amazon Web Services
        Region.</p>
      tags:
        - Data Lakes
        - Log Sources
        - Logs
        - Sources
  /v1/tags/{resourceArn}:
    DELETE:
      summary: 'Untag Resource '
      description: >-
        <p>Removes one or more tags (keys and values) from an Amazon Security
        Lake resource: a subscriber, or the data lake configuration for your
        Amazon Web Services account in a particular Amazon Web Services R
      tags:
        - ARN
        - Resources
        - Tags
        - Untag
