openapi: 3.1.0
info:
  title: serverlessrepo
paths:
  /applications:
    GET:
      summary: 'List Applications '
      description: <p>Lists applications owned by the requester.</p>
      tags:
        - Applications
  /applications/{applicationId}/versions/{semanticVersion}:
    PUT:
      summary: 'Create Application Version '
      description: <p>Creates an application version.</p>
      tags:
        - Applications
        - Semantic
        - Versions
  /applications/{applicationId}/changesets:
    POST:
      summary: 'Create Cloud Formation Change Set '
      description: >-
        <p>Creates an AWS CloudFormation change set for the given
        application.</p>
      tags:
        - Applications
        - Change
        - Change Sets
        - Cloud
        - Formation
        - Sets
  /applications/{applicationId}/templates:
    POST:
      summary: 'Create Cloud Formation Template '
      description: <p>Creates an AWS CloudFormation template.</p>
      tags:
        - Applications
        - Cloud
        - Formation
        - Templates
  /applications/{applicationId}:
    PATCH:
      summary: 'Update Application '
      description: <p>Updates the specified application.</p>
      tags:
        - Applications
  /applications/{applicationId}/policy:
    PUT:
      summary: 'Put Application Policy '
      description: >-
        <p>Sets the permission policy for an application. For the list of
        actions supported for this operation, see
         <a href="https://docs.aws.amazon.com/serverlessrepo/latest/devguide/access-control-resource-based.html#application-permissions">Application 
         Permissions</a>
         .</p>
      tags:
        - Applications
        - Policies
  /applications/{applicationId}/templates/{templateId}:
    GET:
      summary: 'Get Cloud Formation Template '
      description: <p>Gets the specified AWS CloudFormation template.</p>
      tags:
        - Applications
        - Cloud
        - Formation
        - Templates
  /applications/{applicationId}/dependencies:
    GET:
      summary: 'List Application Dependencies '
      description: >-
        <p>Retrieves the list of applications nested in the containing
        application.</p>
      tags:
        - Applications
        - Dependencies
  /applications/{applicationId}/versions:
    GET:
      summary: 'List Application Versions '
      description: <p>Lists versions for the specified application.</p>
      tags:
        - Applications
        - Versions
  /applications/{applicationId}/unshare:
    POST:
      summary: 'Unshare Application '
      description: >-
        <p>Unshares an application from an AWS Organization.</p><p>This
        operation can be called only from the organization's master ac
      tags:
        - Applications
        - Unshare
