openapi: 3.1.0
info:
  title: service-quotas
paths:
  /:
    POST:
      summary: 'Untag Resource '
      description: >-
        <p>Removes tags from the specified applied quota. You can specify one or
        more tags to r
      tags:
        - Resources
        - Untag
