openapi: 3.1.0
info:
  title: signer
paths:
  /signing-profiles/{profileName}/permissions:
    GET:
      summary: 'List Profile Permissions '
      description: >-
        <p>Lists the cross-account permissions associated with a signing
        profile.</p>
      tags:
        - Names
        - Permissions
        - Profiles
        - Signing
  /signing-profiles/{profileName}:
    PUT:
      summary: 'Put Signing Profile '
      description: >-
        <p>Creates a signing profile. A signing profile is a code-signing
        template that can be used to carry out a pre-defined signing job. </p>
      tags:
        - Names
        - Profiles
        - Signing
  /signing-jobs/{jobId}:
    GET:
      summary: 'Describe Signing Job '
      description: >-
        <p>Returns information about a specific code signing job. You specify
        the job by using the <code>jobId</code> value that is returned by the
        <a>StartSigningJob</a> operation. </p>
      tags:
        - Describe
        - Jobs
        - Signing
  /revocations:
    GET:
      summary: 'Get Revocation Status '
      description: >-
        <p>Retrieves the revocation status of one or more of the signing
        profile, signing job, and signing certificate.</p>
      tags:
        - Revocations
        - Status
  /signing-platforms/{platformId}:
    GET:
      summary: 'Get Signing Platform '
      description: <p>Returns information on a specific signing platform.</p>
      tags:
        - Platforms
        - Signing
  /signing-jobs:
    POST:
      summary: 'Start Signing Job '
      description: >-
        <p>Initiates a signing job to be performed on the code provided. Signing
        jobs are viewable by the <code>ListSigningJobs</code> operation for two
        years after they are performed. Note the following requirements: </p>
        <ul> <li> <p> You must create an Amazon S3 source bucket. For more
        information, see <a
        href="http://docs.aws.amazon.com/AmazonS3/latest/gsg/CreatingABucket.html">Creating
        a Bucket</a> in the <i>Amazon S3 Getting Started Guide</i>. </p> </li>
        <li> <p>Your S3 source bucket must be version enabled.</p> </li> <li>
        <p>You must create an S3 destination bucket. AWS Signer uses your S3
        destination bucket to write your signed code.</p> </li> <li> <p>You
        specify the name of the source and destination buckets when calling the
        <code>StartSigningJob</code> operation.</p> </li> <li> <p>You must also
        specify a request token that identifies your request to Signer.</p>
        </li> </ul> <p>You can call the <a>DescribeSigningJob</a> and the
        <a>ListSigningJobs</a> actions after you call
        <code>StartSigningJob</code>.</p> <p>For a Java example that shows how
        to use this action, see <a
        href="https://docs.aws.amazon.com/signer/latest/developerguide/api-startsigningjob.html">StartSigningJob</a>.</p>
      tags:
        - Jobs
        - Signing
  /signing-platforms:
    GET:
      summary: 'List Signing Platforms '
      description: >-
        <p>Lists all signing platforms available in AWS Signer that match the
        request parameters. If additional jobs remain to be listed, Signer
        returns a <code>nextToken</code> value. Use this value in subsequent
        calls to <code>ListSigningJobs</code> to fetch the remaining values. You
        can continue calling <code>ListSigningJobs</code> with your
        <code>maxResults</code> parameter and with new values that Signer
        returns in the <code>nextToken</code> parameter until all of your
        signing jobs have been returned.</p>
      tags:
        - Platforms
        - Signing
  /signing-profiles:
    GET:
      summary: 'List Signing Profiles '
      description: >-
        <p>Lists all available signing profiles in your AWS account. Returns
        only profiles with an <code>ACTIVE</code> status unless the
        <code>includeCanceled</code> request field is set to <code>true</code>.
        If additional jobs remain to be listed, AWS Signer returns a
        <code>nextToken</code> value. Use this value in subsequent calls to
        <code>ListSigningJobs</code> to fetch the remaining values. You can
        continue calling <code>ListSigningJobs</code> with your
        <code>maxResults</code> parameter and with new values that Signer
        returns in the <code>nextToken</code> parameter until all of your
        signing jobs have been returned.</p>
      tags:
        - Profiles
        - Signing
  /tags/{resourceArn}:
    DELETE:
      summary: 'Untag Resource '
      description: >-
        <p>Removes one or more tags from a signing profile. To remove the tags,
        specify a list of tag keys.</p>
      tags:
        - ARN
        - Resources
        - Tags
        - Untag
  /signing-profiles/{profileName}/permissions/{statementId}:
    DELETE:
      summary: 'Remove Profile Permission '
      description: <p>Removes cross-account permissions from a signing profile.</p>
      tags:
        - Names
        - Permission
        - Permissions
        - Profiles
        - Removes
        - Signing
        - Statements
  /signing-jobs/{jobId}/revoke:
    PUT:
      summary: 'Revoke Signature '
      description: >-
        <p>Changes the state of a signing job to REVOKED. This indicates that
        the signature is no longer valid.</p>
      tags:
        - Jobs
        - Revoke
        - Signatures
        - Signing
  /signing-profiles/{profileName}/revoke:
    PUT:
      summary: 'Revoke Signing Profile '
      description: >-
        <p>Changes the state of a signing profile to REVOKED. This indicates
        that signatures generated using the signing profile after an effective
        start date are no longer valid.</p>
      tags:
        - Names
        - Profiles
        - Revoke
        - Signing
  /signing-jobs/with-payload:
    POST:
      summary: 'Sign Payload '
      description: <p>Signs a binary payload and returns a signature env
      tags:
        - Jobs
        - Payload
        - Sign
        - Signing
