openapi: 3.1.0
info:
  title: sms
paths:
  /:
    POST:
      summary: 'Update Replication Job '
      description: <p>Updates the specified settings for the specified replicati
      tags:
        - Jobs
        - Replication
