openapi: 3.1.0
info:
  title: snow-device-management
paths:
  /task/{taskId}/cancel:
    POST:
      summary: 'Cancel Task '
      description: >-
        <p>Sends a cancel request for a specified task. You can cancel a task
        only if it's still in a <code>QUEUED</code> state. Tasks that are
        already running can't be cancelled.</p> <note> <p>A task might still run
        if it's processed from the queue before the <code>CancelTask</code>
        operation changes the task's state.</p> </note>
      tags:
        - Cancel
        - Tasks
  /task:
    POST:
      summary: 'Create Task '
      description: >-
        <p>Instructs one or more devices to start a task, such as unlocking or
        rebooting.</p>
      tags:
        - Tasks
  /managed-device/{managedDeviceId}/describe:
    POST:
      summary: 'Describe Device '
      description: >-
        <p>Checks device-specific information, such as the device type, software
        version, IP addresses, and lock status.</p>
      tags:
        - Describe
        - Device
        - Managed
  /managed-device/{managedDeviceId}/resources/ec2/describe:
    POST:
      summary: 'Describe Device Ec2Instances '
      description: >-
        <p>Checks the current state of the Amazon EC2 instances. The output is
        similar to <code>describeDevice</code>, but the results are sourced from
        the device cache in the Amazon Web Services Cloud and include a subset
        of the available fields. </p>
      tags:
        - Describe
        - Device
        - EC2
        - Ec2Instances
        - Managed
        - Resources
  /task/{taskId}/execution/{managedDeviceId}:
    POST:
      summary: 'Describe Execution '
      description: >-
        <p>Checks the status of a remote task running on one or more target
        devices.</p>
      tags:
        - Describe
        - Device
        - Execution
        - Managed
        - Tasks
  /task/{taskId}:
    POST:
      summary: 'Describe Task '
      description: <p>Checks the metadata for a given task on a device. </p>
      tags:
        - Describe
        - Tasks
  /managed-device/{managedDeviceId}/resources:
    GET:
      summary: 'List Device Resources '
      description: >-
        <p>Returns a list of the Amazon Web Services resources available for a
        device. Currently, Amazon EC2 instances are the only supported resource
        type.</p>
      tags:
        - Device
        - Managed
        - Resources
  /managed-devices:
    GET:
      summary: 'List Devices '
      description: >-
        <p>Returns a list of all devices on your Amazon Web Services account
        that have Amazon Web Services Snow Device Management enabled in the
        Amazon Web Services Region where the command is run.</p>
      tags:
        - Devices
        - Managed
  /executions:
    GET:
      summary: 'List Executions '
      description: <p>Returns the status of tasks for one or more target devices.</p>
      tags:
        - Executions
  /tags/{resourceArn}:
    DELETE:
      summary: 'Untag Resource '
      description: <p>Removes a tag from a device or task.</p>
      tags:
        - ARN
        - Resources
        - Tags
        - Untag
  /tasks:
    GET:
      summary: 'List Tasks '
      description: <p>Returns a list of tasks that can be filtered by
      tags:
        - Tasks
