openapi: 3.1.0
info:
  title: ssm-incidents
paths:
  /batchGetIncidentFindings:
    POST:
      summary: 'Batch Get Incident Findings '
      description: >-
        <p>Retrieves details about all specified findings for an incident,
        including descriptive details about each finding. A finding represents a
        recent application environment change made by an CodeDeploy deployment
        or an CloudFormation stack creation or update that can be investigated
        as a potential cause of the incident.</p>
      tags:
        - Batches
        - Ent
        - Findings
        - Inc
        - Incident
  /createReplicationSet:
    POST:
      summary: 'Create Replication Set '
      description: >-
        <p>A replication set replicates and encrypts your data to the provided
        Regions with the provided KMS key. </p>
      tags:
        - Replication
        - Sets
  /createResponsePlan:
    POST:
      summary: 'Create Response Plan '
      description: >-
        <p>Creates a response plan that automates the initial response to
        incidents. A response plan engages contacts, starts chat channel
        collaboration, and initiates runbooks at the beginning of an
        incident.</p>
      tags:
        - Plan
        - Responses
  /createTimelineEvent:
    POST:
      summary: 'Create Timeline Event '
      description: >-
        <p>Creates a custom timeline event on the incident details page of an
        incident record. Incident Manager automatically creates timeline events
        that mark key moments during an incident. You can create custom timeline
        events to mark important events that Incident Manager can detect
        automatically.</p>
      tags:
        - Events
        - Timeline
  /deleteIncidentRecord:
    POST:
      summary: 'Delete Incident Record '
      description: <p>Delete an incident record from Incident Manager. </p>
      tags:
        - Ent
        - Inc
        - Incident
        - Record
  /deleteReplicationSet:
    POST:
      summary: 'Delete Replication Set '
      description: >-
        <p>Deletes all Regions in your replication set. Deleting the replication
        set deletes all Incident Manager data.</p>
      tags:
        - Replication
        - Sets
  /deleteResourcePolicy:
    POST:
      summary: 'Delete Resource Policy '
      description: >-
        <p>Deletes the resource policy that Resource Access Manager uses to
        share your Incident Manager resource.</p>
      tags:
        - Policies
        - Resources
  /deleteResponsePlan:
    POST:
      summary: 'Delete Response Plan '
      description: >-
        <p>Deletes the specified response plan. Deleting a response plan stops
        all linked CloudWatch alarms and EventBridge events from creating an
        incident with this response plan.</p>
      tags:
        - Plan
        - Responses
  /deleteTimelineEvent:
    POST:
      summary: 'Delete Timeline Event '
      description: <p>Deletes a timeline event from an incident.</p>
      tags:
        - Events
        - Timeline
  /getIncidentRecord:
    GET:
      summary: 'Get Incident Record '
      description: <p>Returns the details for the specified incident record.</p>
      tags:
        - Ent
        - Inc
        - Incident
        - Record
  /getReplicationSet:
    GET:
      summary: 'Get Replication Set '
      description: <p>Retrieve your Incident Manager replication set.</p>
      tags:
        - Replication
        - Sets
  /getResourcePolicies:
    POST:
      summary: 'Get Resource Policies '
      description: >-
        <p>Retrieves the resource policies attached to the specified response
        plan.</p>
      tags:
        - Policies
        - Resources
  /getResponsePlan:
    GET:
      summary: 'Get Response Plan '
      description: <p>Retrieves the details of the specified response plan.</p>
      tags:
        - Plan
        - Responses
  /getTimelineEvent:
    GET:
      summary: 'Get Timeline Event '
      description: <p>Retrieves a timeline event based on its ID and incident record.</p>
      tags:
        - Events
        - Timeline
  /listIncidentFindings:
    POST:
      summary: 'List Incident Findings '
      description: >-
        <p>Retrieves a list of the IDs of findings, plus their last modified
        times, that have been identified for a specified incident. A finding
        represents a recent application environment change made by an
        CloudFormation stack creation or update or an CodeDeploy deployment that
        can be investigated as a potential cause of the incident.</p>
      tags:
        - Ent
        - Findings
        - Inc
        - Incident
  /listIncidentRecords:
    POST:
      summary: 'List Incident Records '
      description: >-
        <p>Lists all incident records in your account. Use this command to
        retrieve the Amazon Resource Name (ARN) of the incident record you want
        to update. </p>
      tags:
        - Ent
        - Inc
        - Incident
        - Records
  /listRelatedItems:
    POST:
      summary: 'List Related Items '
      description: <p>List all related items for an incident record.</p>
      tags:
        - Items
        - Related
  /listReplicationSets:
    POST:
      summary: 'List Replication Sets '
      description: >-
        <p>Lists details about the replication set configured in your account.
        </p>
      tags:
        - Replication
        - Sets
  /listResponsePlans:
    POST:
      summary: 'List Response Plans '
      description: <p>Lists all response plans in your account.</p>
      tags:
        - Plans
        - Responses
  /tags/{resourceArn}:
    DELETE:
      summary: 'Untag Resource '
      description: <p>Removes a tag from a resource.</p>
      tags:
        - ARN
        - Resources
        - Tags
        - Untag
  /listTimelineEvents:
    POST:
      summary: 'List Timeline Events '
      description: <p>Lists timeline events for the specified incident record.</p>
      tags:
        - Events
        - Timeline
  /putResourcePolicy:
    POST:
      summary: 'Put Resource Policy '
      description: >-
        <p>Adds a resource policy to the specified response plan. The resource
        policy is used to share the response plan using Resource Access Manager
        (RAM). For more information about cross-account sharing, see <a
        href="https://docs.aws.amazon.com/incident-manager/latest/userguide/incident-manager-cross-account-cross-region.html">Cross-Region
        and cross-account incident management</a>.</p>
      tags:
        - Policies
        - Resources
  /startIncident:
    POST:
      summary: 'Start Incident '
      description: >-
        <p>Used to start an incident from CloudWatch alarms, EventBridge events,
        or manually. </p>
      tags:
        - Ent
        - Inc
        - Incident
  /updateDeletionProtection:
    POST:
      summary: 'Update Deletion Protection '
      description: >-
        <p>Update deletion protection to either allow or deny deletion of the
        final Region in a replication set.</p>
      tags:
        - Deletion
        - Protection
  /updateIncidentRecord:
    POST:
      summary: 'Update Incident Record '
      description: >-
        <p>Update the details of an incident record. You can use this operation
        to update an incident record from the defined chat channel. For more
        information about using actions in chat channels, see <a
        href="https://docs.aws.amazon.com/incident-manager/latest/userguide/chat.html#chat-interact">Interacting
        through chat</a>.</p>
      tags:
        - Ent
        - Inc
        - Incident
        - Record
  /updateRelatedItems:
    POST:
      summary: 'Update Related Items '
      description: >-
        <p>Add or remove related items from the related items tab of an incident
        record.</p>
      tags:
        - Items
        - Related
  /updateReplicationSet:
    POST:
      summary: 'Update Replication Set '
      description: <p>Add or delete Regions from your replication set.</p>
      tags:
        - Replication
        - Sets
  /updateResponsePlan:
    POST:
      summary: 'Update Response Plan '
      description: <p>Updates the specified response plan.</p>
      tags:
        - Plan
        - Responses
  /updateTimelineEvent:
    POST:
      summary: 'Update Timeline Event '
      description: >-
        <p>Updates a timeline event. You can update events of type <code>Custom
        Event</
      tags:
        - Events
        - Timeline
