openapi: 3.1.0
info:
  title: sso
paths:
  /federation/credentials:
    GET:
      summary: 'Get Role Credentials '
      description: >-
        <p>Returns the STS short-term credentials for a given role name that is
        assigned to the user.</p>
      tags:
        - Credentials
        - Federation
        - Roles
  /assignment/roles:
    GET:
      summary: 'List Account Roles '
      description: >-
        <p>Lists all roles that are assigned to the user for a given AWS
        account.</p>
      tags:
        - Accounts
        - Assignment
        - Roles
  /assignment/accounts:
    GET:
      summary: 'List Accounts '
      description: >-
        <p>Lists all AWS accounts assigned to the user. These AWS accounts are
        assigned by the administrator of the account. For more information, see
        <a
        href="https://docs.aws.amazon.com/singlesignon/latest/userguide/useraccess.html#assignusers">Assign
        User Access</a> in the <i>IAM Identity Center User Guide</i>. This
        operation returns a paginated response.</p>
      tags:
        - Accounts
        - Assignment
  /logout:
    POST:
      summary: 'Logout '
      description: >-
        <p>Removes the locally stored SSO tokens from the client-side cache and
        sends an API call to the IAM Identity Center service to invalidate the
        corresponding server-side IAM Identity Center sign in session.</p>
        <note> <p>If a user uses IAM Identity Center to access the AWS CLI, the
        user’s IAM Identity Center sign in session is used to obtain an IAM
        session, as specified in the corresponding IAM Identity Center
        permission set. More specifically, IAM Identity Center assumes an IAM
        role in the target account on behalf of the user, and the corresponding
        temporary AWS credentials are returned to the client.</p> <p>After user
        logout, any existing IAM role sessions that were created by using IAM
        Identity Center permission sets continue based on the duration
        configured in the permission set. For more information, see <a
        href="https://docs.aws.amazon.com/singlesignon/latest/userguide/authconcept.html">User
        authentications</a> in the <i>IAM Identity Center User Guide</i>.</
      tags:
        - Logout
