openapi: 3.1.0
info:
  title: supplychain
paths:
  /api/configuration/instances/{instanceId}/bill-of-materials-import-jobs:
    POST:
      summary: 'Create Bill Of Materials Import Job '
      description: >-
        <p>CreateBillOfMaterialsImportJob creates an import job for the Product
        Bill Of Materials (BOM) entity. For information on the product_bom
        entity, see the AWS Supply Chain User Guide.</p> <p>The CSV file must be
        located in an Amazon S3 location accessible to AWS Supply Chain. It is
        recommended to use the same Amazon S3 bucket created during your AWS
        Supply Chain instance creation.</p>
      tags:
        - Bill
        - Configurations
        - Import
        - Instances
        - Jobs
        - Materials
  /api/configuration/instances/{instanceId}/bill-of-materials-import-jobs/{jobId}:
    GET:
      summary: 'Get Bill Of Materials Import Job '
      description: <p>Get status and details of a BillOfMaterialsImpo
      tags:
        - Bill
        - Configurations
        - Import
        - Instances
        - Jobs
        - Materials
