openapi: 3.1.0
info:
  title: textract
paths:
  /:
    POST:
      summary: 'Update Adapter '
      description: >-
        <p>Update the configuration for an adapter. FeatureTypes configurations
        cannot be updated. At least one new parameter must be specified as an
        arg
      tags:
        - Adapter
