openapi: 3.1.0
info:
  title: timestream-query
paths:
  /:
    POST:
      summary: 'Update Scheduled Query '
      description: <p>Update a scheduled
      tags:
        - Queries
        - Scheduled
