openapi: 3.1.0
info:
  title: transcribe-streaming
paths:
  /call-analytics-stream-transcription:
    POST:
      summary: 'Start Call Analytics Stream Transcription '
      description: >-
        <p>Starts a bidirectional HTTP/2 or WebSocket stream where audio is
        streamed to Amazon Transcribe and the transcription results are streamed
        to your application. Use this operation for <a
        href="https://docs.aws.amazon.com/transcribe/latest/dg/call-analytics.html">Call
        Analytics</a> transcriptions.</p> <p>The following parameters are
        required:</p> <ul> <li> <p> <code>language-code</code> </p> </li> <li>
        <p> <code>media-encoding</code> </p> </li> <li> <p>
        <code>sample-rate</code> </p> </li> </ul> <p>For more information on
        streaming with Amazon Transcribe, see <a
        href="https://docs.aws.amazon.com/transcribe/latest/dg/streaming.html">Transcribing
        streaming audio</a>.</p>
      tags:
        - Analytics
        - Call
        - Stream
        - Transcriptions
  /medical-stream-transcription:
    POST:
      summary: 'Start Medical Stream Transcription '
      description: >-
        <p>Starts a bidirectional HTTP/2 or WebSocket stream where audio is
        streamed to Amazon Transcribe Medical and the transcription results are
        streamed to your application.</p> <p>The following parameters are
        required:</p> <ul> <li> <p> <code>language-code</code> </p> </li> <li>
        <p> <code>media-encoding</code> </p> </li> <li> <p>
        <code>sample-rate</code> </p> </li> </ul> <p>For more information on
        streaming with Amazon Transcribe Medical, see <a
        href="https://docs.aws.amazon.com/transcribe/latest/dg/streaming.html">Transcribing
        streaming audio</a>.</p>
      tags:
        - Medical
        - Stream
        - Transcriptions
  /stream-transcription:
    POST:
      summary: 'Start Stream Transcription '
      description: >-
        <p>Starts a bidirectional HTTP/2 or WebSocket stream where audio is
        streamed to Amazon Transcribe and the transcription results are streamed
        to your application.</p> <p>The following parameters are required:</p>
        <ul> <li> <p> <code>language-code</code> or
        <code>identify-language</code> or
        <code>identify-multiple-language</code> </p> </li> <li> <p>
        <code>media-encoding</code> </p> </li> <li> <p> <code>sample-rate</code>
        </p> </li> </ul> <p>For more information on streaming with Amazon
        Transcribe, see <a
        href="https://docs.aws.amazon.com/transcribe/latest/dg/streaming.html">Transcribing
        streaming audi
      tags:
        - Stream
        - Transcriptions
