openapi: 3.1.0
info:
  title: translate
paths:
  /:
    POST:
      summary: 'Update Parallel Data '
      description: >-
        <p>Updates a previously created parallel data resource by importing a
        new input file from Amaz
      tags:
        - Data
        - Parallel
