openapi: 3.1.0
info:
  title: trustedadvisor
paths:
  /v1/organization-recommendations/{organizationRecommendationIdentifier}:
    GET:
      summary: 'Get Organization Recommendation '
      description: >-
        <p>Get a specific recommendation within an AWS Organizations
        organization. This API supports only prioritized recommendations. </p>
      tags:
        - Organizations
        - Recommendations
  /v1/recommendations/{recommendationIdentifier}:
    GET:
      summary: 'Get Recommendation '
      description: <p>Get a specific Recommendation</p>
      tags:
        - Recommendations
  /v1/checks:
    GET:
      summary: 'List Checks '
      description: <p>List a filterable set of Checks</p>
      tags:
        - Checks
  /v1/organization-recommendations/{organizationRecommendationIdentifier}/accounts:
    GET:
      summary: 'List Organization Recommendation Accounts '
      description: >-
        <p>Lists the accounts that own the resources for an organization
        aggregate recommendation. This API only supports prioritized
        recommendations. </p>
      tags:
        - Accounts
        - Organizations
        - Recommendations
  /v1/organization-recommendations/{organizationRecommendationIdentifier}/resources:
    GET:
      summary: 'List Organization Recommendation Resources '
      description: >-
        <p>List Resources of a Recommendation within an Organization. This API
        only supports prioritized recommendations. </p>
      tags:
        - Organizations
        - Recommendations
        - Resources
  /v1/organization-recommendations:
    GET:
      summary: 'List Organization Recommendations '
      description: >-
        <p>List a filterable set of Recommendations within an Organization. This
        API only supports prioritized recommendations. </p>
      tags:
        - Organizations
        - Recommendations
  /v1/recommendations/{recommendationIdentifier}/resources:
    GET:
      summary: 'List Recommendation Resources '
      description: <p>List Resources of a Recommendation</p>
      tags:
        - Recommendations
        - Resources
  /v1/recommendations:
    GET:
      summary: 'List Recommendations '
      description: <p>List a filterable set of Recommendations</p>
      tags:
        - Recommendations
  /v1/organization-recommendations/{organizationRecommendationIdentifier}/lifecycle:
    PUT:
      summary: 'Update Organization Recommendation Lifecycle '
      description: >-
        <p>Update the lifecyle of a Recommendation within an Organization. This
        API only supports prioritized recommendations. </p>
      tags:
        - Lifecycle
        - Organizations
        - Recommendations
  /v1/recommendations/{recommendationIdentifier}/lifecycle:
    PUT:
      summary: 'Update Recommendation Lifecycle '
      description: >-
        <p>Update the lifecyle of a Recommendation. This API only supports
        prioritized recommenda
      tags:
        - Lifecycle
        - Recommendations
