openapi: 3.1.0
info:
  title: voice-id
paths:
  /:
    POST:
      summary: 'Update Watchlist '
      description: >-
        <p>Updates the specified watchlist. Every domain has a default watchlist
        which cannot be upd
      tags:
        - Watchlist
