openapi: 3.1.0
info:
  title: wellarchitected
paths:
  /workloads/{WorkloadId}/associateLenses:
    PATCH:
      summary: 'Associate Lenses '
      description: >-
        <p>Associate a lens to a workload.</p> <p>Up to 10 lenses can be
        associated with a workload in a single API operation. A maximum of 20
        lenses can be associated with a workload.</p> <note> <p>
        <b>Disclaimer</b> </p> <p>By accessing and/or applying custom lenses
        created by another Amazon Web Services user or account, you acknowledge
        that custom lenses created by other users and shared with you are Third
        Party Content as defined in the Amazon Web Services Customer Agreement.
        </p> </note>
      tags:
        - Associate
        - Lenses
        - Workloads
  /workloads/{WorkloadId}/associateProfiles:
    PATCH:
      summary: 'Associate Profiles '
      description: <p>Associate a profile with a workload.</p>
      tags:
        - Associate
        - Profiles
        - Workloads
  /lenses/{LensAlias}/shares:
    GET:
      summary: 'List Lens Shares '
      description: <p>List the lens shares associated with the lens.</p>
      tags:
        - Alias
        - Lens
        - Lenses
        - Shares
  /lenses/{LensAlias}/versions:
    POST:
      summary: 'Create Lens Version '
      description: >-
        <p>Create a new lens version.</p> <p>A lens can have up to 100
        versions.</p> <p>Use this operation to publish a new lens version after
        you have imported a lens. The <code>LensAlias</code> is used to identify
        the lens to be published. The owner of a lens can share the lens with
        other Amazon Web Services accounts and users in the same Amazon Web
        Services Region. Only the owner of a lens can delete it. </p>
      tags:
        - Alias
        - Lens
        - Lenses
        - Versions
  /workloads/{WorkloadId}/milestones:
    POST:
      summary: 'Create Milestone '
      description: <p>Create a milestone for an existing workload.</p>
      tags:
        - Milestones
        - Workloads
  /profiles:
    POST:
      summary: 'Create Profile '
      description: <p>Create a profile.</p>
      tags:
        - Profiles
  /profiles/{ProfileArn}/shares:
    GET:
      summary: 'List Profile Shares '
      description: <p>List profile shares.</p>
      tags:
        - ARN
        - Profiles
        - Shares
  /reviewTemplates:
    GET:
      summary: 'List Review Templates '
      description: <p>List review templates.</p>
      tags:
        - Reviews
        - Templates
  /templates/shares/{TemplateArn}:
    GET:
      summary: 'List Template Shares '
      description: <p>List review template shares.</p>
      tags:
        - ARN
        - Shares
        - Templates
  /workloads:
    POST:
      summary: 'Create Workload '
      description: >-
        <p>Create a new workload.</p> <p>The owner of a workload can share the
        workload with other Amazon Web Services accounts, users, an
        organization, and organizational units (OUs) in the same Amazon Web
        Services Region. Only the owner of a workload can delete it.</p> <p>For
        more information, see <a
        href="https://docs.aws.amazon.com/wellarchitected/latest/userguide/define-workload.html">Defining
        a Workload</a> in the <i>Well-Architected Tool User Guide</i>.</p>
        <important> <p>Either <code>AwsRegions</code>,
        <code>NonAwsRegions</code>, or both must be specified when creating a
        workload.</p> <p>You also must specify <code>ReviewOwner</code>, even
        though the parameter is listed as not being required in the following
        section. </p> </important> <p>When creating a workload using a review
        template, you must have the following IAM permissions:</p> <ul> <li> <p>
        <code>wellarchitected:GetReviewTemplate</code> </p> </li> <li> <p>
        <code>wellarchitected:GetReviewTemplateAnswer</code> </p> </li> <li> <p>
        <code>wellarchitected:ListReviewTemplateAnswers</code> </p> </li> <li>
        <p> <code>wellarchitected:GetReviewTemplateLensReview</code> </p> </li>
        </ul>
      tags:
        - Workloads
  /workloads/{WorkloadId}/shares:
    GET:
      summary: 'List Workload Shares '
      description: <p>List the workload shares associated with the workload.</p>
      tags:
        - Shares
        - Workloads
  /lenses/{LensAlias}:
    GET:
      summary: 'Get Lens '
      description: <p>Get an existing lens.</p>
      tags:
        - Alias
        - Lens
        - Lenses
  /lenses/{LensAlias}/shares/{ShareId}:
    DELETE:
      summary: 'Delete Lens Share '
      description: >-
        <p>Delete a lens share.</p> <p>After the lens share is deleted, Amazon
        Web Services accounts, users, organizations, and organizational units
        (OUs) that you shared the lens with can continue to use it, but they
        will no longer be able to apply it to new workloads.</p> <note> <p>
        <b>Disclaimer</b> </p> <p>By sharing your custom lenses with other
        Amazon Web Services accounts, you acknowledge that Amazon Web Services
        will make your custom lenses available to those other accounts. Those
        other accounts may continue to access and use your shared custom lenses
        even if you delete the custom lenses from your own Amazon Web Services
        account or terminate your Amazon Web Services account.</p> </note>
      tags:
        - Alias
        - Lens
        - Lenses
        - Share
        - Shares
  /profiles/{ProfileArn}:
    PATCH:
      summary: 'Update Profile '
      description: <p>Update a profile.</p>
      tags:
        - ARN
        - Profiles
  /profiles/{ProfileArn}/shares/{ShareId}:
    DELETE:
      summary: 'Delete Profile Share '
      description: <p>Delete a profile share.</p>
      tags:
        - ARN
        - Profiles
        - Share
        - Shares
  /reviewTemplates/{TemplateArn}:
    PATCH:
      summary: 'Update Review Template '
      description: <p>Update a review template.</p>
      tags:
        - ARN
        - Reviews
        - Templates
  /templates/shares/{TemplateArn}/{ShareId}:
    DELETE:
      summary: 'Delete Template Share '
      description: >-
        <p>Delete a review template share.</p> <p>After the review template
        share is deleted, Amazon Web Services accounts, users, organizations,
        and organizational units (OUs) that you shared the review template with
        will no longer be able to apply it to new workloads.</p>
      tags:
        - ARN
        - Share
        - Shares
        - Templates
  /workloads/{WorkloadId}:
    PATCH:
      summary: 'Update Workload '
      description: <p>Update an existing workload.</p>
      tags:
        - Workloads
  /workloads/{WorkloadId}/shares/{ShareId}:
    PATCH:
      summary: 'Update Workload Share '
      description: <p>Update a workload share.</p>
      tags:
        - Share
        - Shares
        - Workloads
  /workloads/{WorkloadId}/disassociateLenses:
    PATCH:
      summary: 'Disassociate Lenses '
      description: >-
        <p>Disassociate a lens from a workload.</p> <p>Up to 10 lenses can be
        disassociated from a workload in a single API operation.</p> <note>
        <p>The Amazon Web Services Well-Architected Framework lens
        (<code>wellarchitected</code>) cannot be removed from a workload.</p>
        </note>
      tags:
        - Disassociate
        - Lenses
        - Workloads
  /workloads/{WorkloadId}/disassociateProfiles:
    PATCH:
      summary: 'Disassociate Profiles '
      description: <p>Disassociate a profile from a workload.</p>
      tags:
        - Disassociate
        - Profiles
        - Workloads
  /lenses/{LensAlias}/export:
    GET:
      summary: 'Export Lens '
      description: >-
        <p>Export an existing lens.</p> <p>Only the owner of a lens can export
        it. Lenses provided by Amazon Web Services (Amazon Web Services Official
        Content) cannot be exported.</p> <p>Lenses are defined in JSON. For more
        information, see <a
        href="https://docs.aws.amazon.com/wellarchitected/latest/userguide/lenses-format-specification.html">JSON
        format specification</a> in the <i>Well-Architected Tool User
        Guide</i>.</p> <note> <p> <b>Disclaimer</b> </p> <p>Do not include or
        gather personal identifiable information (PII) of end users or other
        identifiable individuals in or via your custom lenses. If your custom
        lens or those shared with you and used in your account do include or
        collect PII you are responsible for: ensuring that the included PII is
        processed in accordance with applicable law, providing adequate privacy
        notices, and obtaining necessary consents for processing such data.</p>
        </note>
      tags:
        - Alias
        - Exports
        - Lens
        - Lenses
  /workloads/{WorkloadId}/lensReviews/{LensAlias}/answers/{QuestionId}:
    PATCH:
      summary: 'Update Answer '
      description: <p>Update the answer to a specific question in a workload review.</p>
      tags:
        - Alias
        - Answers
        - Lens
        - Questions
        - Reviews
        - Workloads
  /consolidatedReport:
    GET:
      summary: 'Get Consolidated Report '
      description: >-
        <p>Get a consolidated report of your workloads.</p> <p>You can
        optionally choose to include workloads that have been shared with
        you.</p>
      tags:
        - Ated
        - Consol
        - Consolidated
        - Reports
  /workloads/{WorkloadId}/lensReviews/{LensAlias}:
    PATCH:
      summary: 'Update Lens Review '
      description: <p>Update lens review for a particular workload.</p>
      tags:
        - Alias
        - Lens
        - Reviews
        - Workloads
  /workloads/{WorkloadId}/lensReviews/{LensAlias}/report:
    GET:
      summary: 'Get Lens Review Report '
      description: <p>Get lens review report.</p>
      tags:
        - Alias
        - Lens
        - Reports
        - Reviews
        - Workloads
  /lenses/{LensAlias}/versionDifference:
    GET:
      summary: 'Get Lens Version Difference '
      description: <p>Get lens version differences.</p>
      tags:
        - Alias
        - Difference
        - Lens
        - Lenses
        - Versions
  /workloads/{WorkloadId}/milestones/{MilestoneNumber}:
    GET:
      summary: 'Get Milestone '
      description: <p>Get a milestone for an existing workload.</p>
      tags:
        - Milestones
        - Numbers
        - Workloads
  /profileTemplate:
    GET:
      summary: 'Get Profile Template '
      description: <p>Get profile template.</p>
      tags:
        - Profiles
        - Templates
  /reviewTemplates/{TemplateArn}/lensReviews/{LensAlias}/answers/{QuestionId}:
    PATCH:
      summary: 'Update Review Template Answer '
      description: <p>Update a review template answer.</p>
      tags:
        - ARN
        - Alias
        - Answers
        - Lens
        - Questions
        - Reviews
        - Templates
  /reviewTemplates/{TemplateArn}/lensReviews/{LensAlias}:
    PATCH:
      summary: 'Update Review Template Lens Review '
      description: <p>Update a lens review associated with a review template.</p>
      tags:
        - ARN
        - Alias
        - Lens
        - Reviews
        - Templates
  /importLens:
    PUT:
      summary: 'Import Lens '
      description: >-
        <p>Import a new custom lens or update an existing custom lens.</p> <p>To
        update an existing custom lens, specify its ARN as the
        <code>LensAlias</code>. If no ARN is specified, a new custom lens is
        created.</p> <p>The new or updated lens will have a status of
        <code>DRAFT</code>. The lens cannot be applied to workloads or shared
        with other Amazon Web Services accounts until it's published with
        <a>CreateLensVersion</a>.</p> <p>Lenses are defined in JSON. For more
        information, see <a
        href="https://docs.aws.amazon.com/wellarchitected/latest/userguide/lenses-format-specification.html">JSON
        format specification</a> in the <i>Well-Architected Tool User
        Guide</i>.</p> <p>A custom lens cannot exceed 500 KB in size.</p> <note>
        <p> <b>Disclaimer</b> </p> <p>Do not include or gather personal
        identifiable information (PII) of end users or other identifiable
        individuals in or via your custom lenses. If your custom lens or those
        shared with you and used in your account do include or collect PII you
        are responsible for: ensuring that the included PII is processed in
        accordance with applicable law, providing adequate privacy notices, and
        obtaining necessary consents for processing such data.</p> </note>
      tags:
        - Import
        - Lens
  /workloads/{WorkloadId}/lensReviews/{LensAlias}/answers:
    GET:
      summary: 'List Answers '
      description: <p>List of answers for a particular workload and lens.</p>
      tags:
        - Alias
        - Answers
        - Lens
        - Reviews
        - Workloads
  /workloads/{WorkloadId}/checks:
    POST:
      summary: 'List Check Details '
      description: >-
        <p>List of Trusted Advisor check details by account related to the
        workload.</p>
      tags:
        - Checks
        - Details
        - Workloads
  /workloads/{WorkloadId}/checkSummaries:
    POST:
      summary: 'List Check Summaries '
      description: >-
        <p>List of Trusted Advisor checks summarized for all accounts related to
        the workload.</p>
      tags:
        - Checks
        - Summaries
        - Workloads
  /workloads/{WorkloadId}/lensReviews/{LensAlias}/improvements:
    GET:
      summary: 'List Lens Review Improvements '
      description: <p>List lens review improvements.</p>
      tags:
        - Alias
        - Improvements
        - Lens
        - Reviews
        - Workloads
  /workloads/{WorkloadId}/lensReviews:
    GET:
      summary: 'List Lens Reviews '
      description: <p>List lens reviews for a particular workload.</p>
      tags:
        - Lens
        - Reviews
        - Workloads
  /lenses:
    GET:
      summary: 'List Lenses '
      description: <p>List the available lenses.</p>
      tags:
        - Lenses
  /workloads/{WorkloadId}/milestonesSummaries:
    POST:
      summary: 'List Milestones '
      description: <p>List all milestones for an existing workload.</p>
      tags:
        - Milestones
        - Summaries
        - Workloads
  /notifications:
    POST:
      summary: 'List Notifications '
      description: <p>List lens notifications.</p>
      tags:
        - Notifications
  /profileNotifications/:
    GET:
      summary: 'List Profile Notifications '
      description: <p>List profile notifications.</p>
      tags:
        - Notifications
        - Profiles
  /profileSummaries:
    GET:
      summary: 'List Profiles '
      description: <p>List profiles.</p>
      tags:
        - Profiles
        - Summaries
  /reviewTemplates/{TemplateArn}/lensReviews/{LensAlias}/answers:
    GET:
      summary: 'List Review Template Answers '
      description: <p>List the answers of a review template.</p>
      tags:
        - ARN
        - Alias
        - Answers
        - Lens
        - Reviews
        - Templates
  /shareInvitations:
    GET:
      summary: 'List Share Invitations '
      description: >-
        <p>List the share invitations.</p> <p> <code>WorkloadNamePrefix</code>,
        <code>LensNamePrefix</code>, <code>ProfileNamePrefix</code>, and
        <code>TemplateNamePrefix</code> are mutually exclusive. Use the
        parameter that matches your <code>ShareResourceType</code>.</p>
      tags:
        - Invitations
        - Share
  /tags/{WorkloadArn}:
    DELETE:
      summary: 'Untag Resource '
      description: >-
        <p>Deletes specified tags from a resource.</p> <note> <p>The WorkloadArn
        parameter can be a workload ARN, a custom lens ARN, a profile ARN, or
        review template ARN.</p> </note> <p>To specify multiple tags, use
        separate <b>tagKeys</b> parameters, for example:</p> <p> <code>DELETE
        /tags/WorkloadArn?tagKeys=key1&amp;tagKeys=key2</code> </p>
      tags:
        - ARN
        - Resources
        - Tags
        - Untag
        - Workloads
  /workloadsSummaries:
    POST:
      summary: 'List Workloads '
      description: <p>Paginated list of workloads.</p>
      tags:
        - Summaries
        - Workloads
  /global-settings:
    PATCH:
      summary: 'Update Global Settings '
      description: >-
        <p>Updates whether the Amazon Web Services account is opted into
        organization sharing and discovery integration features.</p>
      tags:
        - Global
        - Settings
  /shareInvitations/{ShareInvitationId}:
    PATCH:
      summary: 'Update Share Invitation '
      description: >-
        <p>Update a workload or custom lens share invitation.</p> <note> <p>This
        API operation can be called independently of any resource. Previous
        documentation implied that a workload ARN must be specified.</p> </note>
      tags:
        - Invitation
        - Invitations
        - Share
  /workloads/{WorkloadId}/lensReviews/{LensAlias}/upgrade:
    PUT:
      summary: 'Upgrade Lens Review '
      description: <p>Upgrade lens review for a particular workload.</p>
      tags:
        - Alias
        - Lens
        - Reviews
        - Upgrade
        - Workloads
  /workloads/{WorkloadId}/profiles/{ProfileArn}/upgrade:
    PUT:
      summary: 'Upgrade Profile Version '
      description: <p>Upgrade a profile.</p>
      tags:
        - ARN
        - Profiles
        - Upgrade
        - Versions
        - Workloads
  /reviewTemplates/{TemplateArn}/lensReviews/{LensAlias}/upgrade:
    PUT:
      summary: 'Upgrade Review Template Lens Review '
      description: <p>Upgrade the lens review of a review tem
      tags:
        - ARN
        - Alias
        - Lens
        - Reviews
        - Templates
        - Upgrade
