openapi: 3.1.0
info:
  title: workspaces-thin-client
paths:
  /environments:
    GET:
      summary: 'List Environments '
      description: <p>Returns a list of environments.</p>
      tags:
        - Environments
  /devices/{id}:
    PATCH:
      summary: 'Update Device '
      description: <p>Updates a thin client device.</p>
      tags:
        - Device
        - Devices
  /environments/{id}:
    PATCH:
      summary: 'Update Environment '
      description: <p>Updates an environment.</p>
      tags:
        - Environments
  /deregister-device/{id}:
    POST:
      summary: 'Deregister Device '
      description: <p>Deregisters a thin client device.</p>
      tags:
        - Deregister
        - Device
  /softwaresets/{id}:
    PATCH:
      summary: 'Update Software Set '
      description: <p>Updates a software set.</p>
      tags:
        - Sets
        - Software
        - Software Sets
  /devices:
    GET:
      summary: 'List Devices '
      description: <p>Returns a list of thin client devices.</p>
      tags:
        - Devices
  /softwaresets:
    GET:
      summary: 'List Software Sets '
      description: <p>Returns a list of software sets.</p>
      tags:
        - Sets
        - Software
        - Software Sets
  /tags/{resourceArn}:
    DELETE:
      summary: 'Untag Resource '
      description: <p>Removes a tag or tags from a res
      tags:
        - ARN
        - Resources
        - Tags
        - Untag
